import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {test,expect,EMAIL,PASSWORD,TOKEN,entrar,sembrar,abrir,leer,modelo,guardar,lienzo,cosa,seleccionar,tecla,crear,conectar,opl,guardado,editarOpl,aplicarTexto,descargar,cerrarInformes,captura,arrastrar,seleccionarEnlace,seleccionarSimbolo,arcos,navegar,arrastrarConexion} from './soporte';
import type {Page,Locator} from '@playwright/test';
const svg=(p:Page)=>p.getByLabel(/^Diagrama /);
const estado=(p:Page,n:string)=>svg(p).getByText(n,{exact:true});
const enlaceEnInspector=async(p:Page,n:string)=>{await seleccionar(p,n);await p.getByRole('complementary',{name:'Propiedades y OPL'}).getByRole('button',{name:/→/}).first().click();};
const exportar=async(p:Page)=>{await p.getByRole('button',{name:'Exportar ▾',exact:true}).click();return p.getByRole('dialog',{name:'Exportar',exact:true});};
test.setTimeout(60000);
test('WP-17 DESIGN§10.7 01 acceso: error uniforme, Biblioteca y salida',async({page})=>{
 await page.goto('/');await expect.poll(()=>page.evaluate(()=>document.body.dataset.listo)).toBe('1');
 await page.getByLabel('Correo',{exact:true}).fill(EMAIL);await page.getByLabel('Clave',{exact:true}).fill('erronea-sintetica');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('Credenciales inválidas');
 await page.getByLabel('Clave',{exact:true}).fill(PASSWORD);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page.getByRole('heading',{name:'Biblioteca',exact:true})).toBeVisible();await page.getByRole('button',{name:'Salir',exact:true}).click();await expect(page.getByRole('heading',{name:'Entrar',exact:true})).toBeVisible();await captura(page,'01-acceso');
});
test('T-286 02 Biblioteca: nuevo, nombre, descarga, papelera y restaurar',async({page,request})=>{
 await entrar(page);await page.getByRole('button',{name:'Nuevo',exact:true}).click();await page.getByLabel('Nombre del modelo',{exact:true}).fill('Biblioteca e2e');await page.getByRole('button',{name:'Crear modelo',exact:true}).click();await expect(lienzo(page)).toBeVisible();await cerrarInformes(page);await expect(page.getByText('Crea un objeto o un proceso para comenzar.',{exact:false})).toBeVisible();
 const id=decodeURIComponent(new URL(page.url()).hash.split('/')[2]!);expect(id).toBeTruthy();
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await page.getByLabel('Acciones de Biblioteca e2e').click();await page.getByRole('button',{name:'Renombrar',exact:true}).click();await page.getByLabel('Renombrar modelo',{exact:true}).fill('Biblioteca renombrada');await page.getByRole('button',{name:'Guardar nombre'}).click();await cerrarInformes(page);await expect.poll(async()=>modelo(await leer(request,id!)).modelo.nombre).toBe('Biblioteca renombrada');
 await page.getByLabel('Acciones de Biblioteca renombrada').click();const texto=await descargar(page,page.getByRole('link',{name:'Descargar JSON',exact:true}));expect(texto).toBe((await leer(request,id!)).texto);await page.getByRole('button',{name:'Eliminar',exact:true}).click();await page.getByRole('button',{name:'Mover a la papelera',exact:true}).click();await expect(page.getByRole('button',{name:'Biblioteca renombrada',exact:true})).toHaveCount(0);await page.getByText(/^Papelera \(/).click();await page.getByRole('button',{name:'Restaurar',exact:true}).first().click();await cerrarInformes(page);await expect(page.getByRole('button',{name:'Biblioteca renombrada',exact:true})).toBeVisible();expect(modelo(await leer(request,id!)).modelo.id).toBe(id);await expect(page.getByRole('tab')).toHaveCount(0);await captura(page,'02-biblioteca');
});
test('T-287 03 importar System_Diagram: Informe, opt-in, OPD y GET canónico',async({page,request})=>{
 await entrar(page);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Importar',exact:true}).click();await(await chooser).setFiles(resolve('fixtures/v0/System_Diagram.json'));const informe=page.getByRole('dialog',{name:'Informe de importación',exact:true});await expect(informe).toBeVisible();await expect(informe.getByText(/cosas · .* estados · .* enlaces · .* OPDs/)).toBeVisible();await expect(informe.getByText(/^Visibilidad por OPD/)).toBeVisible();await expect(informe.getByRole('checkbox')).toHaveCount(0);await captura(page,'03-informe');await informe.getByRole('button',{name:'Crear modelo',exact:true}).click();await expect(lienzo(page)).toBeVisible();await cerrarInformes(page);await guardado(page);
 const id=decodeURIComponent(new URL(page.url()).hash.split('/')[2]!)!;const d=await leer(request,id),v=modelo(d);expect(v.formato).toBe('deep-opm-pro.modelo.v0');expect(v.modelo.id).toBe(id);expect(Object.keys(v.modelo.entidades)).toHaveLength(8);expect(await opl(page).evaluate(root=>Array.from(root.getElementsByTagName('p')).filter(n=>n.hasAttribute('data-linea')).map(n=>(n.textContent??'').trim()))).toEqual(['SD','Main System Doing es físico.','Beneficiary Group es físico.','Beneficiary Relevant Attribute puede estar problematic o satisfactory.','Estado problematic de Beneficiary Relevant Attribute es inicial.','Estado satisfactory de Beneficiary Relevant Attribute es final.','System Handler es físico.','Main System Doing consume Main Input.','Main System Doing genera Main Output.','Main System Doing afecta Beneficiary Relevant Attribute.','System Handler maneja Main System Doing.','Main System Doing requiere System Name.','Main System Doing requiere System Tool Set.','Beneficiary Group exhibe Beneficiary Relevant Attribute.','System Name exhibe Main System Doing.']);expect(Object.keys(v.modelo.enlaces)).toEqual(['e-19','e-21','e-23','e-25','e-27','e-29','e-31','e-33']);const revalidado=await guardar(request,id,d.texto,d.rev);expect(await revalidado.json()).not.toHaveProperty('canonicalizado');expect((await leer(request,id)).texto).toBe(d.texto);await expect(cosa(page,'Beneficiary Group')).toBeVisible();await captura(page,'03-system');
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();const archivo=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Importar',exact:true}).click();const fixtures=JSON.parse(readFileSync(resolve('e2e/modelos.json'),'utf8'));await(await archivo).setFiles({name:'Duplicados.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixtures.duplicados))});const dup=page.getByRole('dialog',{name:'Informe de importación',exact:true});await expect(dup.getByRole('checkbox',{name:/Aplicar 2 reparaciones/})).not.toBeChecked();await dup.getByRole('button',{name:'Crear modelo',exact:true}).click();await expect(lienzo(page)).toBeVisible();await cerrarInformes(page);await guardado(page);const idDup=decodeURIComponent(new URL(page.url()).hash.split('/')[2]!);expect(Object.values(modelo(await leer(request,idDup)).modelo.entidades).map(x=>x.nombre)).toEqual(['Pedido','Pedido','Pedido']);
});
test('T-011 04 O/P, nombre inválido, Escape y colisión trae identidad',async({page,request})=>{
 await sembrar(request,'vacio','e2e-04');await abrir(page,'e2e-04');await crear(page,'objeto','Cliente',180,160);await crear(page,'proceso','Atender',500,320);await guardado(page);const antes=await leer(request,'e2e-04');expect(Object.values(modelo(antes).modelo.entidades).map(c=>c.nombre)).toEqual(['Cliente','Atender']);
 await tecla(page,'o');const input=page.getByRole('textbox',{name:'Nombre del objeto'});await input.fill('cliente');await expect(page.getByText(/Traer misma identidad aquí/)).toBeVisible();await input.fill('123');await expect(page.getByText(/léxico/i)).toBeVisible();await input.press('Enter');await expect(input).toBeVisible();await input.press('Escape');await guardado(page);expect((await leer(request,'e2e-04')).texto).toBe(antes.texto);
 await seleccionar(page,'Cliente');await tecla(page,'Delete');await tecla(page,'o');const colision=page.getByRole('textbox',{name:'Nombre del objeto'});await colision.fill('Cliente');await expect(page.getByText(/Traer misma identidad aquí/)).toBeVisible();await colision.press('Enter');await guardado(page);const despues=modelo(await leer(request,'e2e-04'));expect(Object.keys(despues.modelo.entidades)).toEqual(Object.keys(modelo(antes).modelo.entidades));expect(Object.values(despues.modelo.opds.sd!.apariencias).map(a=>a.entidadId)).toContain(Object.keys(despues.modelo.entidades)[0]);await captura(page,'04-creacion');
});
test('T-204 05 esencia, afiliación y métricas DOM±2%',async({page,request})=>{
 await sembrar(request,'basico','e2e-05');await abrir(page,'e2e-05');await seleccionar(page,'Pedido');await page.getByRole('combobox',{name:'Afiliación',exact:true}).selectOption('ambiental');await expect(opl(page)).toContainText('es ambiental');await expect(cosa(page,'Pedido')).toHaveAttribute('aria-label',/física|fisica/);
 const detalles=await cosa(page,'Pedido').evaluate(n=>({sombra:Array.from(n.children).some(x=>x.getAttribute('filter')?.startsWith('url(')),dash:Array.from(n.children).some(x=>x.getAttribute('stroke-dasharray')!==null)}));expect(detalles.sombra).toBe(true);expect(detalles.dash).toBe(true);await expect(opl(page)).toContainText('es físico');
 const esperadas=JSON.parse(readFileSync(resolve('e2e/metricas.json'),'utf8')) as Record<string,number>;
 await page.evaluate(()=>document.fonts.ready);for(const n of ['Pedido','Factura','Procesar']){const b=await svg(page).getByText(n,{exact:true}).evaluate(n=>(n as SVGGraphicsElement).getBBox().width);expect(b).toBeGreaterThan(0);expect(Math.abs(b-esperadas[n]!)/esperadas[n]!).toBeLessThanOrEqual(.02);}await captura(page,'05-metricas');
});
test('T-015 06 estados: S, cancelar, designaciones, ocultos y OPL',async({page,request})=>{
 await sembrar(request,'simple','e2e-06');await abrir(page,'e2e-06');await seleccionar(page,'Pedido');await tecla(page,'s');await page.getByRole('textbox',{name:'Nombre del estado'}).fill('nuevo');await page.getByRole('textbox',{name:'Nombre del estado'}).press('Enter');await expect(estado(page,'nuevo')).toBeVisible();await seleccionar(page,'Pedido');await tecla(page,'s');await page.getByRole('textbox',{name:'Nombre del estado'}).fill('cancelado');await page.getByRole('textbox',{name:'Nombre del estado'}).press('Escape');await guardado(page);expect(Object.keys(modelo(await leer(request,'e2e-06')).modelo.estados)).toHaveLength(1);await expect(estado(page,'estado1')).toHaveCount(0);
 await estado(page,'nuevo').click();for(const k of ['i','f','d'])await tecla(page,k);await expect(opl(page)).toContainText(/inicial.*final|final.*inicial/s);await expect(page.getByRole('checkbox',{name:'porDefecto',exact:true})).toBeChecked();await tecla(page,'h');await expect(svg(page).getByText('⋯1',{exact:true})).toBeVisible();await expect(opl(page)).toContainText('nuevo');await guardado(page);const vs=Object.values(modelo(await leer(request,'e2e-06')).modelo.estados);expect(vs[0]).toMatchObject({nombre:'nuevo',esInicial:true,esFinal:true,designaciones:['default']});await captura(page,'06-estados');
});
test('T-040 07 enlace: arrastre, opciones, consumo y agente informacional',async({page,request})=>{
 await sembrar(request,'simple','e2e-07');await abrir(page,'e2e-07');await seleccionar(page,'Pedido');await arrastrarConexion(page,'cosa:o',cosa(page,'Procesar'));const d=page.getByRole('dialog',{name:/^Enlace:/});await expect(d).toBeVisible();await expect(d.getByRole('menuitem',{name:/consumo · directo/})).toContainText('Procesar consume Pedido.');await expect(d.getByText(/tipos no disponibles/)).toBeVisible();await d.getByRole('menuitem',{name:/consumo · directo/}).click();await expect(opl(page)).toContainText('Procesar consume Pedido.');await guardado(page);expect(modelo(await leer(request,'e2e-07')).modelo.enlaces).toMatchObject({'e-1000':{tipo:'consumo'}});
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'simple','e2e-07b');await abrir(page,'e2e-07b');await seleccionar(page,'Pedido');await page.getByLabel('Esencia',{exact:true}).selectOption('informacional');await tecla(page,'r');await cosa(page,'Procesar').click();await d.getByText(/tipos no disponibles/).click();await expect(d.getByText(/agente.*fisic|agente.*físic/i)).toBeVisible();await d.getByRole('button',{name:'Cerrar diálogo'}).click();await captura(page,'07-consumo');
});
test('T-051 08 segundo gesto: completar TS3 y abanico de resultados',async({page,request})=>{
 await sembrar(request,'ts4','e2e-08a');await abrir(page,'e2e-08a');await seleccionar(page,'Procesar');await arrastrarAEstado(page,'cosa:p','o-s2');const d=page.getByRole('dialog',{name:/^Enlace:/});await expect(d.getByText(/Completar cambio/i)).toBeVisible();await expect(d.getByRole('menuitem').first()).toContainText('Completar cambio: de pendiente a pagado');await captura(page,'08-completar-menu');await d.getByRole('menuitem',{name:/Completar cambio/}).click();await guardado(page);const ts=modelo(await leer(request,'e2e-08a')).modelo.enlaces;expect(Object.keys(ts)).toEqual(['e1']);expect(ts.e1).toMatchObject({estadoEntradaId:'o-s1',estadoSalidaId:'o-s2'});await expect(opl(page)).toContainText(/pendiente.*pagado/s);
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'resultados','e2e-08b');await page.getByLabel('Buscar modelo').fill('e2e-08b');await page.reload();await page.getByRole('button',{name:'E2E e2e-08b',exact:true}).click();await cerrarInformes(page);await seleccionar(page,'Procesar');await arrastrarConexion(page,'cosa:p',cosa(page,'Factura'));const legal=page.getByRole('dialog',{name:/^Enlace:/});await expect(legal.getByRole('menuitem',{name:/resultado · directo/})).toContainText('Procesar genera Factura.');await expect(legal.getByRole('button',{name:'Abanico XOR con el existente',exact:true})).toHaveCount(0);await legal.getByRole('button',{name:'Cerrar diálogo'}).click();expect(Object.keys(modelo(await leer(request,'e2e-08b')).modelo.enlaces)).toEqual(['e1']);
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'resultadosEstados','e2e-08c');await abrir(page,'e2e-08c');await seleccionar(page,'Procesar');await arrastrarAEstado(page,'cosa:p','s-1001');await expect(page.getByRole('button',{name:'Abanico XOR con el existente',exact:true})).toBeVisible();await captura(page,'08-abanico-menu');await page.getByRole('button',{name:'Abanico XOR con el existente',exact:true}).click();await guardado(page);const resultado=modelo(await leer(request,'e2e-08c'));expect(Object.keys(resultado.modelo.abanicos as object)).toHaveLength(1);expect(resultado.modelo.enlaces.e1).toMatchObject({id:'e1',tipo:'resultado',origenId:{kind:'entidad',id:'p'},destinoId:{kind:'estado',id:'s-1000'}});expect(Object.values(resultado.modelo.enlaces).find(e=>e.id!=='e1')).toMatchObject({tipo:'resultado',origenId:{kind:'entidad',id:'p'},destinoId:{kind:'estado',id:'s-1001'}});expect(await arcos(page)).toBe(1);await expect(opl(page)).toContainText('exactamente uno de');await expect(opl(page)).toContainText(/aprobado.*rechazado/s);await captura(page,'08-segundo-gesto');
 for(const operador of ['XOR','OR'] as const){const id=`e2e-08-efecto-${operador}`;await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'ts4',id);await abrir(page,id);const antes=await leer(request,id);await seleccionarEstadoAlcanzable(page,'o-s2');await expect(page.getByRole('heading',{name:'Pedido · pagado',exact:true})).toBeVisible();await tecla(page,'r');await cosa(page,'Procesar').click();const fila=page.getByRole('dialog',{name:/^Enlace:/}).getByRole('menuitem',{name:/efecto · inverso/}).locator('..');await expect(fila.getByRole('button',{name:`Abanico ${operador} con el existente`,exact:true})).toBeVisible();await fila.getByRole('button',{name:`Abanico ${operador} con el existente`,exact:true}).click();await guardado(page);const doc=modelo(await leer(request,id));expect(doc.modelo.enlaces.e1).toMatchObject({id:'e1',tipo:'efecto',estadoEntradaId:'o-s1'});expect(Object.values(doc.modelo.enlaces).find(e=>e.id!=='e1')).toMatchObject({tipo:'efecto',estadoEntradaId:'o-s2'});expect(Object.values(doc.modelo.enlaces).every(e=>e.estadoSalidaId===undefined)).toBe(true);expect(Object.keys(doc.modelo.abanicos as object)).toHaveLength(1);expect(await arcos(page)).toBe(operador==='XOR'?1:2);await expect(opl(page)).toContainText(/pendiente.*pagado/s);await captura(page,`08-efecto-${operador}`);await accionGuardada(page,id,'Control+z');expect((await leer(request,id)).texto).toBe(antes.texto);}
});
test('T-214 09 control, etiqueta y multiplicidad femenina',async({page,request})=>{
 await sembrar(request,'entrada','e2e-09a');await abrir(page,'e2e-09a');await seleccionarEnlace(page,'e1');await tecla(page,'c');await expect(svg(page).getByText('c',{exact:true})).toBeVisible();await expect(opl(page)).toContainText(/si .*Pedido/);await guardado(page);expect(modelo(await leer(request,'e2e-09a')).modelo.enlaces.e1).toMatchObject({modificador:'condicion'});
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'femenino','e2e-09b');await page.reload();await page.getByRole('button',{name:'E2E e2e-09b',exact:true}).click();await cerrarInformes(page);await seleccionarEnlace(page,'e1');for(const valor of ['?','*','+',undefined]){await accionGuardada(page,'e2e-09b','m');const e=modelo(await leer(request,'e2e-09b')).modelo.enlaces.e1!;expect(e.multiplicidadDestino).toBe(valor);expect(e.multiplicidadOrigen).toBeUndefined();expect(e.etiqueta).toBe('usa');expect(e.id).toBe('e1');}for(let i=0;i<3;i++)await accionGuardada(page,'e2e-09b','m');await expect(opl(page)).toContainText('al menos una Olla');for(const valor of ['?','*','+',undefined]){await accionGuardada(page,'e2e-09b','Shift+m');const e=modelo(await leer(request,'e2e-09b')).modelo.enlaces.e1!;expect(e.multiplicidadOrigen).toBe(valor);expect(e.multiplicidadDestino).toBe('+');expect(e.id).toBe('e1');expect(e.etiqueta).toBe('usa');}await accionGuardada(page,'e2e-09b','Control+z');expect(modelo(await leer(request,'e2e-09b')).modelo.enlaces.e1!.multiplicidadOrigen).toBe('+');await accionGuardada(page,'e2e-09b','Control+Shift+z');expect(modelo(await leer(request,'e2e-09b')).modelo.enlaces.e1).toMatchObject({etiqueta:'usa',multiplicidadDestino:'+'});
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'resultados','e2e-09c');await page.reload();await page.getByRole('button',{name:'E2E e2e-09c',exact:true}).click();await cerrarInformes(page);await seleccionarEnlace(page,'e1');const prohibida=page.getByRole('combobox',{name:'Control',exact:true}).getByRole('option',{name:'c',exact:true});expect(await prohibida.evaluate(n=>({opcion:n.tagName,control:n.closest('label')?.control===n.parentElement,selectHabilitado:n.parentElement instanceof HTMLSelectElement&&!n.parentElement.disabled}))).toEqual({opcion:'OPTION',control:true,selectHabilitado:true});await expect(prohibida).toHaveJSProperty('disabled',true);await expect(prohibida).toHaveAttribute('disabled','');await expect(prohibida).toHaveAttribute('title','El control solo puede ser c o e y solo en una entrada canónica.');await captura(page,'09-control');
});
test('T-216 10 abanico XOR/OR y disolver conservando las ramas',async({page,request})=>{
 await sembrar(request,'fan','e2e-10');await abrir(page,'e2e-10');await seleccionarEnlace(page,'e1');await seleccionarEnlace(page,'e2',true);await tecla(page,'x');await expect(opl(page)).toContainText('consume exactamente uno de');expect(await arcos(page)).toBe(1);await guardado(page);const first=modelo(await leer(request,'e2e-10'));const f=Object.keys(first.modelo.abanicos as object)[0]!;
 const p=await puntoAbanico(page,f);await page.mouse.click(p.x,p.y);await tecla(page,'x');await expect(opl(page)).toContainText('consume al menos uno de');expect(await arcos(page)).toBe(2);await tecla(page,'Delete');await expect.poll(()=>arcos(page)).toBe(0);await guardado(page);const last=modelo(await leer(request,'e2e-10'));expect(last.modelo.enlaces).toEqual(first.modelo.enlaces);expect(Object.keys(last.modelo.abanicos as object)).toHaveLength(0);await seleccionarEnlace(page,'e1');await seleccionarEnlace(page,'e2',true);await tecla(page,'Shift+x');expect(await arcos(page)).toBe(2);await expect(opl(page)).toContainText('consume al menos uno de');await guardado(page);const or=modelo(await leer(request,'e2e-10'));const fid=Object.keys(or.modelo.abanicos as object)[0]!;const po=await puntoAbanico(page,fid);await page.mouse.click(po.x,po.y);await tecla(page,'Delete');await guardado(page);expect(modelo(await leer(request,'e2e-10')).modelo.enlaces).toEqual(last.modelo.enlaces);expect(await arcos(page)).toBe(0);await captura(page,'10-abanico');
});
async function puntoAbanico(page:Page,id:string){return page.getByLabel(/^Diagrama /).evaluate((root,id)=>{const x=Array.from(root.getElementsByTagName('*')).find(n=>n.getAttribute('data-ref')===`abanico:${id}`);const g=x instanceof SVGGeometryElement?x:x&&Array.from(x.getElementsByTagName('*')).find(n=>n instanceof SVGGeometryElement);if(!(g instanceof SVGGeometryElement))throw new Error('No existe arco de grupo');const t=g.getPointAtLength(g.getTotalLength()/2),p=new DOMPoint(t.x,t.y).matrixTransform(g.getScreenCTM()!);return{x:p.x,y:p.y};},id);}
async function cadena(page:Page){for(const [n,tecla]of [['A','Enter'],['B','Shift+Enter'],['C','Enter'],['D','Enter']]as const){const campo=page.getByRole('textbox',{name:'Nombre siguiente',exact:true});await campo.fill(n);await campo.press(tecla);}await page.getByRole('textbox',{name:'Nombre siguiente',exact:true}).press('Escape');}
test('T-075 11 descomponer0→n, CXM, distribución, escisión y undo único',async({page,request})=>{
 for(const tipo of ['descomponer','decompTs3']){
  const id=`e2e-11-${tipo}`;await sembrar(request,tipo,id);await abrir(page,id);const antes=await leer(request,id);await seleccionar(page,'Procesar');await tecla(page,'d');await expect(page.getByRole('textbox',{name:'Nombre siguiente',exact:true})).toBeVisible();await guardado(page);let v=modelo(await leer(request,id));const h=Object.values(v.modelo.opds).find(x=>x.padreId==='sd');expect(h).toBeTruthy();expect(h!.ordenInzoom).toEqual([]);await cadena(page);await guardado(page);v=modelo(await leer(request,id));const hijo=Object.values(v.modelo.opds).find(x=>x.padreId==='sd')!;const names=(hijo.ordenInzoom as string[][]).map(b=>b.map(x=>v.modelo.entidades[x]!.nombre));expect(names).toEqual([['A','B'],['C'],['D']]);await expect(opl(page)).toContainText(/A.*B.*C.*D/s);
  if(tipo==='descomponer')expect(v.modelo.enlaces.e1!.destinoId).toMatchObject({kind:'entidad',id:(hijo.ordenInzoom as string[][])[0]![0]});else{expect(Object.keys(v.modelo.enlaces)).toHaveLength(2);expect(Object.values(v.modelo.enlaces).every(e=>e.efectoEscindido)).toBe(true);}
  await navegar(page,/SD E2E/);await expect(opl(page)).toContainText(tipo==='descomponer'?'Procesar consume Pedido.':'Procesar');await tecla(page,'Control+z');await guardado(page);expect((await leer(request,id)).texto).toBe(antes.texto);await captura(page,`11-${tipo}`);await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();
 }
 await sembrar(request,'simple','e2e-11-cancel');await page.reload();await page.getByRole('button',{name:'E2E e2e-11-cancel',exact:true}).click();await cerrarInformes(page);await seleccionar(page,'Procesar');await tecla(page,'d');await page.getByRole('textbox',{name:'Nombre siguiente',exact:true}).press('Escape');await page.getByRole('tab',{name:/Diagnóstico/}).click();await expect(page.getByText(/refinamiento.*dos|al menos dos subprocesos/i)).toBeVisible();
});
test('T-269 12 bandas y rechazo de doble vara sin consumir ID',async({page,request})=>{
 await sembrar(request,'refinado','e2e-12');await abrir(page,'e2e-12');await navegar(page,/SD1 Procesar/);await seleccionar(page,'Preparar');const antesTexto=await opl(page).innerText();await tecla(page,']');await expect.poll(()=>opl(page).innerText()).not.toBe(antesTexto);await guardado(page);const desplazado=modelo(await leer(request,'e2e-12'));expect((desplazado.modelo.opds.h!.ordenInzoom as string[][])).toEqual([['r','q']]);await tecla(page,'Control+z');await guardado(page);const antes=await leer(request,'e2e-12');await seleccionar(page,'Preparar');await tecla(page,'r');await cosa(page,'Entregar').click();const d=page.getByRole('dialog',{name:/^Enlace:/});await d.getByText(/tipos no disponibles/).click();await expect(d.getByText(/R-INV-2B: La invocación duplica la transición a la banda siguiente/)).toBeVisible();await expect(d.getByRole('menuitem',{name:/invocacion · directo/})).toHaveCount(0);await d.getByRole('button',{name:'Cerrar diálogo'}).click();expect((await leer(request,'e2e-12')).texto).toBe(antes.texto);await captura(page,'12-bandas');
});
test('T-034 13 desplegar agregación, CX3/RF1 e incompleta',async({page,request})=>{
 await sembrar(request,'vacio','e2e-13');await abrir(page,'e2e-13');await crear(page,'objeto','Sistema');await seleccionar(page,'Sistema');await tecla(page,'u');await page.getByRole('dialog',{name:'Desplegar por modo'}).getByRole('button',{name:'1 agregacion'}).click();for(const n of ['Cuenta','Saldo']){const t=page.getByRole('textbox',{name:'Nombre siguiente',exact:true});await t.fill(n);await t.press('Enter');}await page.getByRole('textbox',{name:'Nombre siguiente',exact:true}).press('Escape');await guardado(page);await expect(opl(page)).toContainText('Sistema se despliega en SD1 en Cuenta y Saldo.');await expect(opl(page)).toContainText('Sistema consta de Cuenta.');await expect(opl(page)).toContainText('Sistema consta de Saldo.');const v=modelo(await leer(request,'e2e-13'));expect(Object.keys(v.modelo.opds)).toHaveLength(2);expect(Object.values(v.modelo.enlaces).map(x=>x.tipo)).toEqual(['agregacion','agregacion']);await seleccionarSimbolo(page);await tecla(page,'i');await expect(opl(page)).toContainText('y al menos otra parte');await guardado(page);expect(modelo(await leer(request,'e2e-13')).modelo.entidades[Object.keys(v.modelo.entidades)[0]!]!.coleccionIncompleta).toEqual(['agregacion']);await captura(page,'13-despliegue');
});
test('T-231 14 navegación árbol/ruta/Enter/Alt↑ y bbox encuadrado',async({page,request})=>{
 await sembrar(request,'refinado','e2e-14');await abrir(page,'e2e-14');const antes=await leer(request,'e2e-14');await seleccionar(page,'Procesar');await tecla(page,'Enter');await expect(page.getByRole('navigation',{name:'Ruta de OPD'})).toContainText('SD1');await expect(cosa(page,'Preparar')).toBeVisible();const b=await lienzo(page).boundingBox(),n=await cosa(page,'Preparar').boundingBox();expect(n!.x).toBeGreaterThanOrEqual(b!.x);expect(n!.x+n!.width).toBeLessThanOrEqual(b!.x+b!.width);const figuras=await svg(page).evaluate(root=>Array.from(root.getElementsByTagName('*')).filter(n=>n.hasAttribute('data-ref')&&n instanceof SVGGraphicsElement).map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,ancho:r.width,alto:r.height};}).filter(r=>r.ancho||r.alto));expect(figuras.length).toBeGreaterThan(3);for(const f of figuras){expect(f.x).toBeGreaterThanOrEqual(b!.x-2);expect(f.y).toBeGreaterThanOrEqual(b!.y-2);expect(f.x+f.ancho).toBeLessThanOrEqual(b!.x+b!.width+2);expect(f.y+f.alto).toBeLessThanOrEqual(b!.y+b!.height+2);}await tecla(page,'Alt+ArrowUp');await expect(page.getByRole('navigation',{name:'Ruta de OPD'})).not.toContainText('SD1');await tecla(page,'Control+Backslash');await page.getByRole('tree',{name:'Diagramas del modelo'}).getByRole('button',{name:/SD1 Procesar/}).click();await page.getByRole('navigation',{name:'Ruta de OPD'}).getByRole('button',{name:/^SD E2E/}).click();await expect(cosa(page,'Preparar')).toHaveCount(0);expect((await leer(request,'e2e-14')).rev).toBe(antes.rev);await captura(page,'14-navegacion');
});
test('T-251 15 quitar sólo aparición, Buscar Traer y eliminación refinada rechazada',async({page,request})=>{
 await sembrar(request,'simple','e2e-15a');await abrir(page,'e2e-15a');const antes=modelo(await leer(request,'e2e-15a'));await seleccionar(page,'Pedido');await tecla(page,'Delete');await expect(cosa(page,'Pedido')).toHaveCount(0);await guardado(page);let v=modelo(await leer(request,'e2e-15a'));expect(v.modelo.entidades).toEqual(antes.modelo.entidades);expect(Object.values(v.modelo.opds.sd!.apariencias).map(a=>a.entidadId)).not.toContain('o');await tecla(page,'Control+k');await page.getByRole('textbox',{name:'Nombre o diagrama'}).fill('Pedido');await page.getByRole('dialog',{name:'Buscar'}).getByRole('button',{name:'Traer',exact:true}).click();await expect(cosa(page,'Pedido')).toBeVisible();await guardado(page);v=modelo(await leer(request,'e2e-15a'));expect(v.modelo.entidades).toEqual(antes.modelo.entidades);expect(Object.values(v.modelo.opds.sd!.apariencias).map(a=>a.entidadId)).toContain('o');
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'refinado','e2e-15b');await page.reload();await page.getByRole('button',{name:'E2E e2e-15b',exact:true}).click();await cerrarInformes(page);const original=await leer(request,'e2e-15b');await seleccionar(page,'Procesar');await tecla(page,'Shift+Delete');await page.getByRole('dialog',{name:'Eliminar del modelo',exact:true}).getByRole('button',{name:'Eliminar definitivamente'}).click();await expect(page.getByRole('status').filter({hasText:/Elimina primero el refinamiento, de las hojas hacia arriba/})).toBeVisible();expect((await leer(request,'e2e-15b')).texto).toBe(original.texto);await page.getByRole('dialog',{name:'Eliminar del modelo',exact:true}).getByRole('button',{name:'Cerrar diálogo'}).click();await captura(page,'15-identidad');
});
test('T-170 16 editar OPL, parcial válido, inmediato, resalte y no-op',async({page,request})=>{
 await sembrar(request,'vacio','e2e-16');await abrir(page,'e2e-16');const area=await editarOpl(page);await area.fill('**Cliente** es físico.\nEsto no es una oración canónica.');await expect(page.getByRole('status').filter({hasText:/1 aplicables · 1 no aplicables/})).toBeVisible();await expect(page.getByText(/Línea 2:/)).toBeVisible();await page.getByRole('button',{name:'Aplicar 2 cambios',exact:true}).click();await page.getByRole('dialog',{name:'Editar OPL'}).getByRole('button',{name:'Cerrar diálogo'}).click();await expect(cosa(page,'Cliente')).toBeVisible();await expect(opl(page)).toContainText('Cliente es físico.');expect(await opl(page).getByRole('button',{name:'Cliente',exact:true}).evaluate(n=>n.parentElement!.getAttribute('class'))).toContain('linea-nueva');await guardado(page);const despues=await leer(request,'e2e-16');await editarOpl(page);await expect(page.getByRole('button',{name:'Sin cambios aplicables',exact:true})).toBeDisabled();await page.getByRole('textbox',{name:'Texto OPL'}).press('Escape');expect((await leer(request,'e2e-16')).rev).toBe(despues.rev);await captura(page,'16-opl');
});
test('T-242 17 hover bidireccional y clic en otro bloque sin mutar rev',async({page,request})=>{
 await sembrar(request,'refinado','e2e-17');await abrir(page,'e2e-17');const antes=await leer(request,'e2e-17');const token=opl(page).getByRole('button',{name:'Pedido',exact:true}).first();await token.hover();await expect.poll(()=>svg(page).evaluate(root=>Array.from(root.getElementsByTagName('*')).some(n=>n.getAttribute('data-ref')==='cosa:o'&&(()=>{let a:Element|null=n;while(a){if(a.getAttribute('data-capa-ui')==='1')return true;a=a.parentElement;}return false;})()))).toBe(true);await cosa(page,'Pedido').hover();await expect.poll(()=>token.evaluate(n=>n.parentElement!.getAttribute('class'))).toContain('linea-realzada');await opl(page).getByRole('button',{name:'Preparar',exact:true}).first().click();await expect(page.getByRole('navigation',{name:'Ruta de OPD'})).toContainText('SD1');await expect(page.getByRole('heading',{name:'Preparar',exact:true})).toBeVisible();expect((await leer(request,'e2e-17')).rev).toBe(antes.rev);await captura(page,'17-bimodal');
});
test('T-261 18 diagnóstico: warning Ir, reparaciones opt-in N2 y SVG limpio',async({page,request})=>{
 await sembrar(request,'warning','e2e-18a');await abrir(page,'e2e-18a');await page.getByRole('tab',{name:/Diagnóstico/}).click();const warn=page.getByRole('article').filter({hasText:/no consume, crea ni afecta/}).first();await expect(warn).toBeVisible();await warn.getByRole('button',{name:'Ir',exact:true}).click();await expect(page.getByRole('heading',{name:'Procesar',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'duplicados','e2e-18b');await page.reload();await page.getByRole('button',{name:'E2E e2e-18b',exact:true}).click();await cerrarInformes(page);await page.getByRole('tab',{name:/Diagnóstico/}).click();const cs=page.getByRole('checkbox',{name:'Incluir nombre-duplicado',exact:true});await expect(cs).toHaveCount(2);for(const c of await cs.all()){await expect(c).not.toBeChecked();await c.check();}const anterior=await leer(request,'e2e-18b');await page.getByRole('button',{name:'Aplicar a 2',exact:true}).click();await guardado(page);let v=modelo(await leer(request,'e2e-18b'));expect(new Set(Object.values(v.modelo.entidades).map(c=>c.nombre)).size).toBe(3);expect(Object.keys(v.modelo.entidades)).toEqual(Object.keys(modelo(anterior).modelo.entidades));await expect(cs).toHaveCount(0);const d=await exportar(page),texto=await descargar(page,d.getByRole('button',{name:'OPD SVG · canon-diagrama'}));expect(texto).not.toMatch(/data-ref|data-capa-ui|seleccion-ui|hover-ui/);await d.getByRole('button',{name:'Cerrar diálogo'}).click();await tecla(page,'Control+z');await guardado(page);expect((await leer(request,'e2e-18b')).texto).toBe(anterior.texto);await captura(page,'18-diagnostico');
});
test('T-280 19 SVG genuino, AP13, F9, JSON=GET y B26',async({page,request})=>{
 await sembrar(request,'simple','e2e-19a');await abrir(page,'e2e-19a');const d=await exportar(page),texto=await descargar(page,d.getByRole('button',{name:'OPD SVG · canon-diagrama'}));expect(texto).toContain('@font-face');expect(texto).not.toMatch(/data-ref|data-capa-ui|seleccion-ui/);await d.getByRole('button',{name:'Cerrar diálogo'}).click();await tecla(page,'F9');const comparacion=await svg(page).evaluate((root,t)=>{const actual=root.firstElementChild!.firstElementChild!,doc=new DOMParser().parseFromString(t,'image/svg+xml'),canon=Array.from(doc.documentElement.children).find(x=>x.tagName==='g')!;
 const estructura=(n:Node):unknown=>{if(n.nodeType!==Node.ELEMENT_NODE)return{tipo:n.nodeType,texto:n.nodeValue};const e=n as SVGElement,attrs=Array.from(e.attributes).map(a=>[a.namespaceURI,a.localName,a.name==='style'?(()=>{const css=document.createElement('span').style;css.cssText=a.value;return Array.from(css).sort().map(k=>[k,['letter-spacing','word-spacing'].includes(k)&&/^0(?:px)?$/.test(css.getPropertyValue(k))?'0':css.getPropertyValue(k),css.getPropertyPriority(k)]);})():a.value]).sort((a,b)=>String(a[1]).localeCompare(String(b[1])));return{namespace:e.namespaceURI,tipo:e.localName,attrs,hijos:Array.from(e.childNodes).map(estructura)};};const esperado=estructura(canon),obtenido=estructura(actual),negativos:unknown[]=[];const mutar=(f:(n:Element)=>void)=>{const n=canon.cloneNode(true) as Element;f(n);negativos.push(estructura(n));};mutar(n=>n.setAttribute('id','identidad-distinta'));mutar(n=>n.getElementsByTagName('text')[0]!.textContent='Otro nombre');mutar(n=>n.setAttribute('transform','translate(20 0)'));mutar(n=>n.getElementsByTagName('text')[0]!.setAttribute('style','font-kerning:auto;font-variant-ligatures:none;letter-spacing:0;word-spacing:0'));return{esperado,obtenido,negativos};},texto);expect(comparacion.obtenido).toEqual(comparacion.esperado);for(const negativo of comparacion.negativos)expect(comparacion.obtenido).not.toEqual(negativo);await tecla(page,'F9');await guardado(page);const jsonD=await exportar(page),json=await descargar(page,jsonD.getByRole('button',{name:'Modelo JSON',exact:true}));expect(json).toBe((await leer(request,'e2e-19a')).texto);const html=await descargar(page,jsonD.getByRole('button',{name:'Documento HTML · canon-documento'}));expect(html).toContain('canon-documento');expect(html).toContain('@font-face');expect(html).toContain('Pedido');const md=await descargar(page,jsonD.getByRole('button',{name:'Documento OPL',exact:true}));expect(md).toContain('**Pedido**');expect(md).toContain('*Procesar*');await jsonD.getByRole('button',{name:'Cerrar diálogo'}).click();await seleccionar(page,'Pedido');await tecla(page,'Delete');const bloqueado=await exportar(page);await expect(bloqueado.getByRole('button',{name:'Documento HTML · canon-documento'})).toBeDisabled();await expect(bloqueado.getByText('T-262, A8.2: «Pedido» no aparece en ningún OPD.',{exact:false})).toBeVisible();await expect(bloqueado.getByRole('button',{name:'OPD SVG · canon-diagrama'})).toBeEnabled();expect(modelo(await leer(request,'e2e-19a')).modelo.entidades.o!.nombre).toBe('Pedido');await bloqueado.getByRole('button',{name:'Cerrar diálogo'}).click();
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await expect(page.getByRole('heading',{name:'Biblioteca',exact:true})).toBeVisible();await sembrar(request,'ap13','e2e-19b');await abrir(page,'e2e-19b');await navegar(page,/SD1 Procesar/);const ap=await exportar(page);await expect(ap.getByRole('button',{name:'OPD SVG · canon-diagrama'})).toBeDisabled();const motivosAp=ap.getByText(/^AP-13, R-REF-NTRIV-1\/2:/);await expect(motivosAp).toHaveCount(2);for(const motivo of await motivosAp.all())await expect(motivo).toBeVisible();await captura(page,'19-gates');
});
test('T-011 20 OPL tres cambios, undo/redo de modelo y OPD',async({page,request})=>{
 await sembrar(request,'vacio','e2e-20');await abrir(page,'e2e-20');const antes=await leer(request,'e2e-20');await aplicarTexto(page,'**Cliente** es físico.\n**Factura** es informacional.\n*Cobrar* es físico.');await guardado(page);const hecho=await leer(request,'e2e-20');expect(Object.keys(modelo(hecho).modelo.entidades)).toHaveLength(3);await tecla(page,'Control+z');await guardado(page);expect((await leer(request,'e2e-20')).texto).toBe(antes.texto);expect(new URL(page.url()).hash).toMatch(/\/sd$/);await tecla(page,'Control+Shift+z');await guardado(page);expect((await leer(request,'e2e-20')).texto).toBe(hecho.texto);await captura(page,'20-undo');
});
async function renombrar(page:Page,nombre:string){await page.getByRole('button',{name:/✎/}).click();await page.getByRole('dialog',{name:'Renombrar modelo'}).getByRole('textbox',{name:'Nombre del modelo'}).fill(nombre);await page.getByRole('button',{name:'Guardar nombre',exact:true}).click();}
test('WP-17 DESIGN§8.4 21 guardado/CAS ambas resoluciones y borrador offline IDB',async({page,request,context})=>{
 for(const resolver of ['Conservar mis cambios','Usar la versión guardada']){const id=resolver==='Conservar mis cambios'?'e2e-21a':'e2e-21b';await sembrar(request,'simple',id);await abrir(page,id);const original=await leer(request,id),otro=modelo(original);otro.modelo.nombre='Guardada remota';await guardar(request,id,JSON.stringify(otro),original.rev);await renombrar(page,'Cambios locales');await tecla(page,'Control+s');await expect(page.getByRole('dialog',{name:'Hay cambios guardados en otra sesión'})).toBeVisible();await page.getByRole('button',{name:resolver,exact:true}).click();await cerrarInformes(page);await guardado(page);const d=modelo(await leer(request,id));expect(d.modelo.nombre).toBe(resolver==='Conservar mis cambios'?'Cambios locales':'Guardada remota');const papelera=await request.get('/api/papelera',{headers:{Authorization:`Bearer ${TOKEN}`}});expect(papelera.ok()).toBe(true);const entradas=await papelera.json() as {entradas:{id:string;motivo:string;nombre:string}[]};if(resolver==='Conservar mis cambios')expect(entradas.entradas).toEqual(expect.arrayContaining([expect.objectContaining({id,motivo:'reemplazado',nombre:'Guardada remota'})]));else{const ls=await request.get('/api/modelos',{headers:{Authorization:`Bearer ${TOKEN}`}});expect((await ls.json() as {modelos:{nombre:string}[]}).modelos.some(x=>/^Cambios locales \(copia /.test(x.nombre))).toBe(true);}await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();}
 await sembrar(request,'simple','e2e-21c');await page.reload();await page.getByRole('button',{name:'E2E e2e-21c',exact:true}).click();await cerrarInformes(page);await page.route('**/api/modelos/e2e-21c',r=>r.request().method()==='PUT'?r.abort():r.continue());await renombrar(page,'Borrador real');await tecla(page,'Control+s');await expect(page.getByRole('status').filter({hasText:/^Sin conexión$/})).toBeVisible();const b=await page.evaluate(async()=>{const r=indexedDB.open('opforja');const db=await new Promise<IDBDatabase>((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});try{const g=db.transaction('borradores').objectStore('borradores').get('e2e-21c');return await new Promise<unknown>((ok,no)=>{g.onsuccess=()=>ok(g.result);g.onerror=()=>no(g.error);});}finally{db.close();}});expect(b).toMatchObject({texto:expect.stringContaining('Borrador real')});await page.unroute('**/api/modelos/e2e-21c');page.on('dialog',d=>d.accept());await page.reload();await expect(page.getByRole('dialog',{name:'Recuperar cambios de este navegador'})).toBeVisible();await page.getByRole('button',{name:'Recuperar',exact:true}).click();await expect(page.getByRole('dialog',{name:'Recuperar cambios de este navegador'})).toBeHidden();await expect(page.getByRole('button',{name:'Borrador real ✎',exact:true})).toBeVisible();const put=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/api/modelos/e2e-21c')&&r.status()===200);await tecla(page,'Control+s');await put;await guardado(page);expect(modelo(await leer(request,'e2e-21c')).modelo.nombre).toBe('Borrador real');await captura(page,'21-borrador');
});
async function asaReanclaje(page:Page,enlace:string,extremo:'origen'|'destino'){return svg(page).evaluate((root,{enlace,extremo})=>{const n=Array.from(root.getElementsByTagName('*')).find(x=>x.getAttribute('data-ui')==='reanclar'&&x.getAttribute('data-enlace')===enlace&&x.getAttribute('data-extremo')===extremo);if(!n)throw new Error('Asa real ausente');const b=n.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};},{enlace,extremo});}
test('T-250 22 reanclar parte y consumo migrado: mismo ID/OPL/undo',async({page,request})=>{
 await sembrar(request,'estructural','e2e-22a');await abrir(page,'e2e-22a');await crear(page,'objeto','Registro',500,120);await seleccionarSimbolo(page);const a=await asaReanclaje(page,'e1','destino'),b=await cosa(page,'Registro').boundingBox();await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2,{steps:8});await page.mouse.up();await expect(opl(page)).toContainText(/Sistema consta de.*Registro/);await guardado(page);expect(modelo(await leer(request,'e2e-22a')).modelo.enlaces.e1!.destinoId).toMatchObject({kind:'entidad',id:expect.any(String)});expect(modelo(await leer(request,'e2e-22a')).modelo.enlaces.e1!.destinoId).not.toEqual({kind:'entidad',id:'a'});
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'refinado','e2e-22b');await page.reload();await page.getByRole('button',{name:'E2E e2e-22b',exact:true}).click();await cerrarInformes(page);await navegar(page,/SD1 Procesar/);await seleccionarEnlace(page,'e1');const antes=await leer(request,'e2e-22b'),start=await asaReanclaje(page,'e1','destino'),dest=await cosa(page,'Entregar').boundingBox();await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(dest!.x+dest!.width/2,dest!.y+dest!.height/2,{steps:8});await page.mouse.up();await expect(page.getByRole('status').filter({hasText:/R-ROL-UNIC-1/})).toBeVisible();expect((await leer(request,'e2e-22b')).texto).toBe(antes.texto);await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'reanclaje','e2e-22c');await abrir(page,'e2e-22c');await navegar(page,/SD1 Procesar/);await seleccionarEnlace(page,'e1');const original=await leer(request,'e2e-22c'),asa=await asaReanclaje(page,'e1','destino'),legal=await cosa(page,'Verificar').boundingBox();await page.mouse.move(asa.x,asa.y);await page.mouse.down();await page.mouse.move(legal!.x+legal!.width/2,legal!.y+legal!.height/2,{steps:8});await page.mouse.up();await guardado(page);expect(modelo(await leer(request,'e2e-22c')).modelo.enlaces.e1).toMatchObject({id:'e1',tipo:'consumo',destinoId:{kind:'entidad',id:'t'}});await expect(opl(page)).toContainText('Verificar consume Pedido.');await tecla(page,'Control+z');await guardado(page);expect((await leer(request,'e2e-22c')).texto).toBe(original.texto);await captura(page,'22-reanclar');
});
test('T-268 23 duración5min y excepción, manejador ambiental y aviso sistémico',async({page,request})=>{
 await sembrar(request,'excepcion','e2e-23');await abrir(page,'e2e-23');await seleccionar(page,'Procesar');await expect(page.getByRole('spinbutton',{name:'Máxima'})).toHaveValue('5');await expect(page.getByRole('combobox',{name:'Unidad',exact:true})).toHaveValue('min');await seleccionar(page,'Procesar');await tecla(page,'r');await cosa(page,'Gestionar Error').click();await page.getByRole('menuitem',{name:/excepcionSobretiempo · directo/}).click();await expect(opl(page)).toContainText('excede 5 minutos');await seleccionar(page,'Procesar');await tecla(page,'r');await cosa(page,'Resolver Error').click();await page.getByRole('menuitem',{name:/excepcionSobretiempo · directo/}).click();await page.getByRole('tab',{name:/Diagnóstico/}).click();await expect(page.getByRole('article').filter({hasText:/R-EXC-1A/}).getByText(/^R-EXC-1A El manejador/)).toBeVisible();await guardado(page);const es=Object.values(modelo(await leer(request,'e2e-23')).modelo.enlaces);expect(es.filter(e=>e.tipo==='excepcionSobretiempo')).toHaveLength(2);expect(es.every(e=>e.tiempoMaximo==='5'&&e.unidadTiempoMaximo==='min')).toBe(true);await captura(page,'23-duracion');
});
test('T-252 24 narrow390, zonas sin scroll y creación mundial real',async({page,request})=>{
 await page.setViewportSize({width:390,height:844});await sembrar(request,'vacio','e2e-24');await abrir(page,'e2e-24');const nav=page.getByRole('navigation',{name:'Zonas del editor'});await expect(nav).toBeVisible();for(const z of ['Propiedades','OPL','Diagnóstico','Lienzo']){const n=nav.getByRole('button',{name:z==='Diagnóstico'?/^Diagnóstico \d+$/:z,exact:true});await expect(n).toBeVisible();await n.click();await expect(n).toHaveAttribute('aria-pressed','true');if(z==='Propiedades')await expect(page.getByRole('heading',{name:'Propiedades',exact:true})).toBeVisible();if(z==='OPL')await expect(opl(page)).toBeVisible();if(z==='Diagnóstico')await expect(page.getByRole('heading',{name:/Diagnóstico/})).toBeVisible();if(z==='Lienzo')await expect(lienzo(page)).toBeVisible();}await nav.getByRole('button',{name:'Lienzo',exact:true}).click();await crear(page,'objeto','Cliente',150,190);await guardado(page);const v=modelo(await leer(request,'e2e-24'));expect(Object.values(v.modelo.entidades).map(c=>c.nombre)).toEqual(['Cliente']);const caja=await cosa(page,'Cliente').boundingBox(),area=await lienzo(page).boundingBox();expect(caja!.x+caja!.width).toBeLessThanOrEqual(area!.x+area!.width+1);expect(caja!.y).toBeGreaterThanOrEqual(area!.y);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await captura(page,'24-narrow');
});
test('T-251 25 multiselección mover3, undo, Decisión y Enlaces N navega',async({page,request})=>{
 await sembrar(request,'basico','e2e-25a');await abrir(page,'e2e-25a');const antes=await leer(request,'e2e-25a');await seleccionar(page,'Pedido');await cosa(page,'Factura').click({modifiers:['Shift']});await cosa(page,'Entregar').click({modifiers:['Shift']});await expect(page.getByText('3 elementos seleccionados.',{exact:true})).toBeVisible();const b=await cosa(page,'Pedido').boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2+50,b!.y+b!.height/2+30,{steps:8});await page.mouse.up();await guardado(page);const v=modelo(await leer(request,'e2e-25a')),prev=modelo(antes);for(const id of ['o','a','q']){const x=Object.values(v.modelo.opds.sd!.apariencias).find(x=>x.entidadId===id)!,y=Object.values(prev.modelo.opds.sd!.apariencias).find(x=>x.entidadId===id)!;expect(x.x).not.toBe(y.x);expect(x.y).not.toBe(y.y);}await tecla(page,'Control+z');await guardado(page);expect((await leer(request,'e2e-25a')).texto).toBe(antes.texto);await tecla(page,'Delete');await expect(page.getByRole('dialog',{name:/Confirmar/})).toBeVisible();await captura(page,'25-decision');await page.getByRole('dialog',{name:/Confirmar/}).getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.getByRole('dialog',{name:'Confirmar quitar de este OPD'})).toBeHidden();await expect(lienzo(page).getByRole('button',{name:'Seleccionar',exact:true})).toBeEnabled();expect((await leer(request,'e2e-25a')).texto).toBe(antes.texto);await tecla(page,'Delete');await page.getByRole('dialog',{name:'Confirmar quitar de este OPD'}).getByRole('button',{name:'Quitar apariciones'}).click();await guardado(page);const quitado=modelo(await leer(request,'e2e-25a'));expect(quitado.modelo.entidades).toEqual(prev.modelo.entidades);expect(quitado.modelo.enlaces).toEqual(prev.modelo.enlaces);expect(quitado.modelo.nextSeq).toBe(prev.modelo.nextSeq);for(const id of ['o','a','q'])expect(Object.values(quitado.modelo.opds.sd!.apariencias).some(x=>x.entidadId===id)).toBe(false);await tecla(page,'Control+z');await guardado(page);expect((await leer(request,'e2e-25a')).texto).toBe(antes.texto);
 await page.getByRole('button',{name:'Volver a la Biblioteca'}).click();await sembrar(request,'refinado','e2e-25b');await page.reload();await page.getByRole('button',{name:'E2E e2e-25b',exact:true}).click();await cerrarInformes(page);await seleccionar(page,'Pedido');await expect(page.getByText('Enlaces (2)',{exact:true})).toBeVisible();const boton=page.getByRole('complementary',{name:'Propiedades y OPL'}).getByRole('button',{name:/Preparar/}).first();await boton.click();await expect(page.getByRole('heading',{name:/consumo/})).toBeVisible();await captura(page,'25-multiple');
});
test('T-010 26 System_Diagram: auto-no-op cadaOPD y revisión original tras undo',async({page,request})=>{
 await abrir(page,'e2e-archivo-System_Diagram');const id='e2e-archivo-System_Diagram',original=await leer(request,id),v=modelo(original);for(const opd of Object.keys(v.modelo.opds)){
  if(new URL(page.url()).hash.split('/')[3]!==opd){await page.getByRole('button',{name:'Elegir OPD'}).click();await page.getByRole('dialog',{name:'Diagramas del modelo'}).getByRole('button',{name:new RegExp(`\\b${String(v.modelo.opds[opd]!.nombre)}\\b`)}).click();}
  const t=await editarOpl(page),canon=await t.inputValue();await expect(page.getByRole('button',{name:'Sin cambios aplicables',exact:true})).toBeDisabled();await t.fill(`${canon}\n**Cliente E2E** es físico.`);await expect(page.getByRole('button',{name:'Aplicar 2 cambios',exact:true})).toBeEnabled();await t.press('Control+Enter');await expect(page.getByRole('button',{name:'Sin cambios aplicables',exact:true})).toBeDisabled();await t.press('Escape');await guardado(page);expect(Object.values(modelo(await leer(request,id)).modelo.entidades).some(c=>c.nombre==='Cliente E2E')).toBe(true);await tecla(page,'Control+z');await guardado(page);const despues=await leer(request,id);expect(despues.rev).toBe(original.rev);expect(despues.texto).toBe(original.texto);
 }await captura(page,'26-system-idempotente');
});

async function arrastrarAEstado(page:Page,ref:string,id:string){const [origen,destino]=await svg(page).evaluate((root,{ref,id})=>{const all=Array.from(root.getElementsByTagName('*'));const asa=all.find(n=>n.getAttribute('data-ui')==='conectar'&&n.getAttribute('data-ref')===ref) as SVGGraphicsElement|undefined;const grupo=all.find(n=>n.getAttribute('data-ref')===`estado:${id}`);const rect=grupo?.getElementsByTagName('rect')[0];if(!asa||!rect)throw new Error('Asa/cápsula reales ausentes');const a=asa.getBBox(),b=rect.getBBox(),o=new DOMPoint(a.x+a.width/2,a.y+a.height/2).matrixTransform(asa.getScreenCTM()!),pts=[.25,.5,.75].flatMap(y=>[.2,.4,.6,.8].map(x=>new DOMPoint(b.x+b.width*x,b.y+b.height*y).matrixTransform(rect.getScreenCTM()!))),d=pts.find(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-ref]')?.getAttribute('data-ref')===`estado:${id}`);if(!d)throw new Error(`La cápsula ${id} no tiene un punto de tinta alcanzable`);return[{x:o.x,y:o.y},{x:d.x,y:d.y}];},{ref,id});await page.mouse.move(origen!.x,origen!.y);await page.mouse.down();await page.mouse.move(destino!.x,destino!.y,{steps:8});const hit=await page.evaluate(p=>{const n=document.elementFromPoint(p.x,p.y);return{ref:n?.closest('[data-ref]')?.getAttribute('data-ref'),tag:n?.tagName,refs:document.elementsFromPoint(p.x,p.y).map(n=>n.closest('[data-ref]')?.getAttribute('data-ref'))};},destino!);expect(hit,`Hit de la cápsula antes de mouseup: ${JSON.stringify(hit)}`).toMatchObject({ref:`estado:${id}`});await page.mouse.up();}

async function accionGuardada(page:Page,id:string,key:string){const put=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith(`/api/modelos/${id}`)&&r.status()===200);await tecla(page,key);await put;await guardado(page);}

async function seleccionarEstadoAlcanzable(page:Page,id:string){
 const punto=await svg(page).evaluate((root,id)=>{const g=Array.from(root.getElementsByTagName('*')).find(n=>n.getAttribute('data-ref')===`estado:${id}`),rect=g?.getElementsByTagName('rect')[0];if(!rect)throw Error('Cápsula real ausente');const b=rect.getBBox(),rx=Math.min(Number(rect.getAttribute('rx')??0),b.width/2,b.height/2),m=rect.getScreenCTM()!;const pts=[.1,.25,.5,.75,.9].flatMap(y=>[.2,.4,.6,.8].map(x=>({x:b.x+b.width*x,y:b.y+b.height*y}))).filter(p=>{const dx=Math.max(0,Math.abs(p.x-(b.x+b.width/2))-(b.width/2-rx)),dy=Math.max(0,Math.abs(p.y-(b.y+b.height/2))-(b.height/2-rx));return dx*dx+dy*dy<=rx*rx;}).map(p=>new DOMPoint(p.x,p.y).matrixTransform(m));const p=pts.find(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-ref]')?.getAttribute('data-ref')===`estado:${id}`);if(!p)throw Error('Cápsula sin punto alcanzable');return{x:p.x,y:p.y};},id);
 await page.mouse.move(punto.x,punto.y);const hit=()=>page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-ref]')?.getAttribute('data-ref'),punto);expect(await hit()).toBe(`estado:${id}`);await page.mouse.down();expect(await hit()).toBe(`estado:${id}`);await page.mouse.up();
}
