import { test as base, expect, chromium } from '@playwright/test';
import type { Page, BrowserContext, Locator, APIRequestContext } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import {BASE} from './configuracion';
export {BASE};
export const TOKEN='token-sintetico-e2e-exclusivo-1234567890-1234567890',EMAIL='e2e@opforja.invalid',PASSWORD='clave-sintetica-exclusiva-e2e';
export interface V0 {formato:string;modelo:{id:string;nombre:string;nextSeq:number;opdRaizId:string;entidades:Record<string,Record<string,unknown>>;estados:Record<string,Record<string,unknown>>;enlaces:Record<string,Record<string,unknown>>;opds:Record<string,{padreId:string|null;apariencias:Record<string,{entidadId:string;x:number;y:number;width:number;height:number}>;[k:string]:unknown}>;[k:string]:unknown}}
export interface Documento {texto:string;rev:string;id:string}
const cabeceras={Authorization:`Bearer ${TOKEN}`,'Content-Type':'application/json'};
export const test=base.extend<{errores:void;extraContexto:()=>Promise<BrowserContext>}>({
 browser: [async({},use)=>{const b=await chromium.launch({executablePath:process.env.PW_CHROMIUM??'/home/felix/.cache/ms-playwright/chromium-1217/chrome-linux64/chrome'});try{await use(b);}finally{await b.close();}}, {scope:'worker'}],
 errores:[async({context,page},use,testInfo)=>{const errores:string[]=[],externos:string[]=[];const paginas=new WeakSet<Page>();const escuchar=(p:Page)=>{if(paginas.has(p))return;paginas.add(p);p.on('pageerror',e=>errores.push(e.message));};context.on('page',escuchar);context.pages().forEach(escuchar);escuchar(page);await context.route('**/*',async r=>{const u=r.request().url();if(/^https?:/.test(u)&&new URL(u).origin!==BASE){externos.push(u);await r.abort();}else await r.continue();});try{await use();}finally{await testInfo.attach('errores-de-pagina',{body:JSON.stringify({errores,externos}),contentType:'application/json'});expect.soft(errores,'Errores de página, incluso tras otra falla').toEqual([]);expect.soft(externos,'Solicitudes externas').toEqual([]);}}, {auto:true}],
 extraContexto:async({browser},use)=>{const cs:BrowserContext[]=[];const errores:string[]=[],externos:string[]=[];try{await use(async()=>{const c=await browser.newContext({baseURL:BASE});c.on('page',p=>p.on('pageerror',e=>errores.push(e.message)));await c.route('**/*',async r=>{const u=r.request().url();if(/^https?:/.test(u)&&new URL(u).origin!==BASE){externos.push(u);await r.abort();}else await r.continue();});cs.push(c);return c;});}finally{for(const c of cs)await c.close();expect.soft(errores).toEqual([]);expect.soft(externos).toEqual([]);}},
});
export {expect};
export async function entrar(page:Page){await page.goto('/');await expect.poll(()=>page.evaluate(()=>document.body.dataset.listo)).toBe('1');await expect(page.getByRole('heading',{name:/^(Entrar|Biblioteca)$/})).toBeVisible();if(await page.getByRole('heading',{name:'Biblioteca',exact:true}).isVisible())return;await page.getByLabel('Correo',{exact:true}).fill(EMAIL);await page.getByLabel('Clave',{exact:true}).fill(PASSWORD);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page.getByRole('heading',{name:'Biblioteca',exact:true})).toBeVisible();}
export async function leer(api:APIRequestContext,id:string):Promise<Documento>{const r=await api.get(`/api/modelos/${id}`,{headers:cabeceras});expect(r.status()).toBe(200);const texto=await r.text();return {texto,rev:r.headers()['etag']!,id};}
export async function guardar(api:APIRequestContext,id:string,texto:string,rev:string){const r=await api.put(`/api/modelos/${id}`,{headers:{...cabeceras,'If-Match':rev},data:texto});expect(r.status()).toBe(200);return r;}
export function modelo(d:Documento):V0{return JSON.parse(d.texto) as V0;}
export async function sembrar(api:APIRequestContext,tipo:string,id:string):Promise<Documento>{const fixtures=JSON.parse(readFileSync(resolve('e2e/modelos.json'),'utf8')) as Record<string,V0>;const doc=structuredClone(fixtures[tipo]!);expect(doc).toBeTruthy();doc.modelo.id=id;doc.modelo.nombre=`E2E ${id}`;const r=await api.post('/api/modelos',{headers:cabeceras,data:doc});expect(r.status(),await r.text()).toBe(201);return leer(api,id);}
export async function abrir(page:Page,id:string){await entrar(page);const r=await page.request.get(`/api/modelos/${id}`,{headers:cabeceras});expect(r.ok()).toBeTruthy();const d=JSON.parse(await r.text()) as V0;const opciones=page.getByRole('button',{name:d.modelo.nombre,exact:true});if(await opciones.count()===1)await opciones.click();else await page.goto(`/#/m/${encodeURIComponent(id)}/${encodeURIComponent(d.modelo.opdRaizId)}`);await expect(lienzo(page)).toBeVisible();await cerrarInformes(page);await guardado(page);}
export function lienzo(page:Page){return page.getByRole('region',{name:'Edición del diagrama',exact:true});}
export async function cerrarInformes(page:Page){for(const titulo of ['Informe de importación','Informe del servidor']){const dialog=page.getByRole('dialog',{name:titulo,exact:true});if(await dialog.count()){await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Cerrar diálogo'})).toBeEnabled();await dialog.getByRole('button',{name:'Cerrar diálogo'}).click();}}}
export async function guardado(page:Page){await expect(page.getByRole('status').filter({hasText:/^Guardado$/})).toBeVisible();}
export function cosa(page:Page,nombre:string){return page.getByRole('img',{name:new RegExp(`^(Objeto|Proceso) ${nombre.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')},`)});}
export async function seleccionar(page:Page,nombre:string){await cosa(page,nombre).click();}
export async function tecla(page:Page,key:string){await lienzo(page).focus();await page.keyboard.press(key);}
export async function crear(page:Page,tipo:'objeto'|'proceso',nombre:string,x=160,y=180){const b=await lienzo(page).boundingBox();expect(b).not.toBeNull();await page.mouse.move(b!.x+x,b!.y+y);await tecla(page,tipo==='objeto'?'o':'p');const campo=page.getByRole('textbox',{name:`Nombre del ${tipo}`,exact:true});await campo.fill(nombre);await campo.press('Enter');await expect(cosa(page,nombre)).toBeVisible();}
export async function arrastrar(page:Page,a:Locator,b:Locator){const x=await a.boundingBox(),y=await b.boundingBox();expect(x).not.toBeNull();expect(y).not.toBeNull();await page.mouse.move(x!.x+x!.width/2,x!.y+x!.height/2);await page.mouse.down();await page.mouse.move(y!.x+y!.width/2,y!.y+y!.height/2,{steps:8});await page.mouse.up();}
export async function conectar(page:Page,desde:string,hacia:string,opcion:RegExp){await seleccionar(page,desde);await tecla(page,'r');await cosa(page,hacia).click();await expect(page.getByRole('dialog',{name:/^Enlace:/})).toBeVisible();await page.getByRole('menuitem',{name:opcion}).click();await expect(page.getByRole('dialog',{name:/^Enlace:/})).toBeHidden();}
export function opl(page:Page){return page.getByRole('complementary',{name:'Propiedades y OPL'});}
export async function editarOpl(page:Page){await opl(page).getByRole('button',{name:'Editar',exact:true}).click();await expect(page.getByRole('dialog',{name:'Editar OPL'})).toBeVisible();return page.getByRole('textbox',{name:'Texto OPL',exact:true});}
export async function aplicarTexto(page:Page,texto:string){const area=await editarOpl(page);await area.fill(texto);await expect(page.getByRole('button',{name:/^Aplicar \d+ cambio/})).toBeEnabled();await page.getByRole('button',{name:/^Aplicar \d+ cambio/}).click();await page.getByRole('dialog',{name:'Editar OPL'}).getByRole('button',{name:'Cerrar diálogo'}).click();}
export async function descargar(page:Page,boton:Locator){const p=page.waitForEvent('download');await boton.click();const d=await p,stream=await d.createReadStream();expect(stream).not.toBeNull();const xs:Buffer[]=[];for await(const x of stream!)xs.push(Buffer.from(x));return Buffer.concat(xs).toString('utf8');}
export async function captura(page:Page,nombre:string){const dir=process.env.OPFORJA_E2E_CAPTURAS??resolve('/tmp/opforja-rehacer/reanudacion-decisiones29/wp17/capturas');mkdirSync(dir,{recursive:true});await page.screenshot({path:resolve(dir,`${nombre}.png`),fullPage:true});}
/** Coordenada de tinta del recorrido real; no centro del bbox de un arco. */
export async function puntoRef(page:Page,ref:string,fraccion=.5){return page.getByLabel(/^Diagrama /).evaluate((root,{ref,fraccion})=>{const all=Array.from(root.getElementsByTagName('*'));const g=all.find(n=>n.getAttribute('data-ref')===ref);if(!g)throw new Error(`No está ${ref}`);const recorrido=g instanceof SVGGeometryElement?g:Array.from(g.getElementsByTagName('*')).find(x=>x instanceof SVGGeometryElement);if(!(recorrido instanceof SVGGeometryElement))throw new Error(`Sin recorrido ${ref}`);const matrix=recorrido.getScreenCTM();if(!matrix)throw new Error('Sin transformación visible');const puntos=[fraccion,.2,.8,.1,.9,.3,.7,.4,.6].map(f=>{const pt=recorrido.getPointAtLength(recorrido.getTotalLength()*f);return new DOMPoint(pt.x,pt.y).matrixTransform(matrix);});const p=puntos.find(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-ref]')?.getAttribute('data-ref')===ref);if(!p)throw new Error(`Sin tinta alcanzable ${ref}`);return {x:p.x,y:p.y};},{ref,fraccion});}
export async function seleccionarEnlace(page:Page,id:string,shift=false){const pt=await puntoRef(page,`enlace:${id}`);if(shift)await page.keyboard.down('Shift');try{await page.mouse.click(pt.x,pt.y);}finally{if(shift)await page.keyboard.up('Shift');}}
export async function seleccionarSimbolo(page:Page){const p=await page.getByLabel(/^Diagrama /).evaluate(root=>{const g=Array.from(root.getElementsByTagName('*')).find(n=>n.getAttribute('data-ref')?.startsWith('simbolo:'));if(!g)throw new Error('No existe símbolo compuesto');const x=Array.from(g.getElementsByTagName('*')).find(n=>n instanceof SVGGeometryElement);if(!(x instanceof SVGGeometryElement))throw new Error('Sin figura');const pt=x.getPointAtLength(x.getTotalLength()*.5),m=x.getScreenCTM()!,p=new DOMPoint(pt.x,pt.y).matrixTransform(m);return {x:p.x,y:p.y};});await page.mouse.click(p.x,p.y);}
export async function arcos(page:Page){return page.getByLabel(/^Diagrama /).evaluate(root=>Array.from(root.getElementsByTagName('*')).filter(x=>x.getAttribute('data-ref')?.startsWith('abanico:')).reduce((n,g)=>n+g.getElementsByTagName('path').length,0));}
export async function navegar(page:Page,nombre:RegExp){await page.getByRole('button',{name:'Elegir OPD'}).click();const d=page.getByRole('dialog',{name:'Diagramas del modelo'});await d.getByRole('button',{name:nombre}).click();await expect(d).toBeHidden();}

export async function arrastrarConexion(page:Page,ref:string,destino:Locator){const p=await page.getByLabel(/^Diagrama /).evaluate((root,ref)=>{const x=Array.from(root.getElementsByTagName('*')).find(n=>n.getAttribute('data-ui')==='conectar'&&n.getAttribute('data-ref')===ref);if(!(x instanceof SVGGeometryElement))throw new Error(`Sin asa real ${ref}`);const b=x.getBBox(),p=new DOMPoint(b.x+b.width/2,b.y+b.height/2).matrixTransform(x.getScreenCTM()!);return{x:p.x,y:p.y};},ref),d=await destino.boundingBox();expect(d).not.toBeNull();await page.mouse.move(p.x,p.y);const hit=await page.evaluate(p=>{const n=document.elementFromPoint(p.x,p.y);return{ui:n?.closest('[data-ui]')?.getAttribute('data-ui'),ref:n?.closest('[data-ref]')?.getAttribute('data-ref'),tag:n?.tagName,elementos:document.elementsFromPoint(p.x,p.y).map(n=>({ui:n.closest('[data-ui]')?.getAttribute('data-ui'),ref:n.closest('[data-ref]')?.getAttribute('data-ref'),tag:n.tagName}))};},p);expect(hit,`Punto inicial ${JSON.stringify({p,hit})}`).toMatchObject({ui:'conectar',ref});await page.mouse.down();await page.mouse.move(d!.x+d!.width/2,d!.y+d!.height/2,{steps:8});await page.mouse.up();}
