import type { AccionContextualId } from "../store/acciones-contextuales";
import type {
  CapabilityDescriptor,
  CapabilityEffect,
  CapabilityEffectStep,
  CapabilityId,
  TutorCutCoverage,
  TutorEntrypoint,
  TutorEntrypointId,
} from "./tipos";

const OPERATIONAL_EXEMPT = "operational-exempt" as const;
type EntrypointOwner = CapabilityId | typeof OPERATIONAL_EXEMPT;

const CONTEXTUAL_ACTION_OWNERS = {
  "cambiar-tipo-enlace": "cap.link.procedural",
  "agregar-estado": "cap.state.lifecycle",
  inzoom: "cap.refinement.advanced",
  unfold: "cap.refinement.advanced",
  "quitar-descomposicion": "cap.refinement.advanced",
  "quitar-despliegue": "cap.refinement.advanced",
  "editar-alias": "cap.entity.properties",
  "editar-imagen": "cap.entity.properties",
  "marcar-requisito": "cap.requirement.coverage",
  "satisfacer-requisito": "cap.requirement.coverage",
  "conectar-submodelo": "cap.submodel.reference",
  "componer-modelo": "cap.composition.interface",
  "eliminar-seleccion": "cap.entity.kind",
  "agregar-como-partes": "cap.link.structural",
  "alinear-seleccion": "cap.appearance.view",
  "distribuir-seleccion": "cap.appearance.view",
  "mas-opciones": OPERATIONAL_EXEMPT,
  "traer-conectados": "cap.appearance.view",
  "traer-conectados-default": "cap.appearance.view",
  "traer-enlaces": "cap.appearance.view",
  "razonar-afectan-a": "cap.navigation.reasoning",
  "razonar-requerido-por": "cap.navigation.reasoning",
  "razonar-impacto-eliminar": "cap.navigation.reasoning",
  "razonar-impacto-aguas-abajo": "cap.navigation.reasoning",
  "verificar-coherencia-descomposicion": "cap.refinement.advanced",
  "ocultar-apariencia": "cap.appearance.view",
} satisfies Record<AccionContextualId, EntrypointOwner>;

interface EntrypointDefinition {
  entrypointId: TutorEntrypointId;
  owner: EntrypointOwner;
  reason?: string;
}

const entrypointDefinitions: readonly EntrypointDefinition[] = [
  ...Object.entries(CONTEXTUAL_ACTION_OWNERS).map(([actionId, owner]) => ({
    entrypointId: `contextual:${actionId}` as TutorEntrypointId,
    owner,
    ...(owner === OPERATIONAL_EXEMPT
      ? { reason: "Abre o cierra una superficie existente; no toma una decisión de modelado." }
      : {}),
  })),
  semantic("palette:nuevo-modelo", "cap.start.workspace"),
  semantic("palette:abrir-importar", "cap.persistence.import-save"),
  semantic("palette:guardar-como", "cap.persistence.import-save"),
  semantic("palette:abrir-pestana", "cap.start.workspace"),
  exempt("palette:configuracion", "Abre preferencias visuales; no persiste ni transforma hechos OPM."),
  semantic("palette:configurar-ontologia", "cap.ontology.lexical"),
  semantic("ontology:save", "cap.ontology.lexical"),
  semantic("palette:versiones-modelo", "cap.history.review-version"),
  semantic("palette:crear-requisito", "cap.requirement.coverage"),
  semantic("palette:marcar-requisito", "cap.requirement.coverage"),
  semantic("palette:satisfacer-requisito", "cap.requirement.coverage"),
  semantic("requirement:create", "cap.requirement.coverage"),
  semantic("requirement:mark", "cap.requirement.coverage"),
  semantic("requirement:satisfy", "cap.requirement.coverage"),
  semantic("palette:conectar-submodelo", "cap.submodel.reference"),
  semantic("palette:vitrina-estereotipos", "cap.reuse.pieces"),
  semantic("palette:split-parcial", "cap.link.procedural"),
  semantic("palette:recolectar-contorno", "cap.refinement.advanced"),
  semantic("palette:distribuir-contorno", "cap.refinement.advanced"),
  semantic("palette:resolver-decision", "cap.flow.control"),
  semantic("palette:buscar-modelo", "cap.navigation.reasoning"),
  semantic("palette:buscar-workspace", "cap.navigation.reasoning"),
  semantic("palette:exportar-json", "cap.export.interchange"),
  semantic("palette:exportar-diagnostico", "cap.diagnostic.reactive"),
  semantic("palette:exportar-opl-modelo", "cap.export.interchange"),
  semantic("palette:exportar-canon-documento", "cap.export.interchange"),
  semantic("palette:copiar-contexto-skill", "cap.handoff.skill"),
  semantic("palette:copiar-log-decisiones", "cap.handoff.skill"),
  exempt("palette:auth-cerrar-sesion", "Gestiona la sesión, no el modelo."),
  semantic("palette:exportar-opd-png", "cap.export.interchange"),
  semantic("palette:exportar-opds-png-zip", "cap.export.interchange"),
  semantic("palette:simulacion-conceptual", "cap.simulation.conceptual"),
  semantic("palette:simulacion-numerica", "cap.simulation.numeric"),
  exempt("palette:grid-canvas", "Configura la cuadrícula visual sin alterar hechos OPM."),
  exempt("palette:solo-canvas", "Configura chrome y paneles sin alterar hechos OPM."),
  semantic("palette:alias-visibles", "cap.appearance.view"),
  semantic("palette:descripciones-visibles", "cap.appearance.view"),
  semantic("palette:modo-imagen-global", "cap.appearance.view"),
  semantic("palette:editar-imagen-objeto", "cap.entity.properties"),
  semantic("palette:auto-layout", "cap.appearance.view"),
  semantic("palette:tabla-enlaces", "cap.navigation.reasoning"),
  semantic("palette:urls-objeto", "cap.entity.properties"),
  semantic("palette:mostrar-archivados", "cap.history.review-version"),
  semantic("palette:mostrar-versiones", "cap.history.review-version"),
  exempt("palette:capturar-bug", "Abre el capturador operativo de bugs."),
  exempt("palette:bug-ledger", "Abre el ledger operativo de bugs y features."),
  exempt("palette:atajos-teclado", "Abre la referencia operativa de teclado."),
  semantic("empty-state:choose-entry", "cap.purpose.sd-frontier"),
  semantic("canvas:create-object-process", "cap.entity.kind"),
  semantic("inspector:entity-identity", "cap.entity.kind"),
  semantic("inspector:entity-properties", "cap.entity.properties"),
  semantic("inspector:ficha-pregunta-habilitante", "cap.ficha.local"),
  semantic("inspector:ficha-dueno-significado", "cap.ficha.local"),
  semantic("inspector:ficha-responsable-decision", "cap.ficha.local"),
  semantic("inspector:ficha-tipos-modelo", "cap.ficha.local"),
  semantic("inspector:ficha-criterio-suficiencia", "cap.ficha.local"),
  semantic("inspector:ficha-vida-util", "cap.ficha.local"),
  semantic("inspector:ficha-revisar-cuando", "cap.ficha.local"),
  semantic("inspector:ficha-lentes-conocimiento", "cap.ficha.local"),
  semantic("inspector:state-lifecycle", "cap.state.lifecycle"),
  semantic("inspector:link-procedural", "cap.link.procedural"),
  semantic("inspector:link-structural", "cap.link.structural"),
  semantic("inspector:flow-control", "cap.flow.control"),
  semantic("inspector:appearance", "cap.appearance.view"),
  semantic("inspector:refinement", "cap.refinement.advanced"),
  semantic("inspector:requirements", "cap.requirement.coverage"),
  semantic("inspector:anchor-drift", "cap.reuse.anchor-drift"),
  semantic("inspector:note-add", "cap.evidence.notes-anchors"),
  semantic("inspector:note-delete", "cap.evidence.notes-anchors"),
  semantic("inspector:anchor-mark-noted", "cap.evidence.notes-anchors"),
  semantic("inspector:anchor-ratify-source", "cap.evidence.notes-anchors"),
  semantic("inspector:copy-decision-log", "cap.handoff.skill"),
  semantic("tree:adopt-refinement", "cap.refinement.advanced"),
  semantic("tree:derived-view", "cap.view.derived"),
  semantic("opd-header:question-frontier", "cap.refinement.advanced"),
  semantic("opl:read", "cap.opl.forward-reverse"),
  semantic("opl:apply-preview", "cap.opl.forward-reverse"),
  semantic("diagnostic:focus-issue", "cap.diagnostic.reactive"),
  semantic("simulation:step", "cap.simulation.conceptual"),
  semantic("simulation:decision", "cap.simulation.conceptual"),
  semantic("simulation:numeric-run", "cap.simulation.numeric"),
  semantic("simulation:numeric-csv", "cap.simulation.numeric"),
  semantic("pieces:copy", "cap.reuse.pieces"),
  semantic("pieces:anchor", "cap.reuse.pieces"),
  semantic("anchor:resync", "cap.reuse.anchor-drift"),
  semantic("anchor:detach", "cap.reuse.anchor-drift"),
  semantic("submodel:open-reference", "cap.submodel.reference"),
  semantic("submodel:connect-reference", "cap.submodel.reference"),
  semantic("composition:apply", "cap.composition.interface"),
  semantic("workspace:incoming-review", "cap.history.review-version"),
  semantic("workspace:create-version", "cap.history.review-version"),
  semantic("workspace:delete-version", "cap.history.review-version"),
  semantic("workspace:restore-version-copy", "cap.history.review-version"),
  semantic("workspace:import-active", "cap.persistence.import-save"),
  semantic("workspace:import-new-tab", "cap.persistence.import-save"),
  semantic("workspace:save", "cap.persistence.import-save"),
  semantic("workspace:graduate-model", "cap.lifecycle.regime"),
  semantic("workspace:graduate-library", "cap.lifecycle.regime"),
  semantic("workspace:mark-library", "cap.lifecycle.regime"),
  semantic("workspace:unmark-library", "cap.lifecycle.regime"),
  semantic("tutor:search", "cap.discovery.corpus"),
  semantic("mobile:read-context", "cap.interaction.readonly"),
] as const;

export const TUTOR_ENTRYPOINT_CATALOG: readonly TutorEntrypoint[] = entrypointDefinitions.map((definition) => ({
  entrypointId: definition.entrypointId,
  classification: definition.owner === OPERATIONAL_EXEMPT ? "operational-exempt" : "semantic",
  ...(definition.reason ? { reason: definition.reason } : {}),
}));

const entrypointOwnerById = new Map<TutorEntrypointId, CapabilityId>(
  entrypointDefinitions.flatMap((definition) =>
    definition.owner === OPERATIONAL_EXEMPT ? [] : [[definition.entrypointId, definition.owner]],
  ),
);

export const TUTOR_CAPABILITIES = [
  capability({
    capabilityId: "cap.start.workspace",
    cut: "3A",
    family: "Nuevo, abrir y retomar",
    status: "live",
    behavior: "guide",
    owners: ["empty-state", "workspace-manager", "command-palette"],
    effects: [
      effect("workspace", ["palette:nuevo-modelo"], "Crea y activa un Apunte nuevo en otra pestaña.", "Cerrar la pestaña recién creada recupera el workspace anterior; no existe un paso de Cancelar."),
      effect("workspace", ["palette:abrir-pestana"], "Duplica el modelo activo en una pestaña editable adicional.", "Cerrar esa pestaña recupera el conjunto anterior; no existe un paso de Cancelar."),
    ],
    limits: ["Nuevo abre un Apunte sin encuesta ni perfil."],
    silentWhen: ["El operador ya inició por atajo o canvas."],
  }),
  capability({
    capabilityId: "cap.lifecycle.regime",
    cut: "2D",
    family: "Apunte, Modelo, Taller y Biblioteca",
    status: "live",
    behavior: "guide",
    owners: ["workspace-manager", "tree", "modal"],
    effects: [
      effectSequence(["workspace:graduate-model"], [
        effectStep("read", "Valida nombre, destino e issues antes de mutar.", "Corregir o cancelar conserva el Apunte íntegro."),
        effectStep("external", "Persiste la identidad y el destino elegidos.", "Un fallo conserva el Apunte y permite reintentar desde el diálogo."),
        effectStep("workspace", "Coordina rigor Modelo e índice sin cambiar los hechos OPM.", "La transacción fallida restaura rigor, identidad e índice previos."),
      ]),
      effectSequence(["workspace:graduate-library"], [
        effectStep("read", "Valida nombre, destino e issues antes de mutar.", "Corregir o cancelar conserva el Apunte íntegro."),
        effectStep("external", "Persiste identidad y destino de la futura Biblioteca.", "Un fallo conserva el Apunte y mantiene el diálogo recuperable."),
        effectStep("workspace", "Coordina rigor Modelo, rol Biblioteca e índice.", "La transacción fallida restaura rigor, rol, identidad e índice previos."),
      ]),
      effect("workspace", ["workspace:mark-library"], "Designa un Modelo de Trabajo como fuente de Piezas sin abrirlo.", "Quitar de bibliotecas recupera Modelo de Trabajo."),
      effect("workspace", ["workspace:unmark-library"], "Retira el rol Biblioteca sin cambiar hechos ni rigor.", "Marcar de nuevo recupera el rol, no una versión histórica del contenido."),
    ],
    limits: ["Adoptar no gradúa; graduar no certifica; marcar Biblioteca no abre."],
    silentWhen: ["La especie y la consecuencia ya son inequívocas en la superficie."],
  }),
  capability({
    capabilityId: "cap.purpose.sd-frontier",
    cut: "3A",
    family: "Propósito, SD y frontera",
    status: "live",
    behavior: "guide",
    owners: ["empty-state", "opd-header", "inspector"],
    effects: [effect("model", ["empty-state:choose-entry"], "Registra propósito y hechos del sistema modelado.", "Undo restaura el estado previo del documento.")],
    limits: ["SD-first y Taller son entradas legítimas; ninguna persiste una etapa."],
    silentWhen: ["El operador ya comenzó por un gesto directo."],
  }),
  capability({
    capabilityId: "cap.ficha.local",
    cut: "3A",
    family: "Ficha de trabajo local y enfoques de conocimiento",
    status: "live",
    behavior: "guide",
    owners: ["inspector"],
    effects: [
      effect("model", ["inspector:ficha-pregunta-habilitante", "inspector:ficha-dueno-significado", "inspector:ficha-responsable-decision", "inspector:ficha-tipos-modelo", "inspector:ficha-criterio-suficiencia", "inspector:ficha-vida-util", "inspector:ficha-revisar-cuando"], "Actualiza un campo de la ficha local sin emitir OPL ni bloquear el modelo.", "Undo restaura el valor anterior del campo."),
      effect("model", ["inspector:ficha-lentes-conocimiento"], "Actualiza los enfoques de conocimiento del modelo local.", "Undo restaura el conjunto y orden de enfoques anterior."),
    ],
    limits: ["Solo aplica sin procedencia upstream; la ficha orienta decisiones y no certifica suficiencia."],
    silentWhen: ["Existe procedencia upstream o el valor confirmado no cambió."],
  }),
  capability({
    capabilityId: "cap.entity.kind",
    cut: "3B",
    family: "Objetos y procesos",
    status: "live",
    behavior: "guide",
    owners: ["canvas", "inspector", "command-palette"],
    effects: [effect("model", ["canvas:create-object-process", "contextual:eliminar-seleccion", "inspector:entity-identity"], "Crea, renombra o elimina una cosa OPM.", "Undo restaura la cosa y sus hechos dependientes según el kernel.")],
    limits: ["No clasifica nombres mediante heurísticas léxicas."],
    silentWhen: ["Edición repetida sin duda de clasificación."],
  }),
  capability({
    capabilityId: "cap.entity.properties",
    cut: "3B",
    family: "Esencia, afiliación y metadatos",
    status: "live",
    behavior: "guide",
    owners: ["inspector", "command-palette"],
    effects: [effect("model", ["contextual:editar-alias", "contextual:editar-imagen", "inspector:entity-properties", "palette:editar-imagen-objeto", "palette:urls-objeto"], "Actualiza semántica o metadato en el campo propietario.", "Undo restaura el valor anterior.")],
    limits: ["Alias, URL e imagen no cambian la identidad lógica."],
    silentWhen: ["Propiedad conocida en edición repetida."],
  }),
  capability({
    capabilityId: "cap.state.lifecycle",
    cut: "3B",
    family: "Estados, designaciones y duración",
    status: "live",
    behavior: "guide",
    owners: ["inspector", "canvas", "simulation-bar"],
    effects: [effect("model", ["contextual:agregar-estado", "inspector:state-lifecycle"], "Actualiza estados y marcas declaradas del objeto.", "Undo restaura estados, orden y designaciones.")],
    limits: ["Los procesos no tienen estados; current de runtime no persiste."],
    silentWhen: ["Cambio repetido con consecuencia visible."],
  }),
  capability({
    capabilityId: "cap.link.procedural",
    cut: "3C",
    family: "Enlaces transformadores y habilitadores",
    status: "live",
    behavior: "guide",
    owners: ["canvas", "inspector", "command-palette"],
    effects: [effect("model", ["contextual:cambiar-tipo-enlace", "inspector:link-procedural", "palette:split-parcial"], "Crea o cambia un enlace procedural explícito.", "Undo restaura tipo, extremos y metadatos anteriores.")],
    limits: ["No elige un enlace plausible por default en nombre del operador."],
    silentWhen: ["Tipo y extremos son inequívocos."],
  }),
  capability({
    capabilityId: "cap.link.structural",
    cut: "3C",
    family: "Enlaces estructurales",
    status: "live",
    behavior: "guide",
    owners: ["canvas", "inspector", "selection-annotation"],
    effects: [effect("model", ["contextual:agregar-como-partes", "inspector:link-structural"], "Registra agregación, exhibición, generalización o instanciación.", "Undo restaura la relación anterior.")],
    limits: ["Las cuatro alternativas cambian significado y deben ser explícitas."],
    silentWhen: ["La relación ya fue elegida explícitamente."],
  }),
  capability({
    capabilityId: "cap.flow.control",
    cut: "3C",
    family: "Control, abanicos, multiplicidad, rutas y excepciones",
    status: "live",
    behavior: "guide",
    owners: ["inspector", "simulation-bar", "command-palette"],
    effects: [
      effect("model", ["inspector:flow-control"], "Configura política de control y multiplicidad viva.", "Undo restaura control, cardinalidad, ruta y grupo previos."),
      effect("transient-ui", ["palette:resolver-decision"], "Deriva una rama de decisión para el runtime y muestra el resultado sin persistirlo.", "Cerrar el mensaje o reiniciar la simulación recupera el estado transitorio; el modelo no cambió."),
    ],
    limits: ["El diagnóstico conserva inconsistencias persistentes."],
    silentWhen: ["Reproducción fluida o valor ya explícito."],
  }),
  capability({
    capabilityId: "cap.flow.probabilistic-weights",
    cut: "3C",
    family: "Abanico probabilístico declarado",
    status: "reference-only",
    behavior: "reference",
    owners: ["inspector", "simulation-bar"],
    effects: [effect("read", [], "Explica el caso C programado.", "La lectura no muta el modelo.")],
    limits: ["R-FAN-PROB-1 no persiste pesos; el uniforme de simulación no los sustituye."],
    silentWhen: ["No se consulta el fundamento del caso C."],
  }),
  capability({
    capabilityId: "cap.appearance.view",
    cut: "3C",
    family: "Apariciones, traer, ocultar, plegar y layout",
    status: "live",
    behavior: "guide",
    owners: ["canvas", "inspector", "tree", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:alias-visibles", "palette:descripciones-visibles", "palette:modo-imagen-global"], "Alterna una preferencia de representación sin cambiar hechos ni historial del modelo.", "Volver a alternarla recupera la preferencia visual anterior."),
      effect("model", ["contextual:alinear-seleccion", "contextual:distribuir-seleccion", "contextual:ocultar-apariencia", "contextual:traer-conectados", "contextual:traer-conectados-default", "contextual:traer-enlaces", "inspector:appearance", "palette:auto-layout"], "Cambia layout o presencia por OPD sin crear otra identidad lógica.", "Undo restaura la apariencia o layout anterior."),
    ],
    limits: ["Ocultar no borra; una aparición adicional no crea otra entidad."],
    silentWhen: ["Layout rutinario sin colisión, densidad o confusión de identidad."],
  }),
  capability({
    capabilityId: "cap.refinement.advanced",
    cut: "3C",
    family: "Refinamiento, adopción, plegado y frontera",
    status: "live",
    behavior: "guide",
    owners: ["selection-annotation", "opd-header", "tree", "inspector"],
    effects: [
      effect("transient-ui", ["contextual:verificar-coherencia-descomposicion", "inspector:refinement", "opd-header:question-frontier"], "Prepara pregunta, tipo y relación.", "Cancelar es identidad."),
      effect("model", ["contextual:inzoom", "contextual:quitar-descomposicion", "contextual:quitar-despliegue", "contextual:unfold", "palette:distribuir-contorno", "palette:recolectar-contorno", "tree:adopt-refinement"], "Aplica refinamiento o adopción en un commit.", "Undo restaura árbol, slot y pregunta previos."),
    ],
    limits: ["Adoptar integra sin graduar; quitar refinamiento elimina el subárbol vivo."],
    silentWhen: ["El resultado confirmado ya es visible y no compite con otro feedback."],
  }),
  capability({
    capabilityId: "cap.view.derived",
    cut: "3C",
    family: "Vistas derivadas, de requisito y submodelo",
    status: "live-read",
    behavior: "guide",
    owners: ["opd-header", "tree", "canvas"],
    effects: [effect("read", ["tree:derived-view"], "Navega una proyección sin hechos propios.", "Salir vuelve a la vista propietaria sin mutar.")],
    limits: ["No ofrece mutaciones ni llama refinamiento a una vista genérica."],
    silentWhen: ["El modo solo lectura ya está anunciado."],
  }),
  capability({
    capabilityId: "cap.requirement.coverage",
    cut: "3D",
    family: "Requisitos, evidencia y cobertura",
    status: "live",
    behavior: "guide",
    owners: ["inspector", "canvas", "command-palette"],
    effects: [
      effect("transient-ui", ["contextual:marcar-requisito", "contextual:satisfacer-requisito", "inspector:requirements", "palette:crear-requisito", "palette:marcar-requisito", "palette:satisfacer-requisito"], "Abre el diálogo propietario con la selección actual sin mutar el modelo.", "Cancelar conserva modelo, selección e historial."),
      effect("model", ["requirement:create", "requirement:mark", "requirement:satisfy"], "Crea, clasifica o vincula un requisito y su cobertura declarada.", "Undo restaura requisito y vínculos previos."),
    ],
    limits: ["Cobertura no prueba satisfacción empírica ni certifica verdad."],
    silentWhen: ["El vínculo y su alcance ya son explícitos."],
  }),
  capability({
    capabilityId: "cap.ontology.lexical",
    cut: "3D",
    family: "Ontología organizacional",
    status: "live",
    behavior: "guide",
    owners: ["modal", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:configurar-ontologia"], "Abre la normalización léxica sin cambiar el modelo.", "Cancelar conserva vocabulario, modelo e historial."),
      effect("model", ["ontology:save"], "Registra términos, sinónimos y el modo declarado.", "Undo o edición posterior restaura el vocabulario anterior."),
    ],
    limits: ["Es normalización léxica; no es una ontología formal y la UI todavía no consume suggest/enforce."],
    silentWhen: ["El modo y su efecto están visibles."],
  }),
  capability({
    capabilityId: "cap.opl.forward-reverse",
    cut: "4A",
    family: "OPL legible y edición inversa",
    status: "live",
    behavior: "guide",
    owners: ["opl-panel"],
    effects: [
      effect("read", ["opl:read"], "Muestra OPL y preview por línea.", "Cancelar conserva modelo e historial."),
      effect("model", ["opl:apply-preview"], "Aplica solo líneas reconocidas por la inversa viva.", "Undo restaura el modelo anterior."),
    ],
    limits: ["No amplía la gramática por copy; formas sin inversa vuelven al canvas."],
    silentWhen: ["Lectura rutinaria sin delta ni línea no aplicable."],
  }),
  capability({
    capabilityId: "cap.diagnostic.reactive",
    cut: "4B",
    family: "Diagnóstico reactivo",
    status: "live",
    behavior: "guide",
    owners: ["diagnostic-panel"],
    effects: [
      effect("read", ["diagnostic:focus-issue"], "Recomputa hallazgos y navega al hecho corregible.", "La lectura no muta; corregir usa la acción propietaria del hecho."),
      effect("external", ["palette:exportar-diagnostico"], "Serializa los hallazgos actuales y los copia al portapapeles.", "El modelo no cambia; una nueva copia reemplaza el recibo anterior."),
    ],
    limits: ["PanelDiagnostico es dueño único; no existe Revalidar manual."],
    silentWhen: ["No cambió el conjunto de hallazgos ni se pidió explicación."],
  }),
  capability({
    capabilityId: "cap.navigation.reasoning",
    cut: "4B",
    family: "Búsqueda, mapa, tabla y razonamiento de impacto",
    status: "live",
    behavior: "guide",
    owners: ["command-palette", "canvas", "inspector"],
    effects: [effect("read", ["contextual:razonar-afectan-a", "contextual:razonar-impacto-aguas-abajo", "contextual:razonar-impacto-eliminar", "contextual:razonar-requerido-por", "palette:buscar-modelo", "palette:buscar-workspace", "palette:tabla-enlaces"], "Deriva y enfoca estructura existente del modelo.", "Limpiar selección o cerrar la vista recupera el contexto anterior.")],
    limits: ["La derivación es estructural, no causal ni empírica; frontera igual no prueba equivalencia conductual."],
    silentWhen: ["Búsqueda o navegación rutinaria."],
  }),
  capability({
    capabilityId: "cap.simulation.conceptual",
    cut: "5A",
    family: "Simulación conceptual",
    status: "live",
    behavior: "guide",
    owners: ["simulation-bar", "opl-panel"],
    effects: [effect("transient-ui", ["palette:simulacion-conceptual", "simulation:decision", "simulation:step"], "Ejecuta un ensayo conceptual en runtime.", "Reiniciar o salir recupera el estado inicial sin presentar evidencia real.")],
    limits: ["No es ejecución del mundo ni validación empírica."],
    silentWhen: ["Reproducción fluida sin bloqueo ni decisión."],
  }),
  capability({
    capabilityId: "cap.simulation.numeric",
    cut: "5B",
    family: "Simulación numérica y CSV",
    status: "live",
    behavior: "guide",
    owners: ["numeric-simulation-dialog", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:simulacion-numerica"], "Abre el diálogo de muestreo sin ejecutar ni descargar.", "Cerrar conserva modelo e historial."),
      effect("transient-ui", ["simulation:numeric-run"], "Muestrea atributos configurados y muestra filas locales.", "Cerrar o volver a ejecutar descarta el resultado local; el modelo no cambia."),
      effect("external", ["simulation:numeric-csv"], "Descarga el CSV de las filas ya muestreadas.", "El modelo no cambia; regenerar con parámetros explícitos produce otro recibo."),
    ],
    limits: ["No ejecuta procesos, colas, capacidad ni rendimiento; no es evidencia real."],
    silentWhen: ["Parámetros y alcance ya están explícitos."],
  }),
  capability({
    capabilityId: "cap.reuse.pieces",
    cut: "6A",
    family: "Estereotipos y Piezas",
    status: "live",
    behavior: "guide",
    owners: ["pieces", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:vitrina-estereotipos"], "Abre Piezas y permite inspeccionar candidatos sin incorporarlos.", "Cerrar la vitrina conserva modelo e historial."),
      effect("model", ["pieces:copy", "pieces:anchor"], "Calca una copia o ancla una copia con referencia de origen.", "Undo revierte la incorporación completa."),
    ],
    limits: ["Calcar da independencia; Anclar conserva vigilancia, no sincronización automática de contenido."],
    silentWhen: ["La elección independencia/seguimiento ya fue confirmada."],
  }),
  capability({
    capabilityId: "cap.reuse.anchor-drift",
    cut: "6A",
    family: "Anclaje y drift",
    status: "live",
    behavior: "guide",
    owners: ["inspector"],
    effects: [effect("model", ["anchor:detach", "anchor:resync", "inspector:anchor-drift"], "Actualiza firma base o suelta el vínculo.", "Undo inmediato restaura firma o vigilancia anterior.")],
    limits: ["Re-sincronizar no cambia contenido local; no existe diff visual."],
    silentWhen: ["El anclaje permanece sincronizado."],
  }),
  capability({
    capabilityId: "cap.submodel.reference",
    cut: "6B",
    family: "Submodelo como referencia",
    status: "live-read",
    behavior: "guide",
    owners: ["modal", "tree", "command-palette"],
    effects: [
      effect("transient-ui", ["contextual:conectar-submodelo", "palette:conectar-submodelo"], "Abre la elección de referencia sin incorporar hechos.", "Cancelar conserva modelo, workspace e historial."),
      effect("model", ["submodel:connect-reference"], "Registra una referencia navegable de solo lectura.", "Undo quita la referencia incorporada."),
      effect("read", ["submodel:open-reference"], "Abre la vista derivada de la referencia cargada.", "Volver al OPD propietario no muta el modelo."),
    ],
    limits: ["Consultar no incorpora hechos ni acredita equivalencia."],
    silentWhen: ["La cabecera ya anuncia solo lectura."],
  }),
  capability({
    capabilityId: "cap.composition.interface",
    cut: "6B",
    family: "Composición con interfaz compartida",
    status: "live",
    behavior: "guide",
    owners: ["composition-dialog", "command-palette"],
    effects: [
      effect("transient-ui", ["contextual:componer-modelo"], "Abre el preflight de mapeos, procedencia e integridad.", "Cancelar conserva modelo, workspace e historial."),
      effect("model", ["composition:apply"], "Incorpora hechos por una interfaz explícita.", "Undo recupera el modelo anterior."),
    ],
    limits: ["Coincidencia es heurística; mapeos/integridad bloquean, linealidad solo orienta."],
    silentWhen: ["La consecuencia y la reversibilidad ya fueron confirmadas."],
  }),
  capability({
    capabilityId: "cap.evidence.notes-anchors",
    cut: "7A",
    family: "Notas, anclas y RATIFICAR",
    status: "live",
    behavior: "guide",
    owners: ["inspector"],
    effects: [
      effect("model", ["inspector:note-add"], "Agrega una duda local al target seleccionado.", "Undo elimina la nota recién agregada."),
      effect("model", ["inspector:note-delete"], "Elimina una nota local resuelta.", "Undo restaura la nota eliminada."),
      effect("model", ["inspector:anchor-mark-noted"], "Transiciona una ancla upstream pendiente a anotada en mesa.", "Undo devuelve el registro a pendiente."),
      effect("model", ["inspector:anchor-ratify-source"], "Registra una fuente explícita para la ratificación upstream.", "Undo restaura el estado de ratificación y su fuente previa."),
    ],
    limits: ["RATIFICAR solo llega desde un ancla upstream pendiente; la mesa no crea pendientes genéricos."],
    silentWhen: ["El canal y la autoridad ya están declarados."],
  }),
  capability({
    capabilityId: "cap.handoff.skill",
    cut: "7A",
    family: "Contexto y log para modelamiento-opm",
    status: "live",
    behavior: "guide",
    owners: ["command-palette", "inspector"],
    effects: [effect("external", ["palette:copiar-contexto-skill", "palette:copiar-log-decisiones", "inspector:copy-decision-log"], "Copia contexto o log para relevo explícito.", "El modelo no cambia; el portapapeles es un recibo reemplazable.")],
    limits: ["La skill externa re-elicita; opforja no simula ese trabajo."],
    silentWhen: ["La copia tuvo éxito y el destino ya está claro."],
  }),
  capability({
    capabilityId: "cap.ficha.upstream",
    cut: "7A",
    family: "Ficha con procedencia upstream",
    status: "external",
    behavior: "limit",
    owners: ["inspector"],
    effects: [effect("read", [], "Explica que la ficha propietaria vive upstream.", "No crea una ficha local paralela.")],
    limits: ["Se habilita solo tras probar proto, compilador, bundle y lectura propietaria."],
    silentWhen: ["No existe procedencia upstream."],
  }),
  capability({
    capabilityId: "cap.history.review-version",
    cut: "7B",
    family: "Revisión remota e historia de versiones",
    status: "live",
    behavior: "guide",
    owners: ["persistence-chip", "workspace-manager", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:versiones-modelo"], "Abre el historial propietario sin crear ni eliminar versiones.", "Cerrar conserva historia, modelo y workspace."),
      effect("read", ["palette:mostrar-archivados", "palette:mostrar-versiones", "workspace:incoming-review"], "Consulta y filtra historia persistida sin mutarla.", "Cerrar o restablecer el filtro recupera la vista anterior."),
      effect("external", ["workspace:create-version"], "Crea una versión histórica persistida del modelo actual.", "Un fallo conserva la historia previa; eliminarla después exige otra confirmación explícita."),
      effectSequence(["workspace:restore-version-copy"], [
        effectStep("external", "Lee y valida el snapshot histórico elegido.", "Un fallo conserva versión, modelo y workspace actuales."),
        effectStep("workspace", "Abre el snapshot como copia editable con identidad nueva.", "Cancelar antes de abrir no crea la copia; cerrarla recupera el workspace anterior."),
      ]),
      effectSequence(["workspace:delete-version"], [
        effectStep("transient-ui", "Exige confirmación irreversible sobre la versión exacta.", "Cancelar conserva la versión y devuelve el foco a su acción."),
        effectStep("external", "Elimina la versión histórica confirmada.", "Un fallo conserva la historia y permite reintentar; después del éxito no existe undo local."),
      ]),
    ],
    limits: ["Una revisión entrante no muta sin aceptación; no hay merge ni diff visual."],
    silentWhen: ["Autosalvado o versión rutinaria sin conflicto."],
  }),
  capability({
    capabilityId: "cap.persistence.import-save",
    cut: "7B",
    family: "Importar, guardar, autosalvar y Guardar como",
    status: "live",
    behavior: "guide",
    owners: ["workspace-manager", "persistence-chip", "command-palette"],
    effects: [
      effect("transient-ui", ["palette:abrir-importar", "palette:guardar-como"], "Abre el diálogo propietario sin leer, reemplazar ni persistir todavía.", "Cancelar conserva modelo, workspace e historial."),
      effectSequence(["workspace:import-active"], [
        effectStep("external", "Lee y valida el JSON elegido sin mutar.", "Un error conserva modelo, workspace e historial."),
        effectStep("transient-ui", "Hace preflight de trabajo dirty antes del reemplazo.", "Cancelar o preservar mantiene la pestaña activa intacta."),
        effectStep("model", "Reemplaza el documento activo por el importado validado.", "Antes del reemplazo puede cancelarse; después no se promete undo del documento anterior."),
        effectStep("model", "Reinicia el historial del documento reemplazado.", "La recuperación exigible es preservar antes o importar en pestaña nueva."),
      ]),
      effectSequence(["workspace:import-new-tab"], [
        effectStep("external", "Lee y valida el JSON elegido sin mutar la pestaña activa.", "Un error conserva el workspace anterior."),
        effectStep("workspace", "Abre el documento validado en una pestaña nueva.", "Cerrar la pestaña nueva recupera el conjunto previo."),
      ]),
      effectSequence(["workspace:save"], [
        effectStep("external", "Persiste el documento en el backend activo.", "Un fallo conserva el modelo vivo y su estado dirty; reintentar produce otro recibo."),
        effectStep("workspace", "Asigna o actualiza identidad y revisión conocida.", "Un fallo de persistencia no adelanta identidad ni revisión local."),
      ]),
    ],
    limits: ["Importar en activa reemplaza y reinicia historial; pestaña nueva no reemplaza."],
    silentWhen: ["Autosalvado rutinario con estado visible."],
  }),
  capability({
    capabilityId: "cap.export.interchange",
    cut: "7B",
    family: "Exportes y relevo",
    status: "live",
    behavior: "guide",
    owners: ["command-palette", "modal"],
    effects: [effect("external", ["palette:exportar-canon-documento", "palette:exportar-json", "palette:exportar-opd-png", "palette:exportar-opds-png-zip", "palette:exportar-opl-modelo"], "Produce JSON, OPL, Markdown, documento canónico, PNG o contexto.", "El modelo no cambia; el recibo identifica destino o causa de bloqueo.")],
    limits: ["Exportar no valida ni certifica; densidad y OPDs sueltos usan gates vivos."],
    silentWhen: ["Exportación rutinaria exitosa con destino explícito."],
  }),
  capability({
    capabilityId: "cap.discovery.corpus",
    cut: "7C",
    family: "Ctrl+K y corpus tutor",
    status: "live-read",
    behavior: "guide",
    owners: ["command-palette"],
    effects: [effect("read", ["tutor:search"], "Busca contenido tipado y fuentes registradas localmente.", "Cerrar la búsqueda no muta modelo ni experiencia persistida.")],
    limits: ["Lookup local indexado; no red, LLM, telemetría ni heurísticas de nombres."],
    silentWhen: ["La consulta no pide referencia pedagógica."],
  }),
  capability({
    capabilityId: "cap.abstraction.outzoom",
    cut: "7C",
    family: "Out-zoom automático",
    status: "reference-only",
    behavior: "reference",
    owners: ["command-palette"],
    effects: [effect("read", [], "Abre fundamento conceptual de abstracción.", "No ofrece mutación inexistente.")],
    limits: ["No hay entrypoint vivo de abstracción automática."],
    silentWhen: ["No se consulta la referencia."],
  }),
  capability({
    capabilityId: "cap.export.pdf-diff-merge",
    cut: "7C",
    family: "PDF, diff visual y merge multiusuario",
    status: "external",
    behavior: "limit",
    owners: ["command-palette"],
    effects: [effect("read", [], "Explica el límite y enumera solo exportes vivos.", "No crea controles ni archivos ficticios.")],
    limits: ["PDF real, diff visual y merge automático no están disponibles."],
    silentWhen: ["No se intenta una capacidad externa."],
  }),
  capability({
    capabilityId: "cap.inference.ai",
    cut: "7C",
    family: "Inferencia OPM automática",
    status: "external",
    behavior: "limit",
    owners: ["command-palette"],
    effects: [effect("read", [], "Declara que la clasificación y decisión siguen siendo humanas.", "No envía datos ni crea resultados.")],
    limits: ["AI Text e inferencia OPM no se anuncian mientras no estén vivos."],
    silentWhen: ["No se solicita inferencia automática."],
  }),
  capability({
    capabilityId: "cap.lifecycle.degrade",
    cut: "7C",
    family: "Degradar Modelo a Apunte",
    status: "absent",
    behavior: "silent",
    owners: ["workspace-manager"],
    effects: [],
    limits: ["No existe transición Modelo→Apunte."],
    silentWhen: ["Siempre: no se insinúa como acción."],
  }),
  capability({
    capabilityId: "cap.refinement.unadopt",
    cut: "7C",
    family: "Desadoptar sin borrar",
    status: "absent",
    behavior: "silent",
    owners: ["tree"],
    effects: [],
    limits: ["Quitar refinamiento destruye el subárbol; no lo devuelve al Taller."],
    silentWhen: ["Siempre: no se rotula la eliminación como desadopción."],
  }),
  capability({
    capabilityId: "cap.certification.automatic",
    cut: "7C",
    family: "Certificación o reparación automática",
    status: "absent",
    behavior: "silent",
    owners: ["diagnostic-panel", "workspace-manager"],
    effects: [],
    limits: ["Graduar, cubrir requisitos o exportar no certifica ni repara."],
    silentWhen: ["Siempre: no se promete aprobación automática."],
  }),
  capability({
    capabilityId: "cap.interaction.readonly",
    cut: "7C",
    family: "Móvil y modos solo lectura",
    status: "live-read",
    behavior: "guide",
    owners: ["mobile-read", "opd-header"],
    effects: [effect("read", ["mobile:read-context"], "Explica el modo y navega a una superficie compatible.", "La lectura no muta el modelo.")],
    limits: ["No renderiza controles de mutación imposibles."],
    silentWhen: ["La guardia de solo lectura ya es evidente."],
  }),
] as const satisfies readonly CapabilityDescriptor[];

export const CAPABILITY_BY_ID = new Map<CapabilityId, CapabilityDescriptor>(
  TUTOR_CAPABILITIES.map((descriptor) => [descriptor.capabilityId, descriptor]),
);

export const TUTOR_CUT_COVERAGE = [
  cutCoverage("1A", ["cap.refinement.advanced"], ["contextual:inzoom", "opd-header:question-frontier"], ["scenario.refinement.question-required", "scenario.refinement.confirmed"], "Pregunta guía, commit único y confirmación del resultado de descomposición."),
  cutCoverage("1B", ["cap.refinement.advanced"], ["contextual:unfold", "tree:adopt-refinement"], ["scenario.refinement.question-complete"], "Despliegue y adopción atraviesan el gateway tipado sin relación implícita."),
  cutCoverage("2A", ["cap.refinement.advanced", "cap.diagnostic.reactive"], ["contextual:inzoom", "diagnostic:focus-issue"], ["scenario.refinement.integrity-wins", "scenario.refinement.claimed-silent"], "Arbitraje determinista y deduplicación por intención o resultado."),
  cutCoverage("2B", ["cap.start.workspace", "cap.lifecycle.regime"], ["palette:nuevo-modelo", "tree:adopt-refinement"], ["scenario.entry.new-note-choice", "scenario.entry.lifecycle-decision"], "Apunte y Taller se distinguen sin convertir adopción en graduación."),
  cutCoverage("2C", ["cap.lifecycle.regime"], ["workspace:graduate-model"], ["scenario.entry.lifecycle-decision"], "Graduación valida antes de una secuencia externa y de workspace recuperable."),
  cutCoverage("2D", ["cap.lifecycle.regime"], ["workspace:graduate-library", "workspace:mark-library", "workspace:unmark-library"], ["scenario.entry.lifecycle-decision"], "Rol Biblioteca y rigor conservan transiciones explícitas y guardia de apertura."),
  cutCoverage("3A", ["cap.start.workspace", "cap.purpose.sd-frontier", "cap.ficha.local"], ["empty-state:choose-entry", "inspector:ficha-pregunta-habilitante", "inspector:ficha-lentes-conocimiento"], ["scenario.entry.purpose-workshop", "scenario.ficha.local-lenses-committed"], "Entrada simétrica y ficha local editable con roundtrip y undo."),
  cutCoverage("3B", ["cap.entity.kind", "cap.entity.properties", "cap.state.lifecycle"], ["canvas:create-object-process", "inspector:entity-properties", "inspector:state-lifecycle"], ["scenario.element.kind-object", "scenario.element.property-alias", "scenario.element.state-declared-current"], "Cosas, propiedades y estados distinguen declaración persistente y runtime."),
  cutCoverage("3C", ["cap.link.procedural", "cap.link.structural", "cap.flow.control", "cap.refinement.advanced"], ["inspector:link-procedural", "inspector:link-structural", "inspector:flow-control"], ["scenario.link.procedural-ready", "scenario.link.structural-ready"], "Enlaces, control y refinamiento avanzado conservan decisiones explícitas."),
  cutCoverage("3D", ["cap.requirement.coverage", "cap.ontology.lexical"], ["requirement:satisfy", "ontology:save"], ["scenario.knowledge.requirement-coverage", "scenario.knowledge.ontology-no-consumer"], "Cobertura, evidencia y normalización léxica permanecen separadas."),
  cutCoverage("4A", ["cap.opl.forward-reverse"], ["opl:read", "opl:apply-preview"], ["scenario.view.opl-preview"], "OPL expone preview y delta factual sin ampliar el parser inverso."),
  cutCoverage("4B", ["cap.diagnostic.reactive", "cap.navigation.reasoning"], ["diagnostic:focus-issue", "palette:buscar-modelo"], ["scenario.refinement.integrity-wins", "scenario.view.navigation-structural"], "Diagnóstico reactivo y razonamiento se rotulan estructurales, no causales."),
  cutCoverage("5A", ["cap.simulation.conceptual", "cap.flow.control"], ["simulation:step", "simulation:decision"], ["scenario.simulation.blocked", "scenario.simulation.decision", "scenario.simulation.running-silent"], "Simulación conceptual guía bloqueos y decisiones y calla durante reproducción fluida."),
  cutCoverage("5B", ["cap.simulation.numeric"], ["simulation:numeric-run", "simulation:numeric-csv"], ["scenario.numeric.configured-attributes"], "Muestreo numérico y CSV declaran su alcance sin prometer dinámica real."),
  cutCoverage("6A", ["cap.reuse.pieces", "cap.reuse.anchor-drift"], ["pieces:copy", "pieces:anchor", "anchor:resync", "anchor:detach"], ["scenario.reuse.pieces-choice", "scenario.reuse.anchor-drift-choice"], "Calcar, Anclar, resincronizar y soltar declaran independencia, vigilancia y recuperación."),
  cutCoverage("6B", ["cap.submodel.reference", "cap.composition.interface"], ["submodel:open-reference", "composition:apply"], ["scenario.reuse.submodel-readonly", "scenario.composition.preflight-oriented", "scenario.composition.mapping-blocked"], "Referencia e integración se separan; composición valida interfaz, procedencia y reversibilidad."),
  cutCoverage("7A", ["cap.evidence.notes-anchors", "cap.handoff.skill", "cap.ficha.upstream"], ["inspector:note-add", "inspector:anchor-ratify-source", "inspector:copy-decision-log", "palette:copiar-contexto-skill"], ["scenario.knowledge.evidence-local-note", "scenario.knowledge.evidence-route", "scenario.knowledge.handoff-ready", "scenario.nonlive.ficha-upstream"], "Nota, ancla, ratificación, relevo y ficha upstream conservan destinos distintos."),
  cutCoverage("7B", ["cap.history.review-version", "cap.persistence.import-save", "cap.export.interchange"], ["workspace:create-version", "workspace:restore-version-copy", "workspace:delete-version", "workspace:import-active", "workspace:import-new-tab", "palette:exportar-json"], ["scenario.persistence.version-create-confirmed", "scenario.persistence.version-delete-confirm", "scenario.persistence.import-active-dirty", "scenario.persistence.export-confirmed"], "Historia, importación e intercambio declaran destino, reemplazo y recuperación."),
  cutCoverage("7C", ["cap.discovery.corpus", "cap.interaction.readonly", "cap.export.pdf-diff-merge", "cap.inference.ai"], ["tutor:search", "mobile:read-context"], ["scenario.view.discovery-source-and-content", "scenario.view.mobile-readonly", "scenario.nonlive.export-pdf", "scenario.nonlive.inference"], "Corpus local, descubrimiento, solo lectura y silencios no vivos quedan auditados."),
] as const satisfies readonly TutorCutCoverage[];

export function getCapability(capabilityId: CapabilityId): CapabilityDescriptor | null {
  return CAPABILITY_BY_ID.get(capabilityId) ?? null;
}

function semantic(entrypointId: TutorEntrypointId, owner: CapabilityId): EntrypointDefinition {
  return { entrypointId, owner };
}

function cutCoverage(
  cut: TutorCutCoverage["cut"],
  capabilityIds: readonly CapabilityId[],
  entrypointIds: readonly TutorEntrypointId[],
  scenarioIds: readonly TutorCutCoverage["scenarioIds"][number][],
  proof: string,
): TutorCutCoverage {
  return { cut, capabilityIds, entrypointIds, scenarioIds, proof };
}

function exempt(entrypointId: TutorEntrypointId, reason: string): EntrypointDefinition {
  return { entrypointId, owner: OPERATIONAL_EXEMPT, reason };
}

function capability(descriptor: Omit<CapabilityDescriptor, "entrypointIds">): CapabilityDescriptor {
  return {
    ...descriptor,
    entrypointIds: [...entrypointOwnerById.entries()]
      .filter(([, owner]) => owner === descriptor.capabilityId)
      .map(([entrypointId]) => entrypointId)
      .sort((a, b) => a.localeCompare(b, "en")),
  };
}

function effect(
  kind: CapabilityEffectStep["kind"],
  entrypointIds: readonly TutorEntrypointId[],
  outcome: string,
  recovery: string,
): CapabilityEffect {
  return effectSequence(entrypointIds, [effectStep(kind, outcome, recovery)]);
}

function effectSequence(
  entrypointIds: readonly TutorEntrypointId[],
  steps: readonly CapabilityEffectStep[],
): CapabilityEffect {
  return { entrypointIds, steps };
}

function effectStep(
  kind: CapabilityEffectStep["kind"],
  outcome: string,
  recovery: string,
): CapabilityEffectStep {
  return { kind, outcome, recovery };
}
