import type {
  CompositionIntentSnapshot,
  FichaLocalIntentSnapshot,
  PersistenceIntentSnapshot,
  RefineIntentSnapshot,
  SimulationIntentSnapshot,
  TutorScenario,
} from "./tipos";
import {
  deriveElementIntent,
  deriveEntryIntent,
  deriveExportUnavailableIntent,
  deriveKnowledgeIntent,
  deriveLinkDesignIntent,
  deriveNumericSimulationIntent,
  deriveRefinementUnavailableIntent,
  deriveReuseIntent,
  deriveViewIntent,
} from "./adaptadores";

const refineQuestion: RefineIntentSnapshot = {
  kind: "refine",
  intentId: "intent-refine-question",
  actionId: "contextual:inzoom",
  surface: "selection-annotation",
  interactionMode: "editable",
  activeLenses: ["health", "systems", "health"],
  mode: "decomposition",
  stage: "question",
  questionComplete: false,
  integrityBlocked: false,
};

const simulation: SimulationIntentSnapshot = {
  kind: "simulation",
  intentId: "intent-simulation",
  actionId: "simulation:step",
  surface: "simulation-bar",
  interactionMode: "simulation",
  phase: "preflight",
  firstUse: false,
};

const composition: CompositionIntentSnapshot = {
  kind: "composition",
  intentId: "intent-composition",
  actionId: "composition:apply",
  surface: "composition-dialog",
  interactionMode: "editable",
  activeLenses: ["software", "systems"],
  phase: "preflight",
  mappingResolvable: true,
  integrityBlocked: false,
  linealityConflict: false,
};

const fichaLocal: FichaLocalIntentSnapshot = {
  kind: "ficha-local",
  intentId: "intent-ficha-pregunta",
  actionId: "inspector:ficha-pregunta-habilitante",
  surface: "inspector",
  interactionMode: "editable",
  activeLenses: ["systems"],
  field: "pregunta-habilitante",
  phase: "editing",
  valueChanged: true,
  hasUpstreamProvenance: false,
};

const persistence: PersistenceIntentSnapshot = {
  kind: "persistence",
  intentId: "intent-import-active",
  actionId: "workspace:import-active",
  surface: "workspace-manager",
  interactionMode: "editable",
  operation: "import-active",
  phase: "decision",
  hasUnsavedChanges: false,
  destructiveConfirmed: false,
};

export const TUTOR_SCENARIOS: readonly TutorScenario[] = [
  {
    scenarioId: "scenario.refinement.question-required",
    capabilityId: "cap.refinement.advanced",
    condition: "Un in-zoom nuevo llega sin pregunta guía y todavía no existe resultado.",
    snapshot: refineQuestion,
    expected: {
      kind: "ask",
      intentId: "intent-refine-question",
      actionId: "contextual:inzoom",
      owner: "selection-annotation",
      contentId: "content.refinement.question",
      priority: "human-decision",
      activeLenses: ["systems", "health"],
    },
    expectedContent: {
      contentId: "content.refinement.question",
      authorityPlane: "method",
      actionId: "opd-header:question-frontier",
      activeLenses: ["systems", "health"],
    },
    accessibility: ["La pregunta se anuncia una vez y el foco permanece en el gesto de refinamiento."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.refinement.question-complete",
    capabilityId: "cap.refinement.advanced",
    condition: "El in-zoom ya tiene una pregunta completa, pero aún puede orientar antes de confirmar.",
    snapshot: { ...refineQuestion, intentId: "intent-refine-oriented", questionComplete: true },
    expected: {
      kind: "orient",
      intentId: "intent-refine-oriented",
      actionId: "contextual:inzoom",
      owner: "selection-annotation",
      contentId: "content.refinement.question",
      priority: "optional-teaching",
      activeLenses: ["systems", "health"],
    },
    expectedContent: {
      contentId: "content.refinement.question",
      authorityPlane: "method",
      actionId: "opd-header:question-frontier",
      activeLenses: ["systems", "health"],
    },
    accessibility: ["La orientación no reemplaza ni bloquea la decisión ya expresada."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.refinement.integrity-wins",
    capabilityId: "cap.diagnostic.reactive",
    condition: "El refinamiento requiere pregunta, pero un hallazgo de integridad bloquea el mismo intento.",
    snapshot: { ...refineQuestion, intentId: "intent-refine-blocked", activeLenses: [], integrityBlocked: true },
    expected: {
      kind: "block",
      intentId: "intent-refine-blocked",
      actionId: "contextual:inzoom",
      owner: "diagnostic-panel",
      contentId: "content.diagnostic.integrity",
      priority: "integrity",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.diagnostic.integrity",
      authorityPlane: "validity",
      actionId: "diagnostic:focus-issue",
      activeLenses: [],
    },
    accessibility: ["Solo el bloqueo prioritario se anuncia; la enseñanza opcional queda suprimida."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.refinement.confirmed",
    capabilityId: "cap.refinement.advanced",
    condition: "La operación produjo un refinamiento identificado y debe confirmar su consecuencia.",
    snapshot: {
      ...refineQuestion,
      intentId: "intent-refine-confirmed",
      resultId: "refinement-result-1",
      activeLenses: [],
      stage: "confirmed",
      questionComplete: true,
      integrityBlocked: false,
    },
    expected: {
      kind: "confirm",
      intentId: "intent-refine-confirmed",
      resultId: "refinement-result-1",
      actionId: "contextual:inzoom",
      owner: "selection-annotation",
      contentId: "content.refinement.confirmed",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.refinement.confirmed",
      authorityPlane: "opd",
      activeLenses: [],
    },
    accessibility: ["La confirmación se asocia al resultado y no se repite desde otra superficie."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "refinar pide una pregunta antes del único commit y la muestra en el OPD hijo",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.refinement.claimed-silent",
    capabilityId: "cap.refinement.advanced",
    condition: "Flash ya posee el mismo intent de refinamiento antes de arbitrar el tutor.",
    snapshot: { ...refineQuestion, intentId: "intent-refine-owned", activeLenses: [] },
    claims: [{ owner: "flash", intentId: "intent-refine-owned" }],
    expected: {
      kind: "silent",
      intentId: "intent-refine-owned",
      reason: "already-owned",
    },
    accessibility: ["No se crea una segunda región viva para el mismo intento."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.first-use",
    capabilityId: "cap.simulation.conceptual",
    condition: "La primera apertura de la simulación está en preflight y aún no corre.",
    snapshot: { ...simulation, intentId: "intent-simulation-first", firstUse: true },
    expected: {
      kind: "orient",
      intentId: "intent-simulation-first",
      actionId: "simulation:step",
      owner: "simulation-bar",
      contentId: "content.simulation.conceptual.scope",
      priority: "optional-teaching",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.simulation.conceptual.scope",
      authorityPlane: "validity",
      actionId: "simulation:step",
      activeLenses: [],
    },
    accessibility: ["La orientación inicial aparece antes de la reproducción y solo una vez."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.blocked",
    capabilityId: "cap.simulation.conceptual",
    condition: "Un paso no satisface sus condiciones vivas y la corrida no puede avanzar.",
    snapshot: { ...simulation, intentId: "intent-simulation-blocked", phase: "blocked" },
    expected: {
      kind: "block",
      intentId: "intent-simulation-blocked",
      actionId: "simulation:step",
      owner: "simulation-bar",
      contentId: "content.simulation.conceptual.blocked",
      priority: "integrity",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.simulation.conceptual.blocked",
      authorityPlane: "validity",
      actionId: "simulation:step",
      activeLenses: [],
    },
    accessibility: ["El bloqueo identifica una causa navegable y no anuncia progreso ficticio."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.decision",
    capabilityId: "cap.flow.control",
    condition: "La corrida alcanza un abanico con decisión humana pendiente.",
    snapshot: { ...simulation, intentId: "intent-simulation-decision", actionId: "simulation:decision", phase: "decision" },
    expected: {
      kind: "ask",
      intentId: "intent-simulation-decision",
      actionId: "simulation:decision",
      owner: "simulation-bar",
      contentId: "content.flow.control.decision",
      priority: "human-decision",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.flow.control.decision",
      authorityPlane: "validity",
      actionId: "inspector:flow-control",
      activeLenses: [],
    },
    accessibility: ["La pregunta de decisión tiene nombre accesible y no elige una rama por el operador."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.step",
    capabilityId: "cap.simulation.conceptual",
    condition: "Una transición conceptual termina y existe un resultado del paso.",
    snapshot: { ...simulation, intentId: "intent-simulation-step", resultId: "simulation-step-7", phase: "step" },
    expected: {
      kind: "confirm",
      intentId: "intent-simulation-step",
      resultId: "simulation-step-7",
      actionId: "simulation:step",
      owner: "simulation-bar",
      contentId: "content.simulation.conceptual.step",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.simulation.conceptual.step",
      authorityPlane: "validity",
      actionId: "simulation:step",
      activeLenses: [],
    },
    accessibility: ["La confirmación se asocia al resultado del paso y no a cada frame."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.complete",
    capabilityId: "cap.simulation.conceptual",
    condition: "No quedan procesos habilitados y la corrida alcanza su salida completa.",
    snapshot: { ...simulation, intentId: "intent-simulation-complete", resultId: "simulation-run-1", phase: "complete" },
    expected: {
      kind: "confirm",
      intentId: "intent-simulation-complete",
      resultId: "simulation-run-1",
      actionId: "simulation:step",
      owner: "simulation-bar",
      contentId: "content.simulation.conceptual.complete",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.simulation.conceptual.complete",
      authorityPlane: "validity",
      activeLenses: [],
    },
    accessibility: ["El cierre se anuncia una vez sin presentarlo como validación empírica."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.composition.preflight-oriented",
    capabilityId: "cap.composition.interface",
    condition: "La interfaz y sus mapeos resuelven antes de que el operador elija aplicar.",
    snapshot: composition,
    expected: {
      kind: "orient",
      intentId: "intent-composition",
      actionId: "composition:apply",
      owner: "composition-dialog",
      contentId: "content.composition.choice",
      priority: "optional-teaching",
      activeLenses: ["systems", "software"],
    },
    expectedContent: {
      contentId: "content.composition.choice",
      authorityPlane: "validity",
      actionId: "composition:apply",
      activeLenses: ["systems", "software"],
    },
    accessibility: ["La orientación antecede a la mutación y mantiene el foco en el diálogo propietario."],
    integrationEvidence: {
      file: "e2e/32-composicion-modelos.spec.ts",
      test: "componer con modelo desde catálogo aplica interfaz compartida sugerida",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.composition.mapping-blocked",
    capabilityId: "cap.composition.interface",
    condition: "Un mapeo requerido no resuelve contra ninguna entidad de la interfaz destino.",
    snapshot: { ...composition, intentId: "intent-composition-unresolved", mappingResolvable: false },
    expected: {
      kind: "block",
      intentId: "intent-composition-unresolved",
      actionId: "composition:apply",
      owner: "composition-dialog",
      contentId: "content.composition.choice",
      priority: "integrity",
      activeLenses: ["systems", "software"],
    },
    expectedContent: {
      contentId: "content.composition.choice",
      authorityPlane: "validity",
      actionId: "composition:apply",
      activeLenses: ["systems", "software"],
    },
    accessibility: ["El bloqueo identifica el mapeo irresoluble sin sugerir que fue aplicado."],
    integrationEvidence: {
      file: "e2e/32-composicion-modelos.spec.ts",
      test: "componer con modelo desde catálogo aplica interfaz compartida sugerida",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.composition.lineality-oriented",
    capabilityId: "cap.composition.interface",
    condition: "Los mapeos resuelven, pero una coincidencia múltiple impide tratar la linealidad como equivalencia.",
    snapshot: { ...composition, intentId: "intent-composition-lineality", linealityConflict: true },
    expected: {
      kind: "orient",
      intentId: "intent-composition-lineality",
      actionId: "composition:apply",
      owner: "composition-dialog",
      contentId: "content.composition.preservation",
      priority: "optional-teaching",
      activeLenses: ["systems", "software"],
    },
    expectedContent: {
      contentId: "content.composition.preservation",
      authorityPlane: "formal-explanation",
      activeLenses: ["systems", "software"],
    },
    accessibility: ["La explicación conserva lenguaje de orientación y no declara equivalencia automática."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.composition.applied",
    capabilityId: "cap.composition.interface",
    condition: "La composición terminó y el feedback propietario ya posee el mismo resultado.",
    snapshot: {
      ...composition,
      intentId: "intent-composition-applied",
      resultId: "composition-result-1",
      phase: "applied",
      mappingResolvable: true,
      integrityBlocked: false,
    },
    claims: [{ owner: "product", resultId: "composition-result-1" }],
    expected: {
      kind: "silent",
      intentId: "intent-composition-applied",
      resultId: "composition-result-1",
      reason: "already-owned",
    },
    accessibility: ["El feedback propietario anuncia el resultado una vez; el tutor no repite la confirmación."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.ficha.local-field-oriented",
    capabilityId: "cap.ficha.local",
    condition: "Una pregunta habilitante local cambió y el modelo no tiene procedencia upstream.",
    snapshot: fichaLocal,
    expected: {
      kind: "orient",
      intentId: "intent-ficha-pregunta",
      actionId: "inspector:ficha-pregunta-habilitante",
      owner: "inspector",
      contentId: "content.ficha.local",
      priority: "optional-teaching",
      activeLenses: ["systems"],
    },
    expectedContent: {
      contentId: "content.ficha.local",
      authorityPlane: "method",
      activeLenses: ["systems"],
    },
    accessibility: ["La orientación permanece junto al campo y no anuncia OPL ni validación."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.ficha.local-lenses-committed",
    capabilityId: "cap.ficha.local",
    condition: "El operador confirmó un conjunto nuevo de enfoques para una ficha local.",
    snapshot: {
      ...fichaLocal,
      intentId: "intent-ficha-lentes",
      resultId: "ficha-lentes-result-1",
      actionId: "inspector:ficha-lentes-conocimiento",
      field: "lentes-conocimiento",
      phase: "committed",
      valueChanged: true,
      activeLenses: ["health", "systems"],
    },
    expected: {
      kind: "confirm",
      intentId: "intent-ficha-lentes",
      resultId: "ficha-lentes-result-1",
      actionId: "inspector:ficha-lentes-conocimiento",
      owner: "inspector",
      contentId: "content.ficha.local",
      priority: "consequence",
      activeLenses: ["systems", "health"],
    },
    expectedContent: {
      contentId: "content.ficha.local",
      authorityPlane: "method",
      activeLenses: ["systems", "health"],
    },
    accessibility: ["La confirmación nombra el resultado local y no crea una ficha upstream paralela."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "la ficha local conecta campo y enfoque a commits atómicos recuperables",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.import-active-dirty",
    capabilityId: "cap.persistence.import-save",
    condition: "Importar en la pestaña activa reemplazaría cambios locales todavía sin guardar.",
    snapshot: { ...persistence, hasUnsavedChanges: true },
    expected: {
      kind: "confirm",
      intentId: "intent-import-active",
      actionId: "workspace:import-active",
      owner: "workspace-manager",
      contentId: "content.persistence.import-save",
      priority: "loss-or-concurrency",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.persistence.import-save",
      authorityPlane: "method",
      actionId: "palette:abrir-importar",
      activeLenses: [],
    },
    accessibility: ["La advertencia nombra reemplazo y recuperación antes de cualquier efecto externo."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "la importación distingue reemplazo riesgoso de pestaña nueva recuperable",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.import-new-oriented",
    capabilityId: "cap.persistence.import-save",
    condition: "El operador elige importar en una pestaña nueva sin reemplazar el documento activo.",
    snapshot: {
      ...persistence,
      intentId: "intent-import-new",
      actionId: "workspace:import-new-tab",
      operation: "import-new",
    },
    expected: {
      kind: "orient",
      intentId: "intent-import-new",
      actionId: "workspace:import-new-tab",
      owner: "workspace-manager",
      contentId: "content.persistence.import-save",
      priority: "optional-teaching",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.persistence.import-save",
      authorityPlane: "method",
      actionId: "palette:abrir-importar",
      activeLenses: [],
    },
    accessibility: ["La orientación diferencia pestaña nueva de reemplazo sin bloquear una opción recuperable."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.persistence.version-create-confirmed",
    capabilityId: "cap.history.review-version",
    condition: "La creación manual terminó y produjo una versión histórica identificada.",
    snapshot: {
      ...persistence,
      intentId: "intent-version-create",
      resultId: "version-result-1",
      actionId: "workspace:create-version",
      surface: "modal",
      operation: "version-create",
      phase: "confirmed",
      destructiveConfirmed: false,
    },
    expected: {
      kind: "confirm",
      intentId: "intent-version-create",
      resultId: "version-result-1",
      actionId: "workspace:create-version",
      owner: "modal",
      contentId: "content.history.version-mutation",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.history.version-mutation",
      authorityPlane: "method",
      activeLenses: [],
    },
    accessibility: ["La confirmación identifica la versión creada sin confundirla con guardar el modelo."],
    integrationEvidence: {
      file: "e2e/46-versiones-tutor.spec.ts",
      test: "versiones crea, restaura como copia y elimina con recibo; el fallo conserva historia",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.version-restore-confirmed",
    capabilityId: "cap.history.review-version",
    condition: "La restauración terminó como una copia persistida con identidad nueva.",
    snapshot: {
      ...persistence,
      intentId: "intent-version-restore",
      resultId: "restored-model-1",
      actionId: "workspace:restore-version-copy",
      surface: "modal",
      operation: "version-restore-copy",
      phase: "confirmed",
      destructiveConfirmed: false,
    },
    expected: {
      kind: "confirm",
      intentId: "intent-version-restore",
      resultId: "restored-model-1",
      actionId: "workspace:restore-version-copy",
      owner: "modal",
      contentId: "content.history.version-mutation",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.history.version-mutation",
      authorityPlane: "method",
      activeLenses: [],
    },
    accessibility: ["El recibo distingue la copia editable del snapshot histórico de origen."],
    integrationEvidence: {
      file: "e2e/46-versiones-tutor.spec.ts",
      test: "versiones crea, restaura como copia y elimina con recibo; el fallo conserva historia",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.version-delete-decision-owned",
    capabilityId: "cap.history.review-version",
    condition: "El diálogo propietario ya anuncia la eliminación irreversible antes del commit.",
    snapshot: {
      ...persistence,
      intentId: "intent-version-delete",
      actionId: "workspace:delete-version",
      surface: "modal",
      operation: "version-delete",
    },
    claims: [{ owner: "product", intentId: "intent-version-delete" }],
    expected: {
      kind: "silent",
      intentId: "intent-version-delete",
      reason: "already-owned",
    },
    accessibility: ["El diálogo propietario mantiene una sola voz y enfoca Cancelar por defecto."],
    integrationEvidence: {
      file: "e2e/46-versiones-tutor.spec.ts",
      test: "versiones crea, restaura como copia y elimina con recibo; el fallo conserva historia",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.version-delete-confirmed",
    capabilityId: "cap.history.review-version",
    condition: "La eliminación irreversible terminó y produjo un recibo asociado a la versión exacta.",
    snapshot: {
      ...persistence,
      intentId: "intent-version-delete-confirmed",
      resultId: "version-delete-result-1",
      actionId: "workspace:delete-version",
      surface: "modal",
      operation: "version-delete",
      phase: "confirmed",
      destructiveConfirmed: true,
    },
    expected: {
      kind: "confirm",
      intentId: "intent-version-delete-confirmed",
      resultId: "version-delete-result-1",
      actionId: "workspace:delete-version",
      owner: "modal",
      contentId: "content.history.version-mutation",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.history.version-mutation",
      authorityPlane: "method",
      activeLenses: [],
    },
    accessibility: ["El recibo identifica la versión eliminada y declara que no existe undo local."],
    integrationEvidence: {
      file: "e2e/46-versiones-tutor.spec.ts",
      test: "versiones crea, restaura como copia y elimina con recibo; el fallo conserva historia",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.persistence.export-confirmed",
    capabilityId: "cap.export.interchange",
    condition: "La exportación JSON terminó y produjo un resultado descargable identificado.",
    snapshot: {
      ...persistence,
      intentId: "intent-export-confirmed",
      resultId: "export-result-1",
      actionId: "palette:exportar-json",
      surface: "command-palette",
      operation: "export",
      phase: "confirmed",
      destructiveConfirmed: true,
    },
    expected: {
      kind: "confirm",
      intentId: "intent-export-confirmed",
      resultId: "export-result-1",
      actionId: "palette:exportar-json",
      owner: "command-palette",
      contentId: "content.export.interchange",
      priority: "consequence",
      activeLenses: [],
    },
    expectedContent: {
      contentId: "content.export.interchange",
      authorityPlane: "method",
      actionId: "palette:exportar-json",
      activeLenses: [],
    },
    accessibility: ["La confirmación distingue archivo producido de validación del modelo."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.simulation.running-silent",
    capabilityId: "cap.simulation.conceptual",
    condition: "La reproducción avanza sin bloqueo, decisión ni consecuencia terminal.",
    snapshot: { ...simulation, intentId: "intent-simulation-running", phase: "running" },
    expected: {
      kind: "silent",
      intentId: "intent-simulation-running",
      reason: "no-candidate",
    },
    accessibility: ["La barra conserva su estado vivo sin anuncios redundantes por frame."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.entry.new-note-choice",
    capabilityId: "cap.start.workspace",
    condition: "El workspace tiene una pestaña y el operador enfoca Nuevo antes de crear el Apunte.",
    snapshot: deriveEntryIntent({ intentId: "intent-entry-new-note", focus: "start", operation: "new-note", tabsBefore: 1, tabsAfter: 1 }),
    expected: { kind: "orient", intentId: "intent-entry-new-note", actionId: "palette:nuevo-modelo", owner: "command-palette", contentId: "content.start.entry", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.start.entry", authorityPlane: "method", actionId: "palette:nuevo-modelo", activeLenses: [] },
    accessibility: ["La orientación no inventa un paso Cancelar para una pestaña que aún no fue creada."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.entry.lifecycle-decision",
    capabilityId: "cap.lifecycle.regime",
    condition: "La graduación está en decisión y la proyección confirma que los hechos se preservan.",
    snapshot: deriveEntryIntent({ intentId: "intent-entry-lifecycle", focus: "lifecycle", transition: "graduate", factsPreserved: true }),
    expected: { kind: "orient", intentId: "intent-entry-lifecycle", actionId: "workspace:graduate-model", owner: "modal", contentId: "content.lifecycle.regime", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.lifecycle.regime", authorityPlane: "method", actionId: "workspace:graduate-model", activeLenses: [] },
    accessibility: ["La guía permanece subordinada a la decisión explícita de régimen."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.entry.purpose-workshop",
    capabilityId: "cap.purpose.sd-frontier",
    condition: "El operador elige Taller con un propósito ya declarado en el estado vacío.",
    snapshot: deriveEntryIntent({ intentId: "intent-entry-purpose", focus: "purpose", strategy: "workshop", purposePresent: true }),
    expected: { kind: "orient", intentId: "intent-entry-purpose", actionId: "empty-state:choose-entry", owner: "empty-state", contentId: "content.purpose.frontier", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.purpose.frontier", authorityPlane: "method", actionId: "empty-state:choose-entry", activeLenses: [] },
    accessibility: ["SD-first y Taller conservan el mismo nivel visual de elección."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.element.kind-object",
    capabilityId: "cap.entity.kind",
    condition: "El gesto de creación ya resolvió que la cosa será un objeto.",
    snapshot: deriveElementIntent({ intentId: "intent-element-kind", focus: "kind", chosenKind: "object" }),
    expected: { kind: "orient", intentId: "intent-element-kind", actionId: "canvas:create-object-process", owner: "canvas", contentId: "content.entity.kind", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.entity.kind", authorityPlane: "validity", actionId: "canvas:create-object-process", activeLenses: [] },
    accessibility: ["La guía no reclasifica la elección por heurística léxica."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.element.property-alias",
    capabilityId: "cap.entity.properties",
    condition: "El inspector edita un alias y el adaptador constata que no cambia identidad lógica.",
    snapshot: deriveElementIntent({ intentId: "intent-element-property", focus: "properties", property: "alias" }),
    expected: { kind: "orient", intentId: "intent-element-property", actionId: "inspector:entity-properties", owner: "inspector", contentId: "content.entity.properties", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.entity.properties", authorityPlane: "validity", actionId: "inspector:entity-properties", activeLenses: [] },
    accessibility: ["La orientación queda junto al campo propietario."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.element.state-declared-current",
    capabilityId: "cap.state.lifecycle",
    condition: "Un objeto tiene Current declarado, mientras el runner todavía no tiene current de runtime.",
    snapshot: deriveElementIntent({ intentId: "intent-element-state", focus: "state", ownerKind: "object", declaredCurrent: true, runtimeCurrent: false }),
    expected: { kind: "orient", intentId: "intent-element-state", actionId: "inspector:state-lifecycle", owner: "inspector", contentId: "content.state.lifecycle", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.state.lifecycle", authorityPlane: "validity", actionId: "inspector:state-lifecycle", activeLenses: [] },
    accessibility: ["Declared Current y runtime current no comparten anuncio."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.link.procedural-ready",
    capabilityId: "cap.link.procedural",
    condition: "El inspector tiene ambos extremos y un tipo procedural explícito.",
    snapshot: deriveLinkDesignIntent({ intentId: "intent-link-procedural", focus: "procedural", endpointsReady: true, selectedType: "consumo" }),
    expected: { kind: "orient", intentId: "intent-link-procedural", actionId: "inspector:link-procedural", owner: "inspector", contentId: "content.link.procedural", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.link.procedural", authorityPlane: "validity", actionId: "inspector:link-procedural", activeLenses: [] },
    accessibility: ["La orientación no escoge otro enlace en nombre del operador."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.link.structural-ready",
    capabilityId: "cap.link.structural",
    condition: "La relación estructural fue elegida explícitamente como agregación.",
    snapshot: deriveLinkDesignIntent({ intentId: "intent-link-structural", focus: "structural", selectedRelation: "aggregation" }),
    expected: { kind: "orient", intentId: "intent-link-structural", actionId: "inspector:link-structural", owner: "inspector", contentId: "content.link.structural", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.link.structural", authorityPlane: "validity", actionId: "inspector:link-structural", activeLenses: [] },
    accessibility: ["Las cuatro relaciones permanecen distinguibles por nombre."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.view.appearance-existing",
    capabilityId: "cap.appearance.view",
    condition: "La entidad ya tiene dos apariciones y ninguna crea una identidad lógica adicional.",
    snapshot: deriveViewIntent({ intentId: "intent-view-appearance", focus: "appearance", appearanceCount: 2 }),
    expected: { kind: "orient", intentId: "intent-view-appearance", actionId: "inspector:appearance", owner: "inspector", contentId: "content.appearance.view", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.appearance.view", authorityPlane: "opd", actionId: "inspector:appearance", activeLenses: [] },
    accessibility: ["La orientación no llama copia a una aparición."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.view.derived-readonly",
    capabilityId: "cap.view.derived",
    condition: "El árbol abre una proyección derivada de solo lectura que no posee hechos.",
    snapshot: deriveViewIntent({ intentId: "intent-view-derived", focus: "derived", readOnly: true }),
    expected: { kind: "orient", intentId: "intent-view-derived", actionId: "tree:derived-view", owner: "tree", contentId: "content.view.derived", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.view.derived", authorityPlane: "opd", actionId: "tree:derived-view", activeLenses: [] },
    accessibility: ["La vista anuncia solo lectura sin ofrecer mutaciones."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.knowledge.requirement-coverage",
    capabilityId: "cap.requirement.coverage",
    condition: "La cobertura está declarada, pero el estado real no contiene evidencia externa.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-knowledge-requirement", focus: "requirement", operation: "satisfy", coverageDeclared: true, externalEvidencePresent: false }),
    expected: { kind: "orient", intentId: "intent-knowledge-requirement", actionId: "requirement:satisfy", owner: "inspector", contentId: "content.requirement.coverage", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.requirement.coverage", authorityPlane: "validity", actionId: "requirement:satisfy", activeLenses: [] },
    accessibility: ["La guía no anuncia cumplimiento ni certificación."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.knowledge.ontology-no-consumer",
    capabilityId: "cap.ontology.lexical",
    condition: "El glosario contiene términos, pero no existe consumidor automático de nombres.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-knowledge-ontology", focus: "ontology", termCount: 3, automaticConsumerAvailable: false }),
    expected: { kind: "orient", intentId: "intent-knowledge-ontology", actionId: "ontology:save", owner: "modal", contentId: "content.ontology.lexical", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.ontology.lexical", authorityPlane: "method", actionId: "ontology:save", activeLenses: [] },
    accessibility: ["La orientación no promete sugerencia ni reemplazo automático."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "requisitos y vocabulario exponen guía propietaria sin prometer inferencia",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.view.opl-preview",
    capabilityId: "cap.opl.forward-reverse",
    condition: "El editor muestra dos líneas reconocidas y una no reconocida antes de aplicar.",
    snapshot: deriveViewIntent({ intentId: "intent-view-opl", focus: "opl", recognizedLines: 2, unrecognizedLines: 1, previewVisible: true }),
    expected: { kind: "orient", intentId: "intent-view-opl", actionId: "opl:apply-preview", owner: "opl-panel", contentId: "content.opl.delta", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.opl.delta", authorityPlane: "opl", actionId: "opl:apply-preview", activeLenses: [] },
    accessibility: ["El preview conserva separadas líneas aplicables y ruta al canvas."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.view.navigation-structural",
    capabilityId: "cap.navigation.reasoning",
    condition: "La búsqueda encuentra dos hechos y el adaptador no emite una afirmación causal.",
    snapshot: deriveViewIntent({ intentId: "intent-view-navigation", focus: "navigation", query: "afecta", resultCount: 2 }),
    expected: { kind: "orient", intentId: "intent-view-navigation", actionId: "palette:buscar-modelo", owner: "command-palette", contentId: "content.navigation.reasoning", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.navigation.reasoning", authorityPlane: "method", actionId: "palette:buscar-modelo", activeLenses: [] },
    accessibility: ["Los resultados se rotulan estructurales y siguen siendo navegables."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.numeric.configured-attributes",
    capabilityId: "cap.simulation.numeric",
    condition: "Dos atributos están configurados para muestreo y no existe dinámica de procesos.",
    snapshot: deriveNumericSimulationIntent({ intentId: "intent-numeric-simulation", phase: "configure", configuredAttributeCount: 2 }),
    expected: { kind: "orient", intentId: "intent-numeric-simulation", actionId: "simulation:numeric-run", owner: "numeric-simulation-dialog", contentId: "content.simulation.numeric.scope", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.simulation.numeric.scope", authorityPlane: "method", actionId: "simulation:numeric-run", activeLenses: [] },
    accessibility: ["La guía nombra muestreo y no ejecución real."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "la simulación numérica declara el alcance real del CSV",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.reuse.pieces-choice",
    capabilityId: "cap.reuse.pieces",
    condition: "Hay origen seleccionado, pero todavía falta decidir Calcar o Anclar.",
    snapshot: deriveReuseIntent({ intentId: "intent-reuse-pieces", focus: "pieces", originSelected: true, anchorAvailable: true, choice: null }),
    expected: { kind: "ask", intentId: "intent-reuse-pieces", actionId: "palette:vitrina-estereotipos", owner: "pieces", contentId: "content.reuse.pieces", priority: "human-decision", activeLenses: [] },
    expectedContent: { contentId: "content.reuse.pieces", authorityPlane: "method", actionId: "palette:vitrina-estereotipos", activeLenses: [] },
    accessibility: ["La pregunta conserva dos acciones con nombres distintos."],
    integrationEvidence: {
      file: "e2e/35-piezas-puerta.spec.ts",
      test: "una biblioteca designada se ofrece como fuente; Calcar clona sin anclaje, Anclar deja anclaje sincronizado",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.reuse.anchor-drift-choice",
    capabilityId: "cap.reuse.anchor-drift",
    condition: "El centinela detectó drift y falta decidir resincronizar o soltar.",
    snapshot: deriveReuseIntent({ intentId: "intent-reuse-anchor", focus: "anchor-drift", driftDetected: true, choice: null }),
    expected: { kind: "ask", intentId: "intent-reuse-anchor", actionId: "inspector:anchor-drift", owner: "inspector", contentId: "content.reuse.anchor-drift", priority: "human-decision", activeLenses: [] },
    expectedContent: { contentId: "content.reuse.anchor-drift", authorityPlane: "method", actionId: "inspector:anchor-drift", activeLenses: [] },
    accessibility: ["Soltar declara pérdida de vigilancia antes del commit."],
    integrationEvidence: {
      file: "e2e/34-centinela-drift.spec.ts",
      test: "divergente: la mutación SEMÁNTICA de la biblioteca enciende el marcador, sin tocar el hash congelado",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.reuse.submodel-readonly",
    capabilityId: "cap.submodel.reference",
    condition: "La referencia cargó y permanece de solo lectura en su diálogo propietario.",
    snapshot: deriveReuseIntent({ intentId: "intent-reuse-submodel", focus: "submodel", phase: "reading", referenceLoaded: true, readOnly: true }),
    expected: { kind: "orient", intentId: "intent-reuse-submodel", actionId: "submodel:open-reference", owner: "modal", contentId: "content.submodel.reference", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.submodel.reference", authorityPlane: "method", actionId: "submodel:open-reference", activeLenses: [] },
    accessibility: ["No aparecen controles de edición dentro de la referencia."],
    integrationEvidence: {
      file: "e2e/20-inspector-tabs.spec.ts",
      test: "conectar submodelo selecciona un modelo existente desde catálogo y crea referencia LF-04",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.knowledge.evidence-local-note",
    capabilityId: "cap.evidence.notes-anchors",
    condition: "La mesa registra una duda local sin convertirla en deuda normativa.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-knowledge-local-note", focus: "evidence", route: "local-note" }),
    expected: { kind: "orient", intentId: "intent-knowledge-local-note", actionId: "inspector:note-add", owner: "inspector", contentId: "content.evidence.dispatch", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.evidence.dispatch", authorityPlane: "method", activeLenses: [] },
    accessibility: ["La nota local no recibe el rótulo RATIFICAR."],
    integrationEvidence: {
      file: "e2e/33-anclas-inspector.spec.ts",
      test: "Nota y RATIFICAR conservan voz, fuente, destino, undo y recibo separados",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.knowledge.evidence-route",
    capabilityId: "cap.evidence.notes-anchors",
    condition: "La deuda corresponde a ratificación normativa y no a una nota local.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-knowledge-evidence", focus: "evidence", route: "normative-ratification" }),
    expected: { kind: "orient", intentId: "intent-knowledge-evidence", actionId: "inspector:anchor-ratify-source", owner: "inspector", contentId: "content.evidence.dispatch", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.evidence.dispatch", authorityPlane: "method", activeLenses: [] },
    accessibility: ["El rótulo RATIFICAR permanece reservado a autoridad normativa pendiente."],
    integrationEvidence: {
      file: "e2e/33-anclas-inspector.spec.ts",
      test: "Nota y RATIFICAR conservan voz, fuente, destino, undo y recibo separados",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.knowledge.handoff-ready",
    capabilityId: "cap.handoff.skill",
    condition: "El contexto de relevo está listo y copiarlo no mutará el modelo.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-knowledge-handoff", focus: "handoff", payloadReady: true }),
    expected: { kind: "orient", intentId: "intent-knowledge-handoff", actionId: "palette:copiar-contexto-skill", owner: "command-palette", contentId: "content.handoff.skill", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.handoff.skill", authorityPlane: "method", actionId: "palette:copiar-contexto-skill", activeLenses: [] },
    accessibility: ["El recibo de portapapeles no se presenta como persistencia."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.view.discovery-source-and-content",
    capabilityId: "cap.discovery.corpus",
    condition: "La consulta exacta encuentra una guía y dos documentos completos locales.",
    snapshot: deriveViewIntent({ intentId: "intent-view-discovery", focus: "discovery", query: "opforja skill flujo", contentMatches: 1, sourceMatches: 2 }),
    expected: { kind: "orient", intentId: "intent-view-discovery", actionId: "tutor:search", owner: "command-palette", contentId: "content.discovery.corpus", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.discovery.corpus", authorityPlane: "method", actionId: "tutor:search", activeLenses: [] },
    accessibility: ["Contenido y fuente completa conservan filas distinguibles."],
    integrationEvidence: {
      file: "e2e/45-tutor-contextual.spec.ts",
      test: "Ctrl+K prioriza una fuente exacta del corpus antes que resultados temáticos",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.view.mobile-readonly",
    capabilityId: "cap.interaction.readonly",
    condition: "El cliente móvil declara editable=false y solo ofrece contexto navegable.",
    snapshot: deriveViewIntent({ intentId: "intent-view-mobile", focus: "mobile-read", editable: false }),
    expected: { kind: "orient", intentId: "intent-view-mobile", actionId: "mobile:read-context", owner: "mobile-read", contentId: "content.interaction.readonly", priority: "optional-teaching", activeLenses: [] },
    expectedContent: { contentId: "content.interaction.readonly", authorityPlane: "method", actionId: "mobile:read-context", activeLenses: [] },
    accessibility: ["No se renderiza una acción imposible en 390 por 844."],
    integrationEvidence: {
      file: "e2e/mobile-readonly.spec.ts",
      test: "Acerca explica lectura con una sola voz y fuentes navegables",
    },
    testCondition: "integration",
  },
  {
    scenarioId: "scenario.nonlive.probabilistic-weights",
    capabilityId: "cap.flow.probabilistic-weights",
    condition: "El caso C sigue programado y el modelo no dispone de pesos persistidos.",
    snapshot: deriveLinkDesignIntent({ intentId: "intent-nonlive-probability", focus: "probabilistic-weights", persistedWeightsAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-probability", reason: "no-candidate" },
    accessibility: ["No aparecen sliders ni una decisión probabilística ficticia."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.ficha-upstream",
    capabilityId: "cap.ficha.upstream",
    condition: "La procedencia upstream está presente y el editor local de ficha no existe.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-nonlive-upstream-ficha", focus: "upstream-ficha", hasUpstreamProvenance: true, localEditorAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-upstream-ficha", reason: "no-candidate" },
    accessibility: ["La lectura no monta controles paralelos."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.outzoom",
    capabilityId: "cap.abstraction.outzoom",
    condition: "La consulta de abstracción confirma que no existe una mutación out-zoom.",
    snapshot: deriveViewIntent({ intentId: "intent-nonlive-outzoom", focus: "outzoom", mutationAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-outzoom", reason: "no-candidate" },
    accessibility: ["La referencia no se presenta como botón habilitado."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.export-pdf",
    capabilityId: "cap.export.pdf-diff-merge",
    condition: "El formato solicitado es PDF y el exportador local no lo implementa.",
    snapshot: deriveExportUnavailableIntent({ intentId: "intent-nonlive-export", format: "pdf" }),
    expected: { kind: "silent", intentId: "intent-nonlive-export", reason: "no-candidate" },
    accessibility: ["No se crea un archivo ni un CTA falso."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.inference",
    capabilityId: "cap.inference.ai",
    condition: "La clasificación automática local no está disponible.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-nonlive-inference", focus: "inference", localInferenceAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-inference", reason: "no-candidate" },
    accessibility: ["No se anuncian resultados inferidos."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.degrade",
    capabilityId: "cap.lifecycle.degrade",
    condition: "No existe transición automática desde Modelo hacia Apunte.",
    snapshot: deriveEntryIntent({ intentId: "intent-nonlive-degrade", focus: "degrade", transitionAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-degrade", reason: "no-candidate" },
    accessibility: ["No se ofrece una degradación destructiva inexistente."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.unadopt",
    capabilityId: "cap.refinement.unadopt",
    condition: "Quitar refinamiento no equivale a una desadopción con identidad preservada.",
    snapshot: deriveRefinementUnavailableIntent({ intentId: "intent-nonlive-unadopt", operation: "unadopt" }),
    expected: { kind: "silent", intentId: "intent-nonlive-unadopt", reason: "no-candidate" },
    accessibility: ["No se anuncia una recuperación que el producto no implementa."],
    testCondition: "unit",
  },
  {
    scenarioId: "scenario.nonlive.certification",
    capabilityId: "cap.certification.automatic",
    condition: "El modelo no produce certificación automática por estar estructuralmente íntegro.",
    snapshot: deriveKnowledgeIntent({ intentId: "intent-nonlive-certification", focus: "certification", automaticCertificationAvailable: false }),
    expected: { kind: "silent", intentId: "intent-nonlive-certification", reason: "no-candidate" },
    accessibility: ["No se anuncia validez certificada."],
    testCondition: "unit",
  },
];
