export const OPCLOUD_BEHAVIORAL_RULES = [
  "ProcessCannotBeConnectedToitselfWithProceduralLinks",
  "AlreadyConnectedWithStructural",
  "AlreadyConnectedWithProcedural",
  "AlreadyConnectedWithStructuralOnTheOtherWay",
  "CantConnectConsumed",
  "CantConnectConsumed2",
  "CantConnectBeforeCreated",
  "CantConnectBeforeCreated2",
  "CantConnectSelfInvocationForInzoomedProcess",
  "CantConnectInzoomedProcessToItsChildrenWithInvocation",
  "ObjectCantConnectToObjectWithProceduralLinks",
  "PreventAggregationBetweenInformaticalToPhysical",
  "AggregationBetweenPhysicaltoInformatical",
  "ExhibitionToPhysical",
  "LegalConsumptionWarning",
  "ProcessToProcess",
  "ObjectToProcess",
  "ProcessToObject",
  "ObjectToObject",
  "StateToObject",
  "ObjectToState",
  "StateToProcess",
  "ProcessToState",
  "StateToState",
  "CannotConnectThingToItsInzoomedFather",
  "ProcessToProcessExceptionsUndertimeOvertime",
  "ProcessToProcessExceptionsOvertime",
  "ProcessToProcessExceptionsUndertime",
  "OnlyOneLevelOfInstantiation",
  "OnlyOneLevelOfInstantiation2",
  "GeneralizationPhysicalToPhysical",
  "CannotConnectFundamentalFromSharedSubModelSource",
  "CannotConnectFundamentalFromSharedSubModelSource2",
  "exhibitionAncestor",
  "OneUnidirectional",
  "SingleInstrumentFromStates",
  "SingleInstrumentFromStates2",
  "InstrumentWithAgentConsistency1",
  "InstrumentWithAgentConsistency2",
] as const;

export const PARIDAD_BEHAVIORAL_DEEP_OPM = {
  AlreadyConnectedWithStructural: "estructural-sin-duplicar",
  ObjectCantConnectToObjectWithProceduralLinks: "procedural-no-objeto-objeto",
  InstrumentWithAgentConsistency1: "instrumento-y-agente-simultaneos",
  InstrumentWithAgentConsistency2: "instrumento-y-agente-simultaneos",
  ProcessToProcessExceptionsUndertimeOvertime: "excepcion-temporal-proceso-proceso",
  ProcessToProcessExceptionsOvertime: "excepcion-temporal-proceso-proceso",
  ProcessToProcessExceptionsUndertime: "excepcion-temporal-proceso-proceso",
} as const satisfies Partial<Record<(typeof OPCLOUD_BEHAVIORAL_RULES)[number], string>>;

export function resumenParidadBehavioralOpcloud() {
  const implementadas = Object.keys(PARIDAD_BEHAVIORAL_DEEP_OPM).length;
  return {
    totalOpcloud: OPCLOUD_BEHAVIORAL_RULES.length,
    implementadas,
    pendientes: OPCLOUD_BEHAVIORAL_RULES.length - implementadas,
  };
}
