import { useZustandCanvasSessionPort } from "../ports/zustandCanvasSessionPort";
import { useZustandModelCommandPort } from "../ports/zustandModelCommandPort";
import { useZustandSelectionPort } from "../ports/zustandSelectionPort";

export function useJointCanvasViewModel() {
  const {
    cambiarOpdActivo,
    moverAparienciaConPuertos,
    actualizarPosicionSimboloEstructural,
    actualizarAnclajesSimboloEstructural,
    cambiarModoPlegadoApariencia,
    extraerParteDePlegado,
    actualizarVerticesEnlace,
    actualizarPosicionLabelEnlace,
    crearEntidadEnCanvas,
    crearAparienciaEntidadEnCanvas,
    crearEnlaceEntreEntidades,
    elegirTipoEnlace,
    iniciarConexionDesdeApariencia,
    cancelarEnlace,
    redimensionarAparienciaEnCanvas,
    reanclarExtremoAccion,
    renombrarEntidadDesdeOpl,
  } = useZustandModelCommandPort();
  const {
    seleccionId,
    seleccionados,
    enlaceSeleccionId,
    idsResaltadosTemporales,
    seleccionarEntidad,
    seleccionarPartePlegada,
    seleccionarEstadoComoExtremo,
    seleccionarEnlace,
    seleccionarGrupoEstructural,
    setSeleccion,
    agregarASeleccion,
    toggleSeleccion,
    vaciarSeleccion,
  } = useZustandSelectionPort();
  const {
    modoEnlace,
    modoCreacion,
    modelo,
    opdActivoId,
    hoverOplRef,
    uiAliasVisibles,
    uiDescripcionesVisibles,
    uiModoImagenGlobal,
    contextoSimulacion,
    alternarModoImagenEntidad,
    abrirModalImagen,
    fijarHoverOpl,
    gridConfig,
    solicitudFitToken,
  } = useZustandCanvasSessionPort();

  return {
    modoEnlace,
    modoCreacion,
    modelo,
    opdActivoId,
    seleccionId,
    seleccionados,
    idsResaltadosTemporales,
    enlaceSeleccionId,
    hoverOplRef,
    uiAliasVisibles,
    uiDescripcionesVisibles,
    uiModoImagenGlobal,
    contextoSimulacion,
    seleccionarEntidad,
    seleccionarPartePlegada,
    seleccionarEstadoComoExtremo,
    seleccionarEnlace,
    seleccionarGrupoEstructural,
    cambiarOpdActivo,
    moverAparienciaConPuertos,
    actualizarPosicionSimboloEstructural,
    actualizarAnclajesSimboloEstructural,
    cambiarModoPlegadoApariencia,
    alternarModoImagenEntidad,
    abrirModalImagen,
    extraerParteDePlegado,
    actualizarVerticesEnlace,
    actualizarPosicionLabelEnlace,
    crearEntidadEnCanvas,
    crearAparienciaEntidadEnCanvas,
    crearEnlaceEntreEntidades,
    elegirTipoEnlace,
    iniciarConexionDesdeApariencia,
    cancelarEnlace,
    fijarHoverOpl,
    setSeleccion,
    agregarASeleccion,
    toggleSeleccion,
    vaciarSeleccion,
    redimensionarAparienciaEnCanvas,
    reanclarExtremoAccion,
    renombrarEntidadDesdeOpl,
    gridConfig,
    solicitudFitToken,
  };
}

export type JointCanvasViewModel = ReturnType<typeof useJointCanvasViewModel>;
