export const MODELO_SLICE_CAPABILITIES = {
  sessionState: [
    "modelo",
    "opdActivoId",
    "mensaje",
    "dirty",
    "dirtyModelo",
    "puedeDeshacer",
    "puedeRehacer",
    "plantillasGuardadas",
    "dialogoPlantillasAbierto",
    "dialogoGuardarPlantillaAbierto",
    "idsResaltadosTemporales",
    "pantallaInicioCerrada",
    "dialogoConfiguracionAbierto",
    "dialogoTraerConectadosAbierto",
    "gridConfig",
    "nuevaCosaPendiente",
    "colisionPendiente",
  ],
  appFlow: [
    "limpiarMensaje",
    "abrirMenuPrincipal",
    "cerrarMenuPrincipal",
    "fijarToolbarMasAbierto",
    "abrirGuardarComo",
    "cerrarGuardarComo",
    "guardarComoLocal",
    "guardarComoLocalConDescripcion",
    "abrirCargarModelo",
    "cerrarCargarModelo",
    "abrirDialogoImportarExportarJson",
    "cerrarDialogoImportarExportarJson",
    "cargarLocalDesdeDialogo",
    "cerrarPantallaInicio",
    "abrirDialogoConfiguracion",
    "cerrarDialogoConfiguracion",
    "abrirDialogoTraerConectados",
    "cerrarDialogoTraerConectados",
    "renombrarModeloActual",
    "abrirDialogoPlantillas",
    "cerrarDialogoPlantillas",
    "abrirDialogoGuardarPlantilla",
    "cerrarDialogoGuardarPlantilla",
    "guardarComoPlantillaConfirmar",
    "insertarPlantillaEnOpdActivo",
    "resaltarTemporalmente",
    "nuevoModelo",
    "activarReadOnly",
  ],
  entityCommands: [
    "crearObjetoDemo",
    "crearProcesoDemo",
    "crearEntidadEnCanvas",
    "confirmarNombreNuevaCosa",
    "descartarNuevaCosaPendiente",
    "crearAparienciaEntidadEnCanvas",
    "resolverColisionReutilizar",
    "resolverColisionRenombrar",
    "resolverColisionCancelar",
    "irAUbicacionColision",
    "fijarModoCreacion",
    "renombrarSeleccionada",
    "crearAtributoEnObjetoSeleccionado",
    "asignarValorAtributoSeleccionado",
    "cambiarTipoValorAtributoSeleccionado",
    "configurarSimulacionAtributoSeleccionado",
    "fijarEsenciaSeleccionada",
    "fijarAfiliacionSeleccionada",
    "redimensionarSeleccionada",
    "redimensionarAparienciaEnCanvas",
    "ajustarSeleccionadaAlTexto",
    "volverSeleccionadaAAuto",
    "alternarModoTamanoSeleccionado",
    "aplicarEstiloSeleccionado",
    "resetearEstiloSeleccionado",
    "editarAliasEntidad",
    "editarUnidadEntidad",
    "editarDescripcionEntidad",
    "abrirModalUrls",
    "cerrarModalUrls",
    "agregarUrlAEntidad",
    "eliminarUrlDeEntidad",
    "reordenarUrlsEntidad",
    "abrirModalImagen",
    "cerrarModalImagen",
    "editarImagenEntidad",
    "quitarImagenEntidad",
    "cambiarModoImagenEntidad",
    "alternarModoImagenEntidad",
    "fijarModoImagenGlobal",
    "fijarLayoutEstadosEntidad",
    "toggleAliasVisibles",
    "toggleDescripcionesVisibles",
  ],
  stateCommands: [
    "agregarEstadosObjeto",
    "agregarEstadoObjeto",
    "agregarEstadoSmart",
    "eliminarEstado",
    "quitarEstadosObjetoSeleccionado",
    "renombrarEstadoSeleccionado",
    "designarEstadoComo",
    "quitarDesignacionEstado",
    "suprimirEstadoPorId",
    "restaurarEstadoPorId",
    "abrirModalDuracion",
    "cerrarModalDuracion",
    "fijarDuracionEstado",
    "quitarDuracionEstado",
    // Paquete "Estados ciudadanos de primera clase" (2026-05-23).
    // Acciones from-selection: leen `estadoSeleccionId` para que atajos y menús
    // contextuales no tengan que pasar el id explícitamente. Multi-batch
    // `designarBatch` aplica designación a varios estados a la vez (todos
    // del mismo objeto propietario por el constraint del slice).
    // Spec: docs/superpowers/specs/2026-05-23-estados-ciudadania-primera-clase-design.md §3.
    "eliminarEstadoSeleccionado",
    "renombrarEstadoSeleccionadoSmart",
    "designarEstadoSeleccionado",
    "quitarDesignacionEstadoSeleccionado",
    "suprimirEstadoSeleccionado",
    "abrirModalDuracionEstadoSeleccionado",
    "agregarEstadoHermanoDeSeleccionado",
    "reordenarEstadoSeleccionado",
    "designarBatch",
  ],
  opdCommands: [
    "descomponerSeleccionada",
    "desplegarSeleccionada",
    "quitarDescomposicionSeleccionada",
    "quitarDespliegueSeleccionado",
    "reasignarEnlaceExternoManual",
    "eliminarOpdDesdeArbol",
    "cambiarOpdActivo",
    "navegarAviso",
  ],
  oplCommands: [
    "seleccionarDesdeOpl",
    "renombrarEntidadDesdeOpl",
    "fijarFiltroOplPorSeleccion",
    "fijarHoverOpl",
    "fijarBusquedaOpl",
    "buscarEnPanelOpl",
    "alternarNumeracionOpl",
    "fijarOplEsenciaVisibilidad",
    "minimizarOpl",
    "restaurarOpl",
    "alternarBloqueOplContraido",
    "mostrarPlaceholderAiOpl",
    "editarEtiquetaEnlaceDesdeOpl",
    "renombrarEstadoDesdeOpl",
    "abrirInspectorEnlaceDesdeOpl",
    "aplicarEdicionOplLibre",
    "copiarOplActualAlPortapapeles",
    "exportarOplActualHtml",
  ],
  canvasCommands: [
    "seleccionarEntidad",
    "seleccionarEstadoComoExtremo",
    "seleccionarEnlace",
    "seleccionarGrupoEstructural",
    "deshacer",
    "rehacer",
    "moverEntidad",
    "moverApariencia",
    "moverAparienciaConPuertos",
    "actualizarPosicionSimboloEstructural",
    "actualizarAnclajesSimboloEstructural",
    "resetearAnclajesSimboloEstructural",
    "toggleGrid",
    "fijarGridConfig",
    "alinearSeleccion",
    "distribuirSeleccion",
    "aplicarLayoutSugerido",
    "reordenarSubprocesoEnTimeline",
    "actualizarVerticesEnlace",
    "actualizarPosicionLabelEnlace",
    "traerConectadosSeleccionado",
    "traerEnlacesEntreSeleccionadas",
    "ocultarAparienciaSeleccionada",
    "cambiarModoPlegadoSeleccionado",
    "cambiarModoPlegadoApariencia",
    "fijarModoPlegadoApariencia",
    "cambiarOrdenPartesSeleccionado",
    "fijarOrdenPartesApariencia",
    "seleccionarPartePlegada",
    "extraerParteDePlegado",
    "extraerTodasLasPartesSeleccionadas",
    "reinsertarParteExtraidaSeleccionada",
    "quitarSemiplegadoEstructuralSeleccionado",
    "quitarPlegadoCompletoEstructuralSeleccionado",
    "traerAgregacionesInzoomFaltantesSeleccionadas",
  ],
  linkCommands: [
    "elegirTipoEnlace",
    "iniciarConexionDesdeApariencia",
    "crearEnlaceEntreEntidades",
    "cancelarEnlace",
    "ajustarMultiplicidadSeleccionada",
    "apuntarExtremoEnlaceSeleccionado",
    "reanclarEnlaceExternoDerivado",
    "splitEffectSeleccionado",
    "volverEnlaceExternoDerivadoAAutomatico",
    "alternarOperadorAbanicoSeleccionado",
    "crearAbanicoDesdeEnlaceSeleccionado",
    "quitarRamaDeAbanicoSeleccionado",
    "disolverAbanicoSeleccionado",
    "crearAutoInvocacionSeleccionada",
    "aplicarModificadorEnlaceSeleccionado",
    "aplicarSubtipoModificadorEnlaceSeleccionado",
    "quitarModificadorEnlaceSeleccionado",
    "definirProbabilidadEventoSeleccionada",
    "definirDemoraInvocacionSeleccionada",
    "definirBackwardTagSeleccionado",
    "definirRequisitosEnlaceSeleccionado",
    "definirTasaEnlaceSeleccionada",
    "definirTiempoExcepcionEnlaceSeleccionado",
    "moverPuertoEnlaceSeleccionado",
    "renombrarEtiquetaEnlaceSeleccionado",
    "definirRutaEtiquetaSeleccionada",
  ],
} as const;

type CapabilityKey<T> = T[keyof T] extends readonly (infer K)[] ? K : never;

export type ModeloSliceKey = CapabilityKey<typeof MODELO_SLICE_CAPABILITIES>;

export const MODELO_SLICE_KEYS = Object.values(MODELO_SLICE_CAPABILITIES).flat() as ModeloSliceKey[];

export const MODELO_SLICE_OPTIONAL_INITIAL_KEYS = ["gridConfig"] as const satisfies readonly ModeloSliceKey[];
