import {useState} from 'preact/hooks';
import type {Modelo,Ref,Enlace,Multiplicidad,UnidadTiempo,Designacion} from '../nucleo/tipos';
import {extremos} from '../nucleo/tipos';
import {indice,describirEnlace} from '../nucleo/indice';
import {MATRIZ} from '../nucleo/matriz';
import {aplicarAccion} from '../nucleo/operaciones';
import type {Accion} from '../nucleo/operaciones';
import {COMANDOS} from '../editor/comandos';
import {escena} from '../opd/escena';
import {generarBloque} from '../opl/generar';
import {proyectar} from '../nucleo/proyeccion';
import type {DatosRanura} from './Editor';
import {irRefs,contieneRef,perdidasAccion} from './ArbolOpd';
import {Dialogo} from './Dialogo';
export {perdidasAccion} from './ArbolOpd';
export function Inspector(p:DatosRanura){
 const m=p.estado.modelo!,s=p.estado.seleccion,idx=indice(m),[decision,decidir]=useState<Accion|null>(null),[error,fallar]=useState('');
 const ejecutar=(a:Accion)=>{const r=p.editor.ejecutar(a);if(!r.ok)fallar(`${r.rechazo.regla}: ${r.rechazo.mensaje}`);else {fallar('');if(a.op==='eliminarRefinamiento'){const o=m.opds[a.args.opd];if(o&&o.tipo!=='raiz')p.editor.navegar(o.padre);}}return r.ok;};
 const boton=(texto:string,a:Accion,peligrosa=false)=>{const r=aplicarAccion(m,a),razon=p.estado.modo!=='edicion'?'El modelo está en modo navegación.':!r.ok?r.rechazo.mensaje:null;return <button disabled={!!razon} title={razon??''} onClick={()=>{if(peligrosa)decidir(a);else ejecutar(a);}}>{texto}</button>;};
 const campo=(nombre:string,valor:string,accion:(v:string)=>Accion,clase='text')=>{const previo=aplicarAccion(m,accion(nombre==='Valor de atributo'?(valor||'valor'):valor)),razon=p.estado.modo!=='edicion'?'El modelo está en modo navegación.':!previo.ok?previo.rechazo.mensaje:null;return <label>{nombre}<input key={`${nombre}:${valor}`} type={clase} defaultValue={valor} disabled={!!razon} title={razon??''} onInput={e=>{const r=aplicarAccion(m,accion(e.currentTarget.value));fallar(r.ok?'':`${r.rechazo.regla}: ${r.rechazo.mensaje}`);}} onBlur={e=>{if(e.currentTarget.value!==valor)ejecutar(accion(e.currentTarget.value));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>{razon&&<small>{razon}</small>}</label>;};
 const opciones=(nombre:string,valor:string,vs:readonly string[],accion:(v:string)=>Accion)=><label>{nombre}<select aria-label={nombre} value={valor} disabled={p.estado.modo!=='edicion'} onChange={e=>ejecutar(accion(e.currentTarget.value))}>{vs.map(v=>{const r=aplicarAccion(m,accion(v));return <option value={v} disabled={!r.ok} title={!r.ok?r.rechazo.mensaje:''}>{idx.estadoDe.has(v)?(()=>{const z=idx.estadoDe.get(v)!,o=m.cosas[z.objeto]!;return o.tipo==='objeto'?o.estados[z.posicion]!.nombre:v;})():v||'Ninguno'}</option>;})}</select></label>;
 const cantidad=s.cosas.length+s.estados.length+s.enlaces.length+s.abanicos.length+(s.simbolo?1:0),c=cantidad===1?m.cosas[s.cosas[0]??'']:undefined,estado=cantidad===1?idx.estadoDe.get(s.estados[0]??''):undefined,e=cantidad===1?m.enlaces[s.enlaces[0]??'']:undefined,fan=cantidad===1?m.abanicos[s.abanicos[0]??'']:undefined,z=s.simbolo?escena(m,p.estado.opd).simbolos.find(x=>x.clave===s.simbolo):undefined;
 const enlaces=c?idx.enlacesDeCosa.get(c.id)??[]:estado?idx.enlacesDeEstado.get(s.estados[0]!)??[]:[];
 function estadosLink(e:Enlace){const f=MATRIZ[e.tipo],x=extremos(e),estados=(id:string)=>{const c=m.cosas[id];return c?.tipo==='objeto'?c.estados:[];};const selector=(titulo:string,dueño:string,v:string|null,cambio:(id:string|null)=>Accion)=>opciones(titulo,v??'',['',...estados(dueño).map(x=>x.id)],id=>cambio(id||null));
  if(f.estados==='objeto'&&'objeto'in e)return selector('Estado',e.objeto,'estado'in e?e.estado??null:null,id=>({op:'fijarEstados',args:{enlace:e.id,estados:{estado:id}}}));
  if(e.tipo==='efecto')return <>{selector('Entrada',e.objeto,e.entrada??null,id=>({op:'fijarEstados',args:{enlace:e.id,estados:{entrada:id,salida:e.salida??null}}}))}{selector('Salida',e.objeto,e.salida??null,id=>({op:'fijarEstados',args:{enlace:e.id,estados:{entrada:e.entrada??null,salida:id}}}))}</>;
  if(f.estados==='origenDestino'||f.estados==='soloOrigen'||f.estados==='simetrico'){const origen='estadoOrigen'in e?e.estadoOrigen:'estados'in e&&e.tipo==='reciproco'?e.estados?.origen:undefined,destino='estadoDestino'in e?e.estadoDestino:e.tipo==='reciproco'?e.estados?.destino:undefined;return <>{selector('Estado origen',x.origen,origen??null,id=>({op:'fijarEstados',args:{enlace:e.id,estados:{origen:id,destino:destino??null}}}))}{f.estados!=='soloOrigen'&&selector('Estado destino',x.destino,destino??null,id=>({op:'fijarEstados',args:{enlace:e.id,estados:{origen:origen??null,destino:id}}}))}</>;}
  if(e.tipo==='generalizacion'){const o=estados(e.refinable),d=estados(e.refinador);return <>{boton('Sin especialización de estado',{op:'fijarEstados',args:{enlace:e.id,estados:{generalizacion:null}}})}{o.length&&d.length?<label>Especialización<select value={e.estados?`${e.estados.general}|${e.estados.especializacion}`:''} disabled={p.estado.modo!=='edicion'} onChange={v=>{const[a,b]=v.currentTarget.value.split('|');if(a&&b)ejecutar({op:'fijarEstados',args:{enlace:e.id,estados:{generalizacion:{general:a,especializacion:b}}}});}}><option value="">Ninguna</option>{o.flatMap(a=>d.map(b=>{const r=aplicarAccion(m,{op:'fijarEstados',args:{enlace:e.id,estados:{generalizacion:{general:a.id,especializacion:b.id}}}});return<option disabled={!r.ok} value={`${a.id}|${b.id}`}>{a.nombre} → {b.nombre}</option>;}))}</select></label>:null}</>;}
  return null;
 }
 const previo=decision?perdidasAccion(m,decision):null;
 return <div class="inspector"><h2>Propiedades</h2>{!cantidad&&<p>Selecciona una cosa, estado, enlace o grupo.</p>}{cantidad>1&&<><p>{cantidad} elementos seleccionados.</p>{s.cosas.length>0&&<>{boton('Quitar del OPD',{op:'quitarDeOpd',args:{opd:p.estado.opd,cosas:s.cosas}},true)}{boton('Eliminar del modelo',{op:'eliminarCosas',args:{cosas:s.cosas}},true)}</>}{s.enlaces.length>0&&<>{boton('Eliminar enlaces',{op:'eliminarEnlaces',args:{enlaces:s.enlaces}},true)}{(['XOR','OR']as const).map(operador=>boton(`Formar ${operador}`,{op:'formarAbanico',args:{operador,enlaces:s.enlaces}}))}</>}</>}
 {c&&<><h3>{c.nombre}</h3><small>{c.id}</small>{campo('Nombre',c.nombre,v=>({op:'renombrarCosa',args:{cosa:c.id,nombre:v}}))}{opciones('Tipo',c.tipo,['objeto','proceso'],v=>({op:'cambiarTipoCosa',args:{cosa:c.id,tipo:v as 'objeto'|'proceso'}}))}{opciones('Esencia',c.esencia,['fisica','informacional'],v=>({op:'fijarEsencia',args:{cosa:c.id,esencia:v as 'fisica'|'informacional'}}))}{opciones('Afiliación',c.afiliacion,['sistemica','ambiental'],v=>({op:'fijarAfiliacion',args:{cosa:c.id,afiliacion:v as 'sistemica'|'ambiental'}}))}{opciones('Género',c.genero??'m',['m','f'],v=>({op:'fijarGenero',args:{cosa:c.id,genero:v as 'm'|'f'}}))}{campo('Descripción',c.descripcion??'',v=>({op:'fijarDescripcion',args:{cosa:c.id,texto:v||null}}))}
 {c.tipo==='proceso'&&<fieldset><legend>Duración</legend>{(['min','esperada','max']as const).map(k=>campo(k==='min'?'Mínima':k==='max'?'Máxima':'Esperada',String(c.duracion?.[k]??''),v=>({op:'fijarDuracion',args:{proceso:c.id,duracion:Object.fromEntries(Object.entries({...c.duracion,[k]:v===''?undefined:Number(v)}).filter(([,x])=>x!==undefined))}}),'number'))}{opciones('Unidad',c.duracion?.unidad??'',['','ms','sec','min','hour','day','week','month','year'],v=>({op:'fijarDuracion',args:{proceso:c.id,duracion:v?{...c.duracion,unidad:v as UnidadTiempo}:Object.fromEntries(Object.entries(c.duracion??{}).filter(([k])=>k!=='unidad'))}}))}{boton('Quitar duración',{op:'fijarDuracion',args:{proceso:c.id,duracion:null}})}</fieldset>}
 {c.tipo==='objeto'&&<>{campo('Valor de atributo',c.valor??'',v=>({op:'fijarValor',args:{objeto:c.id,valor:v||null}}))}<h4>Estados</h4><ul>{c.estados.map(x=><li><button onClick={()=>irRefs(p.editor,[{tipo:'estado',id:x.id}],p.estado.opd)}>{x.nombre}</button></li>)}</ul><button disabled={p.estado.modo!=='edicion'} onClick={()=>p.editor.solicitar({k:'estado',opcion:'crear',refs:[{tipo:'cosa',id:c.id}]})}>Añadir estado</button></>}
 <div class="acciones-propiedades">{c.tipo==='proceso'&&<button disabled={p.estado.modo!=='edicion'} onClick={()=>COMANDOS.find(x=>x.id==='descomponer')!.ejecutar(p.editor)}>Descomponer</button>}<button disabled={p.estado.modo!=='edicion'} onClick={()=>p.editor.solicitar({k:'desplegar',refs:[{tipo:'cosa',id:c.id}]})}>Desplegar</button>{Object.values(idx.refinamientosDe.get(c.id)??{}).map(opd=><span><button onClick={()=>p.editor.navegar(opd)}>Ir al refinamiento</button>{boton('Eliminar refinamiento',{op:'eliminarRefinamiento',args:{opd}},true)}</span>)}{boton('Quitar del OPD',{op:'quitarDeOpd',args:{opd:p.estado.opd,cosas:[c.id]}},true)}{boton('Eliminar del modelo',{op:'eliminarCosas',args:{cosas:[c.id]}},true)}</div></>}
 {estado&&(()=>{const o=m.cosas[estado.objeto]!,id=s.estados[0]!,x=o.tipo==='objeto'?o.estados[estado.posicion]!:null;if(!x||o.tipo!=='objeto')return null;return<><h3>{o.nombre} · {x.nombre}</h3>{campo('Nombre',x.nombre,v=>({op:'renombrarEstado',args:{estado:id,nombre:v}}))}{(['inicial','final','porDefecto','current']as Designacion[]).map(k=><label><input type="checkbox" checked={k==='porDefecto'?o.porDefecto===id:k==='current'?o.current===id:!!x[k]} disabled={p.estado.modo!=='edicion'} onChange={v=>ejecutar({op:'designar',args:{estado:id,designacion:k,activa:v.currentTarget.checked}})}/>{k==='current'?'Current declarado':k}</label>)}<label><input type="checkbox" checked={!!x.suprimido} disabled={p.estado.modo!=='edicion'} onChange={v=>ejecutar({op:'suprimirEstado',args:{estado:id,opd:null,activa:v.currentTarget.checked}})}/>Suprimido globalmente</label><label><input type="checkbox" checked={m.opds[p.estado.opd]?.apariciones[o.id]?.ocultos?.includes(id)??false} disabled={p.estado.modo!=='edicion'} onChange={v=>ejecutar({op:'suprimirEstado',args:{estado:id,opd:p.estado.opd,activa:v.currentTarget.checked}})}/>Suprimido en este OPD</label>{boton('Subir estado',{op:'moverEstado',args:{estado:id,indice:Math.max(0,estado.posicion-1)}})}{boton('Bajar estado',{op:'moverEstado',args:{estado:id,indice:Math.min(o.estados.length-1,estado.posicion+1)}})}{boton('Eliminar estado',{op:'eliminarEstado',args:{estado:id}},true)}</>;})()}
 {e&&<><h3>{describirEnlace(m,e)}</h3><small>{e.id}</small><button disabled={p.estado.modo!=='edicion'} onClick={()=>p.editor.solicitar({k:'tipo',refs:[{tipo:'enlace',id:e.id}]})}>Cambiar tipo</button>{opciones('Control','control'in e?e.control??'':'',['','e','c'],v=>({op:'fijarControl',args:{enlace:e.id,control:v?v as 'e'|'c':null}}))}{campo('Ruta','ruta'in e?e.ruta??'':'',v=>({op:'fijarRuta',args:{enlace:e.id,ruta:v||null}}))}{campo('Etiqueta','etiqueta'in e?e.etiqueta??'':'',v=>({op:'fijarEtiqueta',args:{enlace:e.id,etiqueta:v||null}}))}{'inversa'in e&&campo('Etiqueta inversa',e.inversa,v=>({op:'fijarEtiqueta',args:{enlace:e.id,etiqueta:e.etiqueta,inversa:v||null}}))}{(MATRIZ[e.tipo].mult==='ambos'?['origen','destino']:MATRIZ[e.tipo].mult==='ninguno'?[]:[MATRIZ[e.tipo].mult]).map(rol=>opciones(`Multiplicidad ${rol}`,'mult'in e?e.mult??'':rol==='origen'&&'multOrigen'in e?e.multOrigen??'':rol==='destino'&&'multDestino'in e?e.multDestino??'':'',['','?','*','+'],v=>({op:'fijarMultiplicidad',args:{enlace:e.id,extremo:rol as 'objeto'|'refinador'|'origen'|'destino',valor:v?v as Multiplicidad:null}})))}{estadosLink(e)}<p class="vista-opl">{generarBloque(m,p.estado.opd).filter(l=>l.hechos.includes(e.id)).map(l=>l.texto).join('\n')}</p>{boton('Eliminar enlace',{op:'eliminarEnlaces',args:{enlaces:[e.id]}},true)}</>}
 {fan&&<><h3>Abanico {fan.operador}</h3>{opciones('Operador',fan.operador,['XOR','OR'],v=>({op:'fijarOperador',args:{abanico:fan.id,operador:v as 'XOR'|'OR'}}))}{opciones('Control',m.enlaces[fan.enlaces[0]??'']&&'control'in m.enlaces[fan.enlaces[0]!]!?(m.enlaces[fan.enlaces[0]!] as {control?:string}).control??'':'',['','e','c'],v=>({op:'fijarControlAbanico',args:{abanico:fan.id,control:v?v as 'e'|'c':null}}))}<ul>{fan.enlaces.map(id=><li><button onClick={()=>irRefs(p.editor,[{tipo:'enlace',id}],p.estado.opd)}>{describirEnlace(m,m.enlaces[id]!)}</button>{boton('Quitar rama',{op:'quitarRama',args:{abanico:fan.id,enlace:id}})}</li>)}</ul>{boton('Disolver grupo',{op:'disolverAbanico',args:{abanico:fan.id}})}</>}
 {z&&<><h3>{z.relacion} de {m.cosas[z.refinable]?.nombre}</h3>{z.relacion!=='clasificacion'&&boton(z.incompleta?'Marcar completa':'Marcar incompleta',{op:'fijarIncompleta',args:{cosa:z.refinable,relacion:z.relacion,activa:!z.incompleta}})}<ul>{z.ramas.map(id=><li><button onClick={()=>irRefs(p.editor,[{tipo:'enlace',id}],p.estado.opd)}>{describirEnlace(m,m.enlaces[id]!)}</button></li>)}</ul></>}
 {enlaces.length>0&&<details open><summary>Enlaces ({enlaces.length})</summary><ul>{enlaces.map(id=><li key={id} onKeyDown={ev=>{if(ev.key==='Delete'&&p.estado.modo==='edicion'){ev.preventDefault();decidir({op:'eliminarEnlaces',args:{enlaces:[id]}});}}}><button onClick={()=>irRefs(p.editor,[{tipo:'enlace',id}],contieneRef(m,p.estado.opd,{tipo:'enlace',id})?p.estado.opd:undefined)}>{describirEnlace(m,m.enlaces[id]!)}</button><p class="enlace-oracion">{Object.keys(m.opds).flatMap(opd=>generarBloque(m,opd).filter(l=>l.hechos.includes(id))).map(l=>l.texto).filter((x,i,a)=>a.indexOf(x)===i).join(' · ')}</p><small>{Object.keys(m.opds).filter(opd=>proyectar(m,opd).enlaces.some(x=>x.hechos.includes(id))).map(id=>idx.etiqueta.get(id)).join(', ')} · {id}</small>{boton('Eliminar',{op:'eliminarEnlaces',args:{enlaces:[id]}},true)}</li>)}</ul></details>}
 {error&&<p role="alert">{error}</p>}{decision&&previo&&<Dialogo titulo="Confirmar pérdidas" cerrar={()=>decidir(null)} acciones={[{texto:'Cancelar',hacer:()=>decidir(null)},{texto:'Confirmar',peligrosa:true,deshabilitada:!previo.r.ok,hacer:()=>{if(ejecutar(decision))decidir(null);}}]}>{previo.r.ok?<><p>Esta operación elimina:</p><ul>{previo.perdidas.map(x=><li>{x}</li>)}</ul>{!previo.perdidas.length&&<p>Los demás hechos conservan su identidad.</p>}{previo.conservados.length>0&&<><p>Se conservan:</p><ul>{previo.conservados.map(x=><li>{x}</li>)}</ul></>}</>:<p role="alert">{previo.r.rechazo.mensaje}</p>}</Dialogo>}</div>;
}
