// Estilos compartidos del Inspector y sus sub-componentes
// (InspectorEntidad, InspectorEnlace y la rama vacia inline). Vive en
// archivo aparte para evitar duplicar tokens visuales y dejar los
// componentes puros de markup.
export const inspectorStyles = {
  panel: {
    minWidth: 0,
    overflow: "auto",
    padding: "14px",
    background: "#ffffff",
    borderLeft: "1px solid #d9e0ea",
  },
  empty: {
    color: "#667085",
    fontSize: "13px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    marginBottom: "16px",
  },
  kind: {
    color: "#1f2937",
    fontSize: "13px",
    fontWeight: 700,
  },
  id: {
    color: "#667085",
    fontSize: "12px",
  },
  field: {
    display: "grid",
    gap: "6px",
    marginBottom: "14px",
  },
  label: {
    color: "#475467",
    fontSize: "12px",
    fontWeight: 700,
  },
  summary: {
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    gap: "8px",
    marginBottom: "16px",
    padding: "10px",
    border: "1px solid #d9e0ea",
    borderRadius: "4px",
    color: "#1f2937",
    fontSize: "13px",
    fontWeight: 600,
  },
  arrow: {
    color: "#586D8C",
    fontWeight: 700,
  },
  input: {
    width: "100%",
    height: "34px",
    padding: "0 10px",
    border: "1px solid #c8d2df",
    borderRadius: "4px",
    color: "#1f2937",
    background: "#ffffff",
    outlineColor: "#586D8C",
  },
  segmented: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
  },
  segment: {
    height: "32px",
    border: "1px solid #c8d2df",
    borderRadius: "4px",
    background: "#f9fbfd",
    color: "#475467",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
  },
  segmentActive: {
    height: "32px",
    border: "1px solid #586D8C",
    borderRadius: "4px",
    background: "#e8eef5",
    color: "#1f2937",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
  },
  menu: {
    marginBottom: "10px",
  },
  menuSummary: {
    width: "100%",
    minHeight: "32px",
    padding: "8px 10px",
    border: "1px solid #147aa5",
    borderRadius: "4px",
    background: "#e8f7ff",
    color: "#0f5f82",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
    listStylePosition: "inside",
  },
  menuItems: {
    display: "grid",
    gap: "6px",
    paddingTop: "8px",
  },
  menuButton: {
    width: "100%",
    minHeight: "32px",
    padding: "0 10px",
    border: "1px solid #c8d2df",
    borderRadius: "4px",
    background: "#f9fbfd",
    color: "#1f2937",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
    textAlign: "left",
  },
  primaryButton: {
    width: "100%",
    height: "32px",
    marginBottom: "10px",
    border: "1px solid #147aa5",
    borderRadius: "4px",
    background: "#e8f7ff",
    color: "#0f5f82",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
  },
  secondaryButton: {
    width: "100%",
    height: "32px",
    marginBottom: "10px",
    border: "1px solid #c8d2df",
    borderRadius: "4px",
    background: "#f9fbfd",
    color: "#475467",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
  },
  dangerButton: {
    width: "100%",
    height: "32px",
    border: "1px solid #d92d20",
    borderRadius: "4px",
    background: "#fff5f5",
    color: "#b42318",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
  },
  oplEditButton: {
    width: "100%",
    height: "32px",
    marginTop: "8px",
    border: "1px solid #586D8C",
    borderRadius: "4px",
    background: "#f0f3f9",
    color: "#334155",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 700,
  },
} satisfies Record<string, preact.JSX.CSSProperties>;
