// Source: decompiled/deobfuscated.js
// Original path: ./src/app/modules/Settings/graph-insights/graph-insights-instructions-dialog.component.ts
// Extracted by opm-extracted/tools/extract.mjs

let GraphInsightsInstructionsDialogComponent = /*#__PURE__*/(() => {
  class GraphInsightsInstructionsDialogComponent {
    constructor(dialogRef) {
      this.dialogRef = dialogRef;
    }
    close() {
      this.dialogRef.close();
    }
    static #_ = (() => this.ɵfac = function GraphInsightsInstructionsDialogComponent_Factory(__ngFactoryType__) {
      return new (__ngFactoryType__ || GraphInsightsInstructionsDialogComponent)(core /* ɵɵdirectiveInject */.rXU(MatDialogRef));
    })();
    static #_2 = (() => this.ɵcmp = /*@__PURE__*/core /* ɵɵdefineComponent */.VBU({
      type: GraphInsightsInstructionsDialogComponent,
      selectors: [["opcloud-graph-insights-instructions-dialog"]],
      decls: 358,
      vars: 0,
      consts: [[1, "gi-instr-shell"], [1, "gi-instr-title-wrap"], [1, "gi-instr-title"], [1, "gi-instr-subtitle"], [1, "gi-instr-scroll"], [1, "note"], [1, "gi-instr-footer"], ["mat-raised-button", "", "color", "primary", "type", "button", 1, "gi-instr-close-btn", 3, "click"]],
      template: function GraphInsightsInstructionsDialogComponent_Template(rf, ctx) {
        if (rf & 1) {
          core /* ɵɵelementStart */.j41(0, "div", 0)(1, "div", 1)(2, "h2", 2);
          core /* ɵɵtext */.EFF(3, "Graph Insights — User Guide");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(4, "p", 3);
          core /* ɵɵtext */.EFF(5, " How this page works, what each control means, and how to interpret results in OPM terms. ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(6, "div", 4)(7, "h3");
          core /* ɵɵtext */.EFF(8, "What is Graph Insights?");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(9, "p")(10, "strong");
          core /* ɵɵtext */.EFF(11, "Graph Insights");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(12, " turns your ");
          core /* ɵɵelementStart */.j41(13, "em");
          core /* ɵɵtext */.EFF(14, "currently loaded");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(15, " OPCloud OPM model into a ");
          core /* ɵɵelementStart */.j41(16, "strong");
          core /* ɵɵtext */.EFF(17, "temporary graph");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(18, " inside the browser. Analyses run entirely on the frontend (Graphology). There is ");
          core /* ɵɵelementStart */.j41(19, "strong");
          core /* ɵɵtext */.EFF(20, "no persistent graph database");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(21, ", no server-side analytics for these features, and no synchronization with an external graph store. When you leave the page or refresh the snapshot, the in-memory graph is discarded unless you build it again. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(22, "p", 5);
          core /* ɵɵtext */.EFF(23, " The graph is built from the same kind of ");
          core /* ɵɵelementStart */.j41(24, "strong");
          core /* ɵɵtext */.EFF(25, "flattened");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(26, " view of the model used elsewhere in OPCloud for analysis exports: relations appear as directed links between ");
          core /* ɵɵelementStart */.j41(27, "strong");
          core /* ɵɵtext */.EFF(28, "objects");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(29, ", ");
          core /* ɵɵelementStart */.j41(30, "strong");
          core /* ɵɵtext */.EFF(31, "processes");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(32, ", and ");
          core /* ɵɵelementStart */.j41(33, "strong");
          core /* ɵɵtext */.EFF(34, "states");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(35, " where the flattening algorithm exposes them. This page walks ");
          core /* ɵɵelementStart */.j41(36, "strong");
          core /* ɵɵtext */.EFF(37, "visual links");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(38, " on the temporary flattened OPD from ");
          core /* ɵɵelementStart */.j41(39, "code");
          core /* ɵɵtext */.EFF(40, "opmModel.flattening(false)");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(41, " (same family as “Download Model Triplets”), not by parsing RDF/Turtle. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(42, "p", 5)(43, "strong");
          core /* ɵɵtext */.EFF(44, "RDF export");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(45, " (");
          core /* ɵɵelementStart */.j41(46, "code");
          core /* ɵɵtext */.EFF(47, "OpmRdfService");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(48, ") serializes the logical model to Turtle with ");
          core /* ɵɵelementStart */.j41(49, "code");
          core /* ɵɵtext */.EFF(50, "opm:");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(51, " link individuals; Graph Insights does ");
          core /* ɵɵelementStart */.j41(52, "em");
          core /* ɵɵtext */.EFF(53, "not");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(54, " consume that file. Relation names in the graph use the same link-type vocabulary as RDF export, but the pipelines are separate. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(55, "h3");
          core /* ɵɵtext */.EFF(56, "Build Graph Snapshot & Refresh");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(57, "ul")(58, "li")(59, "strong");
          core /* ɵɵtext */.EFF(60, "Build Graph Snapshot");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(61, " — Ensures the normalized graph for the ");
          core /* ɵɵelementStart */.j41(62, "em");
          core /* ɵɵtext */.EFF(63, "currently selected projection");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(64, " is available. If this projection was already built in this session, it may reuse the cached snapshot. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(65, "li")(66, "strong");
          core /* ɵɵtext */.EFF(67, "Refresh from Current Model");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(68, " — Forces a full rebuild from the ");
          core /* ɵɵelementStart */.j41(69, "em");
          core /* ɵɵtext */.EFF(70, "live");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(71, " model state. Use this after edits in OPCloud so analyses reflect your latest links and elements. ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(72, "h3");
          core /* ɵɵtext */.EFF(73, "Projection (dropdown)");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(74, "p");
          core /* ɵɵtext */.EFF(75, " A ");
          core /* ɵɵelementStart */.j41(76, "strong");
          core /* ɵɵtext */.EFF(77, "projection");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(78, " is a filter on which OPM link types are included in the graph. The same logical model can look different depending on projection; counts, paths, and “suspicious” patterns all apply to the ");
          core /* ɵɵelementStart */.j41(79, "em");
          core /* ɵɵtext */.EFF(80, "selected");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(81, " projection only. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(82, "ul")(83, "li")(84, "strong");
          core /* ɵɵtext */.EFF(85, "Semantic (default)");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(86, " — Structural relations (e.g. aggregation, exhibition, generalization, instantiation) ");
          core /* ɵɵelementStart */.j41(87, "em");
          core /* ɵɵtext */.EFF(88, "and");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(89, " procedural relations (e.g. agent, instrument, consumption, result, effect, invocation, exceptions, tagged relations). A balanced default for general exploration. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(90, "li")(91, "strong");
          core /* ɵɵtext */.EFF(92, "Structural");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(93, " — Emphasizes hierarchy and typing-style links: aggregation, exhibition, generalization, instantiation. Good for decomposition, specialization, and structure-focused questions. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(94, "li")(95, "strong");
          core /* ɵɵtext */.EFF(96, "Behavioral / Procedural");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(97, " — Procedural links only (agents, instruments, consumption, result, effect, invocation, exceptions, unidirectional/bidirectional tagged links). Good for flow and process participation views. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(98, "li")(99, "strong");
          core /* ɵɵtext */.EFF(100, "Full");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(101, " — Same relation set as the semantic default in the current implementation (all of the above categories). Kept for clarity and future extension if projections diverge. ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(102, "h3");
          core /* ɵɵtext */.EFF(103, "Summary cards (top row)");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(104, "p");
          core /* ɵɵtext */.EFF(105, "High-level metrics for the ");
          core /* ɵɵelementStart */.j41(106, "strong");
          core /* ɵɵtext */.EFF(107, "current projection");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(108, ":");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(109, "ul")(110, "li")(111, "strong");
          core /* ɵɵtext */.EFF(112, "Total Nodes / Total Edges");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(113, " — Count of elements and relations in the snapshot graph.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(114, "li")(115, "strong");
          core /* ɵɵtext */.EFF(116, "Objects / Processes / States");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(117, " — Breakdown by normalized element kind.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(118, "li")(119, "strong");
          core /* ɵɵtext */.EFF(120, "Isolated Elements");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(121, " — Nodes with degree zero (no links in this projection).");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(122, "li")(123, "strong");
          core /* ɵɵtext */.EFF(124, "Connected Components");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(125, " — Number of weakly connected regions if you treat the graph as undirected for component counting (used internally for this metric).");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(126, "li")(127, "strong");
          core /* ɵɵtext */.EFF(128, "High-Risk Hubs");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(129, " — Count of nodes with very high degree (heuristic threshold); not a formal OPM quality gate.");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(130, "h3");
          core /* ɵɵtext */.EFF(131, "Left panel — Quick Queries");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(132, "ul")(133, "li")(134, "strong");
          core /* ɵɵtext */.EFF(135, "Element");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(136, " — Choose any node from the snapshot (label and kind are shown in the list). ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(137, "li")(138, "strong");
          core /* ɵɵtext */.EFF(139, "Analyze Neighborhood");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(140, " — Shows direct neighbors, grouped by relation type and by neighbor kind, plus a short OPM-oriented explanation (e.g. how many objects/processes/states are adjacent). ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(141, "h3");
          core /* ɵɵtext */.EFF(142, "Left panel — Path Analysis");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(143, "ul")(144, "li")(145, "strong");
          core /* ɵɵtext */.EFF(146, "Treat relations as undirected");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(147, " — When ");
          core /* ɵɵelementStart */.j41(148, "strong");
          core /* ɵɵtext */.EFF(149, "on");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(150, " (default), path search can traverse a link in either direction, which often matches “connected on the diagram” intuition. When ");
          core /* ɵɵelementStart */.j41(151, "strong");
          core /* ɵɵtext */.EFF(152, "off");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(153, ", only ");
          core /* ɵɵelementStart */.j41(154, "em");
          core /* ɵɵtext */.EFF(155, "outgoing");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(156, " directed edges are followed (strict causal/flow direction in the flattened graph). If no path appears, try undirected mode or another projection. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(157, "li")(158, "strong");
          core /* ɵɵtext */.EFF(159, "Source / Target");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(160, " — Start and end nodes for path finding. Changing either re-runs path queries and refreshes the graph preview highlights when those nodes appear in the sampled preview. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(161, "li")(162, "strong");
          core /* ɵɵtext */.EFF(163, "Max Depth");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(164, " — Maximum number of steps for ");
          core /* ɵɵelementStart */.j41(165, "em");
          core /* ɵɵtext */.EFF(166, "enumerating alternative simple paths");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(167, " (bounded DFS). Does not shorten the true ");
          core /* ɵɵelementStart */.j41(168, "em");
          core /* ɵɵtext */.EFF(169, "shortest");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(170, " path; it limits extra paths only. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(171, "li")(172, "strong");
          core /* ɵɵtext */.EFF(173, "Path Limit");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(174, " — Maximum number of alternative simple paths returned (protects the UI from combinatorial explosion). ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(175, "li")(176, "strong");
          core /* ɵɵtext */.EFF(177, "Run Path Queries");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(178, " — Refreshes shortest-path and bounded simple-path results for the current settings. ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(179, "h3");
          core /* ɵɵtext */.EFF(180, "Left panel — Centrality & Connectivity");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(181, "ul")(182, "li")(183, "strong");
          core /* ɵɵtext */.EFF(184, "Recompute Importance");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(185, " — Refreshes degree-/betweenness-/PageRank-assisted rankings and the “Important Elements” table in the main panel. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(186, "li")(187, "strong");
          core /* ɵɵtext */.EFF(188, "Recompute Connectivity");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(189, " — Refreshes connected components, strongly connected areas, and lists such as nodes with no incoming or no outgoing edges (directed), within this projection. ");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(190, "h3");
          core /* ɵɵtext */.EFF(191, "Main panel — Path Finder");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(192, "p");
          core /* ɵɵtext */.EFF(193, " Shows the ");
          core /* ɵɵelementStart */.j41(194, "strong");
          core /* ɵɵtext */.EFF(195, "shortest");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(196, " path (BFS on directed or undirected view per your toggle) and optional ");
          core /* ɵɵelementStart */.j41(197, "strong");
          core /* ɵɵtext */.EFF(198, "alternative simple paths");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(199, " with relation labels between steps. Labels come from the normalized relation type; they are not a substitute for full OPL validation. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(200, "h3");
          core /* ɵɵtext */.EFF(201, "Main panel — Important Elements");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(202, "p");
          core /* ɵɵtext */.EFF(203, " A table of elements ranked mainly by ");
          core /* ɵɵelementStart */.j41(204, "strong");
          core /* ɵɵtext */.EFF(205, "betweenness");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(206, " (and ties broken using degree / influence heuristics). Interpretations are phrased in system-modeling language (e.g. potential bridges, overloaded hubs). These are ");
          core /* ɵɵelementStart */.j41(207, "strong");
          core /* ɵɵtext */.EFF(208, "exploratory hints");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(209, ", not methodological certificates. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(210, "h3");
          core /* ɵɵtext */.EFF(211, "Main panel — Connectivity Analysis");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(212, "p");
          core /* ɵɵtext */.EFF(213, " Summarizes how the graph splits into components and highlights structural asymmetries (e.g. many nodes with no incoming edges in a directed view). Use this to see whether the model—or this projection—breaks into separate “islands.” ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(214, "h3");
          core /* ɵɵtext */.EFF(215, "Main panel — Suspicious Modeling Patterns");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(216, "p");
          core /* ɵɵtext */.EFF(217, " Heuristic flags with ");
          core /* ɵɵelementStart */.j41(218, "strong");
          core /* ɵɵtext */.EFF(219, "named elements");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(220, " listed under each category. Examples: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(221, "ul")(222, "li")(223, "strong");
          core /* ɵɵtext */.EFF(224, "Isolated");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(225, " — No relations in this projection.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(226, "li")(227, "strong");
          core /* ɵɵtext */.EFF(228, "Hubs");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(229, " — Very high degree; may be overloaded focal points.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(230, "li")(231, "strong");
          core /* ɵɵtext */.EFF(232, "Process gaps");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(233, " — Processes missing incoming and/or outgoing links in this projection.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(234, "li")(235, "strong");
          core /* ɵɵtext */.EFF(236, "Bottlenecks");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(237, " — High betweenness; possible bridges between areas.");
          core /* ɵɵelementEnd */.k0s()();
          core /* ɵɵelementStart */.j41(238, "p");
          core /* ɵɵtext */.EFF(239, " Long lists are truncated with a note; this is for readability, not an OPM completeness proof. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(240, "h3");
          core /* ɵɵtext */.EFF(241, "Graph preview (bottom of the page)");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(242, "p");
          core /* ɵɵtext */.EFF(243, " An ");
          core /* ɵɵelementStart */.j41(244, "strong");
          core /* ɵɵtext */.EFF(245, "SVG");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(246, " preview of a ");
          core /* ɵɵelementStart */.j41(247, "strong");
          core /* ɵɵtext */.EFF(248, "bounded sample");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(249, " of the snapshot (on the order of tens of nodes and edges—enough for orientation, not the whole model). It is for communication and exploration, not a faithful copy of OPD geometry on the canvas. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(250, "p")(251, "strong");
          core /* ɵɵtext */.EFF(252, "How layout works:");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(253, " High-degree nodes are ");
          core /* ɵɵelementStart */.j41(254, "strong");
          core /* ɵɵtext */.EFF(255, "seeded across a large virtual sheet");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(256, " (multi-hub style); neighbors are placed nearby; then a ");
          core /* ɵɵelementStart */.j41(257, "strong");
          core /* ɵɵtext */.EFF(258, "force-directed");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(259, " pass runs ");
          core /* ɵɵelementStart */.j41(260, "em");
          core /* ɵɵtext */.EFF(261, "without");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(262, " pinning nodes to the border of a fixed rectangle (so they do not line up on a “picture frame”). A final ");
          core /* ɵɵelementStart */.j41(263, "strong");
          core /* ɵɵtext */.EFF(264, "compact");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(265, " step pulls the layout slightly toward its centroid so the graph uses space efficiently while keeping the same overall shape. The SVG’s internal size is the graph’s ");
          core /* ɵɵelementStart */.j41(266, "strong");
          core /* ɵɵtext */.EFF(267, "bounding box");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(268, " (plus padding), not an arbitrary fixed chart size. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(269, "p")(270, "strong");
          core /* ɵɵtext */.EFF(271, "Navigator (viewport):");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(272, " The on-screen rectangle is only a ");
          core /* ɵɵelementStart */.j41(273, "strong");
          core /* ɵɵtext */.EFF(274, "window");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(275, " over that SVG. Use the ");
          core /* ɵɵelementStart */.j41(276, "strong");
          core /* ɵɵtext */.EFF(277, "mouse wheel");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(278, " to zoom toward the cursor, ");
          core /* ɵɵelementStart */.j41(279, "strong");
          core /* ɵɵtext */.EFF(280, "drag");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(281, " to pan, and the toolbar buttons ");
          core /* ɵɵelementStart */.j41(282, "strong");
          core /* ɵɵtext */.EFF(283, "Zoom in");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(284, ", ");
          core /* ɵɵelementStart */.j41(285, "strong");
          core /* ɵɵtext */.EFF(286, "Zoom out");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(287, ", and ");
          core /* ɵɵelementStart */.j41(288, "strong");
          core /* ɵɵtext */.EFF(289, "Fit graph");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(290, " to adjust the view. On large graphs, the first view may show a ");
          core /* ɵɵelementStart */.j41(291, "strong");
          core /* ɵɵtext */.EFF(292, "centered crop");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(293, "; use ");
          core /* ɵɵelementStart */.j41(294, "strong");
          core /* ɵɵtext */.EFF(295, "Fit graph");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(296, " or zoom out to see everything. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(297, "p")(298, "strong");
          core /* ɵɵtext */.EFF(299, "Reading the drawing:");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(300, " Nodes are drawn ");
          core /* ɵɵelementStart */.j41(301, "strong");
          core /* ɵɵtext */.EFF(302, "large");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(303, " for readability. Element names use a prominent font size. ");
          core /* ɵɵelementStart */.j41(304, "strong");
          core /* ɵɵtext */.EFF(305, "Relation names on links");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(306, " (consumption, aggregation, etc.) use ");
          core /* ɵɵelementStart */.j41(307, "strong");
          core /* ɵɵtext */.EFF(308, "larger type");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(309, " as well; they are shown when you are ");
          core /* ɵɵelementStart */.j41(310, "strong");
          core /* ɵɵtext */.EFF(311, "zoomed in");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(312, " enough, and hidden at wide “overview” zoom so the map stays uncluttered. ");
          core /* ɵɵelementStart */.j41(313, "strong");
          core /* ɵɵtext */.EFF(314, "Source");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(315, " and ");
          core /* ɵɵelementStart */.j41(316, "strong");
          core /* ɵɵtext */.EFF(317, "target");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(318, " from Path Analysis appear as ");
          core /* ɵɵelementStart */.j41(319, "strong");
          core /* ɵɵtext */.EFF(320, "larger circles with an outline");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(321, " when they are in the sample. Colors: objects (green tone), processes (blue), states (purple). ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(322, "p")(323, "strong");
          core /* ɵɵtext */.EFF(324, "Export PNG");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(325, " rasterizes the ");
          core /* ɵɵelementStart */.j41(326, "strong");
          core /* ɵɵtext */.EFF(327, "entire");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(328, " preview graph at ");
          core /* ɵɵelementStart */.j41(329, "strong");
          core /* ɵɵtext */.EFF(330, "2×");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(331, " resolution, with relation labels on edges turned on in the export. The filename includes the model name when available. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(332, "p", 5);
          core /* ɵɵtext */.EFF(333, " Short ");
          core /* ɵɵelementStart */.j41(334, "strong");
          core /* ɵɵtext */.EFF(335, "provenance");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(336, " lines may appear above the preview (how the snapshot relates to flattening vs RDF/Turtle); they mirror the same ideas described in the notes at the top of this guide. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(337, "h3");
          core /* ɵɵtext */.EFF(338, "Limitations & good practice");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(339, "ul")(340, "li");
          core /* ɵɵtext */.EFF(341, "Results depend on ");
          core /* ɵɵelementStart */.j41(342, "strong");
          core /* ɵɵtext */.EFF(343, "flattening");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(344, " and on the chosen ");
          core /* ɵɵelementStart */.j41(345, "strong");
          core /* ɵɵtext */.EFF(346, "projection");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(347, "; changing either can change paths and metrics materially.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(348, "li");
          core /* ɵɵtext */.EFF(349, "Very large models may feel slower; path enumeration stays bounded by depth and count limits.");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(350, "li");
          core /* ɵɵtext */.EFF(351, "Use ");
          core /* ɵɵelementStart */.j41(352, "strong");
          core /* ɵɵtext */.EFF(353, "Refresh from Current Model");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(354, " after substantive edits so the snapshot matches the editor.");
          core /* ɵɵelementEnd */.k0s()()();
          core /* ɵɵelementStart */.j41(355, "div", 6)(356, "button", 7);
          core /* ɵɵlistener */.bIt("click", function GraphInsightsInstructionsDialogComponent_Template_button_click_356_listener() {
            return ctx.close();
          });
          core /* ɵɵtext */.EFF(357, " Close ");
          core /* ɵɵelementEnd */.k0s()()();
        }
      },
      dependencies: [MatButton],
      styles: [".gi-instr-shell[_ngcontent-%COMP%]{display:flex;flex-direction:column;max-height:min(85vh,900px);width:100%;min-width:280px;font-family:Roboto,Helvetica Neue,sans-serif;color:#000000de;background:#fff}.gi-instr-title-wrap[_ngcontent-%COMP%]{flex-shrink:0;text-align:center;padding:20px 20px 12px;border-bottom:1px solid rgba(26,55,99,.12)}.gi-instr-title[_ngcontent-%COMP%]{margin:0 0 6px;font-size:22px;font-weight:600;color:#1a3763}.gi-instr-subtitle[_ngcontent-%COMP%]{margin:0;font-size:13px;color:#5a6c85;line-height:1.4}.gi-instr-scroll[_ngcontent-%COMP%]{flex:1 1 auto;overflow-y:auto;overflow-x:hidden;padding:16px 22px 8px;min-height:120px;-webkit-overflow-scrolling:touch}.gi-instr-scroll[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%]{margin:20px 0 8px;font-size:16px;font-weight:600;color:#1a3763}.gi-instr-scroll[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%]:first-child{margin-top:0}.gi-instr-scroll[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{margin:0 0 10px;font-size:14px;line-height:1.55;color:#000000de}.gi-instr-scroll[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]{margin:0 0 12px;padding-left:1.25rem;font-size:14px;line-height:1.55}.gi-instr-scroll[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{margin-bottom:6px}.gi-instr-scroll[_ngcontent-%COMP%]   .note[_ngcontent-%COMP%]{font-size:13px;color:#5a6c85;border-left:3px solid #1a3763;padding:8px 12px;margin:12px 0;background:#f8fbff}.gi-instr-footer[_ngcontent-%COMP%]{flex-shrink:0;padding:14px 20px 18px;text-align:center;border-top:1px solid rgba(26,55,99,.15);background:#fafbfc;box-shadow:0 -4px 12px #0000000a}.gi-instr-close-btn[_ngcontent-%COMP%]{min-width:120px;font-weight:500}"]
    }))();
  }
  return GraphInsightsInstructionsDialogComponent;
})();

var betweenness_default = /*#__PURE__*/__webpack_require__.n(betweenness);

var pagerank_default = /*#__PURE__*/__webpack_require__.n(pagerank);
