import { afterEach, expect, test } from 'bun:test';
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, symlinkSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const repo = resolve(import.meta.dir, '..'), dirs: string[] = [];
afterEach(() => { for (const d of dirs.splice(0))
    rmSync(d, { recursive: true, force: true }); });
const texto = (p: string) => readFileSync(join(repo, p), 'utf8'), q = (s: string) => "'" + s.replaceAll("'", "'\\''") + "'";
function entorno() {
    const raiz = mkdtempSync(join(tmpdir(), 'opforja scripts espacio-'));
    dirs.push(raiz);
    const proyecto = join(raiz, 'proyecto propio'), bin = join(raiz, 'bin'), log = join(raiz, 'calls.jsonl'), stub = join(raiz, 'stub.ts');
    mkdirSync(join(proyecto, 'deploy'), { recursive: true });
    mkdirSync(bin);
    for (const c of ['bash', 'dirname', 'grep', 'mktemp', 'rm', 'mkdir', 'mv', 'find', 'chmod', 'stat', 'gzip', 'env'])
        symlinkSync('/usr/bin/' + c, join(bin, c));
    writeFileSync(stub, `import {appendFileSync,writeFileSync} from 'node:fs';
const e=process.env,a=process.argv.slice(2),c=e.TEST_COMMAND;const fail=(m:string):never=>{console.error('STUB inesperado '+m);process.exit(97)};appendFileSync(e.TEST_LOG!,JSON.stringify({command:c,args:a,build:e.OPFORJA_BUILD})+'\\n');
if(c==='git'){if(JSON.stringify(a)===JSON.stringify(['rev-parse','--short','HEAD']))process.stdout.write('abc12345\\n');else if(JSON.stringify(a)===JSON.stringify(['status','--porcelain','--untracked-files=all'])){if(e.TEST_GIT_STATUS_EXIT)process.exit(Number(e.TEST_GIT_STATUS_EXIT));process.stdout.write(e.TEST_DIRTY??'');}else fail('git');}
else if(c==='date'){if(a.length!==1||!['+%F','+%s'].includes(a[0]!))fail('date');const t=Number(e.TEST_NOW);process.stdout.write(a[0]==='+%s'?String(t):new Date(t*1000).toISOString().slice(0,10));}
else if(c==='docker'){
 if(a[0]==='compose'){if(JSON.stringify(a)!==JSON.stringify(['compose','up','-d','--build','--wait','--wait-timeout','120','--remove-orphans']))fail('compose '+JSON.stringify(a));process.exit(Number(e.TEST_DOCKER_EXIT??0));}
 if(a.length!==13||a[0]!=='run'||a[1]!=='--rm'||a[2]!=='-v'||a[3]!=='opforja-datos:/datos:ro'||a[4]!=='-v'||a[5]!==e.TEST_DESTINO+':/respaldo'||a[6]!=='alpine'||a[7]!=='tar'||a[8]!=='czf'||!a[9]?.startsWith('/respaldo/.opforja-')||a[10]!=='-C'||a[11]!=='/datos'||a[12]!=='.')fail('backup '+JSON.stringify(a));
 const salida=e.TEST_DESTINO+a[9].slice('/respaldo'.length);if(e.TEST_DOCKER_EXIT){writeFileSync(salida,'parcial');process.exit(Number(e.TEST_DOCKER_EXIT));}const r=Bun.spawnSync(['/usr/bin/tar','czf',salida,'-C',e.TEST_DATOS!,'.'],{env:{PATH:e.PATH!}});process.stderr.write(r.stderr);process.exit(r.exitCode);
}else if(c==='curl'){
 const url=a.find(x=>x.startsWith('http://'));if(!url||!url.startsWith('http://synthetic.invalid'))fail('URL');const p=url!.slice('http://synthetic.invalid'.length),wanted=p==='/salud'?['-fsS','--retry','5','--retry-delay','2','--max-time','15',url]:p==='/api/sesion'?['-sS','--max-time','15','-o','/dev/null','-w','%{http_code}',url]:p==='/'?['-fsS','--max-time','15',url]:null;if(!wanted||JSON.stringify(a)!==JSON.stringify(wanted))fail('curl '+JSON.stringify(a));if(e.TEST_CURL_FAIL===p)process.exit(22);process.stdout.write(p==='/salud'?JSON.stringify({ok:true,version:e.TEST_VERSION??'abc12345'}):p==='/api/sesion'?(e.TEST_SESSION??'401'):(e.TEST_HTML??'<div id="app">sintética</div>'));
}else fail('command '+c);`);
    for (const c of ['git', 'docker', 'curl', 'date'])
        writeFileSync(join(bin, c), `#!/bin/sh\nTEST_COMMAND=${c} exec ${q(process.execPath)} --no-env-file ${q(stub)} "$@"\n`, { mode: 0o755 });
    writeFileSync(join(bin, 'bun'), '#!/bin/sh\necho "Bun fuera del circuito" >&2\nexit 97\n', { mode: 0o755 });
    const ejecutar = (nombre: string, extra: Record<string, string> = {}) => { const origen = join(repo, 'deploy', nombre); expect(existsSync(origen), nombre + ' debe existir').toBe(true); const copia = join(proyecto, 'deploy', nombre); copyFileSync(origen, copia); const r = Bun.spawnSync(['/usr/bin/bash', copia], { cwd: raiz, env: { PATH: bin, TEST_LOG: log, OPFORJA_URL: 'http://synthetic.invalid/', OPFORJA_REPO: proyecto, TEST_NOW: String(Math.floor(Date.now() / 1000)), ...extra } }); return { status: r.exitCode, output: r.stdout.toString() + r.stderr.toString(), calls: existsSync(log) ? readFileSync(log, 'utf8').trim().split('\n').filter(Boolean).map(l => JSON.parse(l) as {
            command: string;
            args: string[];
            build?: string;
        }) : [] }; };
    return { raiz, bin, ejecutar };
}
const deploy = (e: Record<string, string> = {}) => entorno().ejecutar('deploy.sh', e);
test('WP-18 §9.3 copia espera Compose exacto, versión,401/app antes del éxito', () => { const r = deploy(); expect(r.status, r.output).toBe(0); expect(r.output).toContain('✓ opforja abc12345 disponible'); expect(r.calls.map(c => c.command)).toEqual(['git', 'git', 'docker', 'curl', 'curl', 'curl']); expect(r.calls[2]?.build).toBe('abc12345'); });
for (const dirty of [' M app/src/main.tsx\n', '?? docs/bugs/nuevo.json\n', '?? archivo nuevo\n'])
    test('WP-18 §9.3 dirty incluye ' + JSON.stringify(dirty), () => { const r = deploy({ TEST_DIRTY: dirty, TEST_VERSION: 'abc12345-dirty' }); expect(r.status, r.output).toBe(0); expect(r.calls[2]?.build).toBe('abc12345-dirty'); });
test('WP-18 §9.3 Compose42 propaga fallo sin curl posterior', () => { const r = deploy({ TEST_DOCKER_EXIT: '42' }); expect(r.status).toBe(42); expect(r.calls.some(c => c.command === 'curl')).toBe(false); expect(r.output).not.toContain('✓'); });
for (const [n, e] of [['salud vieja', { TEST_VERSION: 'vieja' }], ['salud IO', { TEST_CURL_FAIL: '/salud' }], ['sesión pública', { TEST_SESSION: '200' }], ['sesión403', { TEST_SESSION: '403' }], ['sesión500', { TEST_SESSION: '500' }], ['sesión IO', { TEST_CURL_FAIL: '/api/sesion' }], ['HTML sin app', { TEST_HTML: '<h1>otra</h1>' }], ['HTML IO', { TEST_CURL_FAIL: '/' }]] as const)
    test('WP-18 §9.3 ' + n + ' impide éxito', () => { const r = deploy(e); expect(r.status).not.toBe(0); expect(r.output).not.toContain('✓'); const path = 'TEST_CURL_FAIL' in e ? e.TEST_CURL_FAIL : 'TEST_VERSION' in e ? '/salud' : 'TEST_SESSION' in e ? '/api/sesion' : '/'; expect(r.calls.some(c => c.command === 'curl' && c.args.at(-1)?.endsWith(path))).toBe(true); });
function backup() { const p = entorno(), datos = join(p.raiz, 'datos sintéticos'), destino = join(p.raiz, 'respaldos privados'); mkdirSync(datos); mkdirSync(destino); const originales = { 'cuenta.json': Buffer.from('{"email":"sintetica@example.test"}'), 'modelos/modelo con espacio.json': Buffer.from([0, 255, 239, 187, 191]), 'papelera/original.json': Buffer.from('original'), 'previas/anterior.json': Buffer.from('previa') }; for (const [n, b] of Object.entries(originales)) {
    mkdirSync(resolve(datos, n, '..'), { recursive: true });
    writeFileSync(join(datos, n), b);
} return { ...p, datos, destino, originales, ejecutar: (e: Record<string, string> = {}) => p.ejecutar('respaldo.sh', { OPFORJA_RESPALDOS: destino, TEST_DATOS: datos, TEST_DESTINO: destino, ...e }) }; }
test('WP-18 §8.7 backup fixture byteexacto privado mountRO y paths espacios', () => { const p = backup(), r = p.ejecutar(); expect(r.status, r.output).toBe(0); const ns = readdirSync(p.destino); expect(ns).toHaveLength(1); expect(ns[0]).toMatch(/^opforja-\d{4}-\d\d-\d\d\.tgz$/); const archivo = join(p.destino, ns[0]!); expect(statSync(archivo).mode & 0o777).toBe(0o600); expect(statSync(p.destino).mode & 0o777).toBe(0o700); const extraido = join(p.raiz, 'extraído'); mkdirSync(extraido); expect(Bun.spawnSync(['/usr/bin/tar', 'xzf', archivo, '-C', extraido], { env: { PATH: '/usr/bin:/bin' } }).exitCode).toBe(0); for (const [n, b] of Object.entries(p.originales))
    expect(readFileSync(join(extraido, n))).toEqual(b); expect(r.output).not.toContain('sintetica@example.test'); });
test('WP-18 §8.7 fallo tar preserva anterior/ajenos y no poda; limpia temporal propio', () => { const p = backup(), hoy = new Date().toISOString().slice(0, 10), previo = join(p.destino, 'opforja-' + hoy + '.tgz'), viejo = join(p.destino, 'opforja-2000-01-01.tgz'); writeFileSync(previo, 'completo'); writeFileSync(viejo, 'antiguo'); writeFileSync(join(p.destino, 'ajeno.tgz'), 'ajeno'); const r = p.ejecutar({ TEST_DOCKER_EXIT: '42' }); expect(r.status).toBe(42); expect(readFileSync(previo, 'utf8')).toBe('completo'); expect(readFileSync(viejo, 'utf8')).toBe('antiguo'); expect(readFileSync(join(p.destino, 'ajeno.tgz'), 'utf8')).toBe('ajeno'); expect(readdirSync(p.destino).sort()).toEqual(['ajeno.tgz', 'opforja-2000-01-01.tgz', 'opforja-' + hoy + '.tgz'].sort()); });
test('WP-18 §8.7 retención14d solo éxito y patrón propio, conserva ajenos', () => { const p = backup(), t = Date.now() / 1000, v = join(p.destino, 'opforja-2000-01-01.tgz'), k = join(p.destino, 'opforja-2000-01-02.tgz'), a = join(p.destino, 'otro-2000-01-01.tgz'); for (const n of [v, k, a])
    writeFileSync(n, 'anterior'); utimesSync(v, t - 14 * 86400 - 3600, t - 14 * 86400 - 3600); utimesSync(k, t - 14 * 86400 + 3600, t - 14 * 86400 + 3600); utimesSync(a, t - 40 * 86400, t - 40 * 86400); const r = p.ejecutar(); expect(r.status, r.output).toBe(0); expect(existsSync(v)).toBe(false); expect(readFileSync(k, 'utf8')).toBe('anterior'); expect(readFileSync(a, 'utf8')).toBe('anterior'); });
test('WP-18 §9.1 estático dos etapas Bun, runner solo bundles/web sin acreditar imagen', () => { const partes = texto('Dockerfile').split(/^FROM /m).slice(1); expect(partes).toHaveLength(2); expect(partes[0]).toStartWith('oven/bun:1.3 AS construccion'); expect(partes[1]).toStartWith('oven/bun:1.3-slim'); const r = partes[1]!; expect(r.match(/^COPY .+$/gm)).toEqual(['COPY --from=construccion /src/app/dist ./web', 'COPY --from=construccion /src/app/dist-servidor ./servidor']); expect(r).toContain('USER bun'); expect(r).toContain('EXPOSE 8080'); expect(r).toContain('/salud'); expect(r).toContain('CMD ["bun", "--no-env-file", "servidor/principal.js"]'); expect(r).not.toMatch(/node_modules|app\/src|\.test\.ts|nginx/); });
test('WP-18 §9.2 estático Compose servicio/volumen físico único y HSTS sin headers duplicados', () => { const c = Bun.YAML.parse(texto('docker-compose.yml')) as any; expect(Object.keys(c.services)).toEqual(['opforja']); expect(c.volumes).toEqual({ 'opforja-datos': { name: 'opforja-datos' } }); expect(c.networks).toEqual({ web: { external: true } }); const s = c.services.opforja; expect(s.volumes).toEqual(['opforja-datos:/datos']); expect(s.environment.OPFORJA_SECRETO).toStartWith('${OPFORJA_SECRETO:?'); expect(s.environment.OPFORJA_TOKEN).toBe('${OPFORJA_TOKEN:-}'); expect(s.build.args.OPFORJA_VERSION).toBe('${OPFORJA_BUILD:-local}'); expect(s.labels.join('\n')).toContain('stsSeconds=63072000'); expect(s.labels.join('\n')).not.toMatch(/customResponseHeaders|Content-Security-Policy|X-Frame-Options|X-Content-Type-Options/); });
test('WP-18 §8.7 servicio/script UMask077 y timer diario03:30 persistente', () => { const s = texto('deploy/systemd/opforja-respaldo.service'), t = texto('deploy/systemd/opforja-respaldo.timer'); expect(s).toContain('Type=oneshot'); expect(s).toContain('Environment=OPFORJA_REPO='); expect(s).toContain('$OPFORJA_REPO/deploy/respaldo.sh'); expect(s).toContain('UMask=0077'); expect(t).toContain('OnCalendar=*-*-* 03:30:00'); expect(t).toContain('Persistent=true'); expect(t).toContain('Unit=opforja-respaldo.service'); });
test('WP-18 §9.1 layout3 entradas declarado sin fingir buildUI/imagen actuales', () => { expect(JSON.parse(texto('app/package.json')).scripts.build).toBe("vite build && bun build servidor/principal.ts servidor/cuenta.ts herramientas/migrar-postgres.ts --target=bun --outdir dist-servidor --entry-naming '[name].js'"); });
test('WP-18 §9.1 Vite pre-transform conecta main sin editar index ni crearUI', async () => { const c = (await import('../app/vite.config')).default as any; expect(c.envDir).toBe(false); expect(c.build.outDir).toBe('dist'); const p = c.plugins.find((x: any) => x.name === 'opforja-entrada'); expect(p?.transformIndexHtml?.order).toBe('pre'); expect(await p.transformIndexHtml.handler(texto('app/index.html'))).toContain('<script type="module" src="/src/main.tsx"></script>'); });
test('WP-18 §9.1 Playwright bundle real/dist y entorno mínimo sin envfile', async () => { const c = (await import('../app/playwright.config')).default as any; expect(c.webServer.command).toContain('env -i'); expect(c.webServer.command).toContain('bun --no-env-file dist-servidor/principal.js'); expect(c.webServer.command).toContain('OPFORJA_WEB='); expect(c.webServer.command).toContain('/dist'); expect(c.webServer.command).toContain('OPFORJA_SECRETO='); expect(c.webServer.reuseExistingServer).toBe(false); });
test('WP-18 §8.7 frontera14d exacta se conserva y prefijos parecidos son ajenos', () => { const p = backup(), now = Math.floor(Date.now() / 1000), frontera = join(p.destino, 'opforja-2000-02-01.tgz'), ajeno = join(p.destino, 'opforja-texto-02-01.tgz'); writeFileSync(frontera, 'frontera'); writeFileSync(ajeno, 'ajeno'); utimesSync(frontera, now - 14 * 86400, now - 14 * 86400); utimesSync(ajeno, now - 30 * 86400, now - 30 * 86400); const r = p.ejecutar({ TEST_NOW: String(now) }); expect(r.status, r.output).toBe(0); expect(existsSync(frontera)).toBe(true); expect(readFileSync(ajeno, 'utf8')).toBe('ajeno'); });
test('WP-18 §8.7 publicación no mueve temporal dentro de directorio ajeno homónimo', () => { const p = backup(), now = Math.floor(Date.now() / 1000), hoy = new Date(now * 1000).toISOString().slice(0, 10), homonimo = join(p.destino, 'opforja-' + hoy + '.tgz'); mkdirSync(homonimo); writeFileSync(join(homonimo, 'ajeno'), 'conservar'); const r = p.ejecutar({ TEST_NOW: String(now) }); expect(r.status).not.toBe(0); expect(readdirSync(homonimo)).toEqual(['ajeno']); expect(readFileSync(join(homonimo, 'ajeno'), 'utf8')).toBe('conservar'); expect(readdirSync(p.destino)).toEqual(['opforja-' + hoy + '.tgz']); expect(r.output).not.toContain('✓'); });
test('WP-18 §9.1 Playwright arranque se limita a loopback y no hereda auth', async () => { const c = (await import('../app/playwright.config')).default as any; expect(c.webServer.command).toContain('--host 127.0.0.1'); });
test('WP-18 §9.1 bundler Bun local dos entradas reales produce nombres planos, tercera diferida12', () => { const d = mkdtempSync(join(tmpdir(), 'opforja bundles propios-')); dirs.push(d); const r = Bun.spawnSync([process.execPath, '--no-env-file', 'build', join(repo, 'app/servidor/principal.ts'), join(repo, 'app/servidor/cuenta.ts'), '--target=bun', '--outdir', d, '--entry-naming', '[name].js'], { env: { PATH: '/tmp/opforja-rehacer-tools:/usr/bin:/bin' } }); expect(r.exitCode, r.stderr.toString()).toBe(0); expect(readdirSync(d).sort()).toEqual(['cuenta.js', 'principal.js']); expect(readFileSync(join(d, 'principal.js'), 'utf8')).toContain('servidor-iniciado'); });
test('WP-18 §9.1 comando Playwright real limpia auth heredada y entrega args al Bun sinenv', async () => { const c = (await import('../app/playwright.config')).default as any, p = entorno(), probe = join(p.raiz, 'probe.ts'); writeFileSync(probe, `console.log(JSON.stringify({args:process.argv.slice(2),token:process.env.OPFORJA_TOKEN,secreto:process.env.OPFORJA_SECRETO,web:process.env.OPFORJA_WEB,heredada:process.env.AUTH_SINTETICA!==undefined}));`); writeFileSync(join(p.bin, 'bun'), `#!/bin/sh\nexec ${q(process.execPath)} --no-env-file ${q(probe)} "$@"\n`, { mode: 0o755 }); const r = Bun.spawnSync(['/usr/bin/bash', '-c', c.webServer.command], { env: { PATH: p.bin, AUTH_SINTETICA: 'no-heredar', OPFORJA_TOKEN: 'token-padre-sintetico-no-heredar', OPFORJA_SECRETO: 'secreto-padre-sintetico-no-heredar' } }); expect(r.exitCode, r.stderr.toString()).toBe(0); const visto = JSON.parse(r.stdout.toString()); expect(visto.heredada).toBe(false); expect(visto.token).toBe('token-sintetico-e2e-exclusivo-1234567890-1234567890'); expect(visto.secreto).toBe('secreto-sintetico-e2e-exclusivo-1234567890'); expect(visto.args.slice(0, 4)).toEqual(['--no-env-file', 'dist-servidor/principal.js', '--host', '127.0.0.1']); expect(visto.web).toBe(join(repo, 'app/dist')); });
test('WP-18 §8.7 lectura fallida real de fixture no publica ni toca anterior/ajeno', () => { const p = backup(), hoy = new Date().toISOString().slice(0, 10), previo = join(p.destino, 'opforja-' + hoy + '.tgz'); writeFileSync(previo, 'completo'); const r = p.ejecutar({ TEST_DATOS: join(p.raiz, 'fuente inexistente') }); expect(r.status).not.toBe(0); expect(readFileSync(previo, 'utf8')).toBe('completo'); expect(readdirSync(p.destino)).toEqual(['opforja-' + hoy + '.tgz']); expect(r.output).not.toContain('✓'); });
test('WP-18 §9.3 estado Git ilegible no declara SHA limpio ni inicia Compose', () => { const r = deploy({ TEST_GIT_STATUS_EXIT: '38' }); expect(r.status).toBe(38); expect(r.calls.some(c => c.command === 'docker')).toBe(false); expect(r.output).not.toContain('✓'); });
test('WP-18 §9.1 contexto Docker excluye secretos/datos/salidas, permite fuentes para construcción', () => { const d = texto('.dockerignore').split('\n'); for (const patron of ['.git', '.env', '.env.*', '**/.env', '**/.env.*', '**/cuenta.json', 'app/node_modules', 'app/dist', 'app/dist-servidor', 'app/.datos*', 'datos', 'respaldos'])
    expect(d).toContain(patron); expect(d).not.toContain('app/src'); });
