import type { OpmStore } from "./tipos";

type Slice<K extends keyof OpmStore> = Pick<OpmStore, K>;

export type CrearSlice<T> = (
  set: (partial: Partial<OpmStore> | ((state: OpmStore) => Partial<OpmStore>)) => void,
  get: () => OpmStore,
) => T;

export type ModeloSlice = Slice<
  | "modelo"
  | "opdActivoId"
  | "mensaje"
  | "dirty"
  | "dirtyModelo"
  | "puedeDeshacer"
  | "puedeRehacer"
  | "plantillasGuardadas"
  | "dialogoPlantillasAbierto"
  | "dialogoGuardarPlantillaAbierto"
  | "idsResaltadosTemporales"
  | "pantallaInicioCerrada"
  | "dialogoRenombrarModeloAbierto"
  | "dialogoTraerConectadosAbierto"
  | "gridConfig"
  | "limpiarMensaje"
  | "abrirMenuPrincipal"
  | "cerrarMenuPrincipal"
  | "fijarToolbarMasAbierto"
  | "abrirGuardarComo"
  | "cerrarGuardarComo"
  | "guardarComoLocal"
  | "guardarComoLocalConDescripcion"
  | "abrirCargarModelo"
  | "cerrarCargarModelo"
  | "cargarLocalDesdeDialogo"
  | "cerrarPantallaInicio"
  | "abrirRenombrarModelo"
  | "cerrarRenombrarModelo"
  | "abrirDialogoTraerConectados"
  | "cerrarDialogoTraerConectados"
  | "renombrarModeloActual"
  | "abrirDialogoPlantillas"
  | "cerrarDialogoPlantillas"
  | "abrirDialogoGuardarPlantilla"
  | "cerrarDialogoGuardarPlantilla"
  | "guardarComoPlantillaConfirmar"
  | "insertarPlantillaEnOpdActivo"
  | "resaltarTemporalmente"
  | "cargarEjemploOrganizacional"
  | "nuevoModelo"
  | "crearObjetoDemo"
  | "crearProcesoDemo"
  | "crearEntidadEnCanvas"
  | "nuevaCosaPendiente"
  | "confirmarNombreNuevaCosa"
  | "descartarNuevaCosaPendiente"
  | "crearAparienciaEntidadEnCanvas"
  | "fijarModoCreacion"
  | "descomponerSeleccionada"
  | "desplegarSeleccionada"
  | "quitarDescomposicionSeleccionada"
  | "quitarDespliegueSeleccionado"
  | "reasignarEnlaceExternoManual"
  | "eliminarOpdDesdeArbol"
  | "cambiarOpdActivo"
  | "seleccionarEntidad"
  | "seleccionarEstadoComoExtremo"
  | "seleccionarEnlace"
  | "seleccionarDesdeOpl"
  | "renombrarEntidadDesdeOpl"
  | "fijarFiltroOplPorSeleccion"
  | "fijarHoverOpl"
  | "fijarBusquedaOpl"
  | "buscarEnPanelOpl"
  | "alternarNumeracionOpl"
  | "cambiarPosicionOpl"
  | "minimizarOpl"
  | "restaurarOpl"
  | "alternarBloqueOplContraido"
  | "mostrarPlaceholderAiOpl"
  | "editarEtiquetaEnlaceDesdeOpl"
  | "renombrarEstadoDesdeOpl"
  | "abrirInspectorEnlaceDesdeOpl"
  | "aplicarEdicionOplLibre"
  | "copiarOplActualAlPortapapeles"
  | "exportarOplActualHtml"
  | "navegarAviso"
  | "deshacer"
  | "rehacer"
  | "elegirTipoEnlace"
  | "crearEnlaceEntreEntidades"
  | "cancelarEnlace"
  | "renombrarSeleccionada"
  | "crearAtributoEnObjetoSeleccionado"
  | "asignarValorAtributoSeleccionado"
  | "cambiarTipoValorAtributoSeleccionado"
  | "configurarSimulacionAtributoSeleccionado"
  | "fijarEsenciaSeleccionada"
  | "fijarAfiliacionSeleccionada"
  | "redimensionarSeleccionada"
  | "redimensionarAparienciaEnCanvas"
  | "ajustarSeleccionadaAlTexto"
  | "volverSeleccionadaAAuto"
  | "alternarModoTamanoSeleccionado"
  | "cambiarModoPlegadoSeleccionado"
  | "cambiarModoPlegadoApariencia"
  | "fijarModoPlegadoApariencia"
  | "cambiarOrdenPartesSeleccionado"
  | "fijarOrdenPartesApariencia"
  | "aplicarEstiloSeleccionado"
  | "resetearEstiloSeleccionado"
  | "seleccionarPartePlegada"
  | "extraerParteDePlegado"
  | "extraerTodasLasPartesSeleccionadas"
  | "reinsertarParteExtraidaSeleccionada"
  | "agregarEstadosObjeto"
  | "agregarEstadoObjeto"
  | "eliminarEstado"
  | "quitarEstadosObjetoSeleccionado"
  | "renombrarEstadoSeleccionado"
  | "designarEstadoInicial"
  | "designarEstadoFinal"
  | "editarAliasEntidad"
  | "editarUnidadEntidad"
  | "editarDescripcionEntidad"
  | "abrirModalUrls"
  | "cerrarModalUrls"
  | "agregarUrlAEntidad"
  | "eliminarUrlDeEntidad"
  | "reordenarUrlsEntidad"
  | "abrirModalImagen"
  | "cerrarModalImagen"
  | "editarImagenEntidad"
  | "quitarImagenEntidad"
  | "cambiarModoImagenEntidad"
  | "alternarModoImagenEntidad"
  | "fijarModoImagenGlobal"
  | "activarReadOnly"
  | "designarEstadoComo"
  | "quitarDesignacionEstado"
  | "suprimirEstadoPorId"
  | "restaurarEstadoPorId"
  | "abrirModalDuracion"
  | "cerrarModalDuracion"
  | "fijarDuracionEstado"
  | "quitarDuracionEstado"
  | "fijarLayoutEstadosEntidad"
  | "toggleAliasVisibles"
  | "toggleDescripcionesVisibles"
  | "moverEntidad"
  | "moverApariencia"
  | "moverAparienciaConPuertos"
  | "actualizarPosicionSimboloEstructural"
  | "toggleGrid"
  | "fijarGridConfig"
  | "alinearSeleccion"
  | "distribuirSeleccion"
  | "aplicarLayoutSugerido"
  | "reordenarSubprocesoEnTimeline"
  | "actualizarVerticesEnlace"
  | "traerConectadosSeleccionado"
  | "traerEnlacesEntreSeleccionadas"
  | "ocultarAparienciaSeleccionada"
  | "ajustarMultiplicidadSeleccionada"
  | "apuntarExtremoEnlaceSeleccionado"
  | "reanclarEnlaceExternoDerivado"
  | "splitEffectSeleccionado"
  | "volverEnlaceExternoDerivadoAAutomatico"
  | "alternarOperadorAbanicoSeleccionado"
  | "quitarRamaDeAbanicoSeleccionado"
  | "disolverAbanicoSeleccionado"
  | "crearAutoInvocacionSeleccionada"
  | "aplicarModificadorEnlaceSeleccionado"
  | "aplicarSubtipoModificadorEnlaceSeleccionado"
  | "quitarModificadorEnlaceSeleccionado"
  | "definirProbabilidadEventoSeleccionada"
  | "definirDemoraInvocacionSeleccionada"
  | "moverPuertoEnlaceSeleccionado"
  | "renombrarEtiquetaEnlaceSeleccionado"
  | "definirRutaEtiquetaSeleccionada"
>;

export type SeleccionSlice = Slice<
  | "seleccionId"
  | "seleccionados"
  | "modoSeleccion"
  | "portapapelesVisual"
  | "enlaceSeleccionId"
  | "eliminarSeleccion"
  | "setSeleccion"
  | "agregarASeleccion"
  | "quitarDeSeleccion"
  | "toggleSeleccion"
  | "vaciarSeleccion"
  | "seleccionarTodoEnOpd"
  | "nudgeSeleccion"
  | "alinearSeleccionEnlaces"
  | "conectarSeleccionAlTodo"
  | "aplicarEstiloASeleccion"
  | "copiarSeleccionAlBuffer"
  | "pegarBufferEnOpdActivo"
>;

export type EnlacesSlice = Slice<
  | "modoEnlace"
  | "modoCreacion"
  | "tablaEnlacesAbierta"
  | "tablaEnlacesFiltroTipo"
  | "tablaEnlacesOrdenColumna"
  | "tablaEnlacesOrdenDireccion"
  | "enlaceEstiloPortapapeles"
  | "fijarMultiplicidadEnlace"
  | "quitarMultiplicidadEnlace"
  | "aplicarEstiloEnlaceAccion"
  | "resetEstiloEnlaceAccion"
  | "copiarEstiloEnlaceAlPortapapeles"
  | "pegarEstiloEnlaceDesdePortapapeles"
  | "aplicarEstiloTextoAccion"
  | "resetEstiloTextoAccion"
  | "insertarVerticeAccion"
  | "reposicionarVerticeAccion"
  | "reanclarExtremoAccion"
  | "separarGrupoEstructuralSeleccionado"
  | "volverGrupoEstructuralAutomaticoSeleccionado"
  | "borrarEnlacesEnLote"
  | "abrirTablaEnlaces"
  | "cerrarTablaEnlaces"
  | "fijarFiltroTablaEnlaces"
  | "fijarOrdenTablaEnlaces"
  | "navegarAEnlaceDesdeTabla"
  | "irAExtremoEnlaceTabla"
  | "eliminarEnlaceDesdeTabla"
>;

export type WorkspaceModSlice = Slice<
  | "indice"
  | "carpetaActualId"
  | "modelosRecientes"
  | "crearCarpetaEnActual"
  | "renombrarCarpetaEnIndice"
  | "eliminarCarpetaEnIndice"
  | "abrirCarpeta"
  | "moverModeloACarpetaEnIndice"
  | "cortarModelo"
  | "cortarCarpeta"
  | "cancelarPortapapelesWorkspace"
  | "pegarEn"
  | "moverModeloDirecto"
  | "moverCarpetaDirecto"
  | "archivarModeloActual"
  | "archivarModeloPorId"
  | "restaurarModeloPorId"
  | "archivarCarpetaPorId"
  | "restaurarCarpetaPorId"
  | "guardarConVersion"
  | "crearVersionAhora"
>;

export type CarpetasSlice = Slice<
  | "portapapelesWorkspace"
  | "mostrarArchivados"
  | "mostrarVersiones"
  | "dialogoVersionesAbierto"
  | "dialogoArchivadosAbierto"
  | "dialogoBuscarGlobalAbierto"
  | "busquedaGlobal"
  | "busquedaCosasAbierta"
  | "busquedaCosasQuery"
  | "busquedaCosasFiltro"
  | "abrirDialogoVersiones"
  | "cerrarDialogoVersiones"
  | "restaurarVersionComoCopia"
  | "eliminarVersionPorId"
  | "abrirDialogoArchivados"
  | "cerrarDialogoArchivados"
  | "abrirDialogoBuscarGlobal"
  | "cerrarDialogoBuscarGlobal"
  | "fijarBusquedaGlobalQuery"
  | "ejecutarBusquedaGlobal"
  | "abrirResultadoBusquedaGlobal"
  | "toggleMostrarArchivados"
  | "toggleMostrarVersiones"
  | "abrirBusquedaCosas"
  | "cerrarBusquedaCosas"
  | "fijarBusquedaCosasQuery"
  | "fijarBusquedaCosasFiltro"
  | "saltarAResultadoBusqueda"
>;

export type UiPanelSlice = Slice<
  | "filtroOplPorSeleccion"
  | "hoverOplRef"
  | "busquedaOpl"
  | "menuPrincipalAbierto"
  | "toolbarMasAbierto"
  | "dialogoGuardarComoAbierto"
  | "dialogoCargarModeloAbierto"
  | "uiAliasVisibles"
  | "uiDescripcionesVisibles"
  | "solicitudFitToken"
  | "readOnly"
  | "modalUrlsAbierto"
  | "modalImagenAbierto"
  | "uiModoImagenGlobal"
  | "modalDuracionAbierto"
  | "modoOrdenArbol"
  | "gestionArbolAbierta"
  | "busquedaOpdGestion"
  | "anchoPanelArbol"
  | "anchoPanelInspector"
  | "nombresArbolVisibles"
  | "cheatsheetAtajosAbierto"
  | "vistaMobileActiva"
  | "asistente"
  | "fijarModoOrdenArbol"
  | "moverHermano"
  | "moverOpdEnGestion"
  | "abrirGestionArbol"
  | "cerrarGestionArbol"
  | "fijarBusquedaOpdGestion"
  | "renombrarOpdDesdeArbol"
  | "fijarAnchoPanelArbol"
  | "fijarAnchoPanelInspector"
  | "toggleNombresArbolVisibles"
  | "abrirCheatsheetAtajos"
  | "cerrarCheatsheetAtajos"
  | "cambiarVistaMobile"
  | "navegarOpdArriba"
  | "navegarOpdAbajo"
  | "navegarOpdIzquierda"
  | "navegarOpdDerecha"
  | "iniciarAsistente"
  | "siguienteEtapa"
  | "etapaAnterior"
  | "cancelarAsistente"
  | "confirmarAsistente"
  // L3 ronda 20: biblioteca overlay legacy + dock acoplable
  | "bibliotecaCosaAbierta"
  | "bibliotecaDockAbierto"
  | "toggleBibliotecaCosa"
  | "abrirBibliotecaCosa"
  | "cerrarBibliotecaCosa"
  | "toggleBibliotecaDock"
  | "abrirBibliotecaDock"
  | "cerrarBibliotecaDock"
  // L1 ronda 20: tabs por intención del Inspector
  | "tabInspectorEntidadActivo"
  | "tabInspectorEnlaceActivo"
  | "cambiarTabInspectorEntidad"
  | "cambiarTabInspectorEnlace"
>;

export type MapaSlice = Slice<
  | "vistaMapaActiva"
  | "descriptorMapaCache"
  | "mapaProfundidadMaxima"
  | "mapaSubarbolRaizId"
  | "mapaCriterioResaltado"
  | "mapaZoom"
  | "mapaPanX"
  | "mapaPanY"
  | "mapaAutoRefresh"
  | "mapaUltimoVisitadoOpdId"
  | "mapaTooltipActivoId"
  | "mapaPanelFiltrosAbierto"
  | "mapaPanelEstadisticasAbierto"
  | "abrirVistaMapa"
  | "cerrarVistaMapa"
  | "refrescarVistaMapa"
  | "saltarAOpdDesdeMapa"
  | "fijarMapaProfundidad"
  | "fijarMapaSubarbol"
  | "fijarMapaCriterioResaltado"
  | "fijarMapaZoom"
  | "fijarMapaPan"
  | "toggleMapaAutoRefresh"
  | "fijarMapaTooltip"
  | "toggleMapaPanelFiltros"
  | "toggleMapaPanelEstadisticas"
  | "limpiarFiltrosMapa"
  | "descriptorMapaFiltrado"
  | "estadisticasModelo"
>;

export type PersistenciaSlice = Slice<
  | "modelosGuardados"
  | "modeloPersistidoId"
  | "descripcionModeloLocal"
  | "workspaceLocal"
  | "autosalvado"
  | "exportarJson"
  | "importarJson"
  | "listarModelosGuardados"
  | "guardarLocal"
  | "cargarLocal"
  | "borrarLocal"
  | "cargarDemo"
  | "cargarFixtureDemo"
  | "iniciarAutosalvado"
  | "detenerAutosalvado"
>;

export type PestanasSlice = Slice<
  | "pestanasAbiertas"
  | "pestanaActivaId"
  | "abrirPestanaNueva"
  | "abrirPestanaConAsistente"
  | "abrirPestanaImportandoJson"
  | "abrirPestanaConModelo"
  | "duplicarPestana"
  | "cerrarPestana"
  | "cambiarPestanaActiva"
  | "reordenarPestanas"
  | "renombrarPestana"
>;

export type SimulacionSlice = Slice<
  | "contextoSimulacion"
  | "readOnlyPrevSimulacion"
  | "autoAvanceSimulacionActivo"
  | "velocidadSimulacion"
  | "iniciarModoSimulacion"
  | "salirModoSimulacion"
  | "ejecutarPasoSimulacion"
  | "ejecutarCorridaSimulacion"
  | "reiniciarSimulacionActual"
  | "iniciarAutoAvanceSimulacion"
  | "pausarAutoAvanceSimulacion"
  | "fijarVelocidadSimulacion"
  | "asignarValorRuntimeSimulacion"
>;

export type OpmStoreSlices =
  & ModeloSlice
  & SeleccionSlice
  & EnlacesSlice
  & WorkspaceModSlice
  & CarpetasSlice
  & UiPanelSlice
  & MapaSlice
  & PersistenciaSlice
  & PestanasSlice
  & SimulacionSlice;

type AssertNever<T extends never> = T;

export type OpmStoreSliceMissingKeys = AssertNever<Exclude<keyof OpmStore, keyof OpmStoreSlices>>;
export type OpmStoreSliceExtraKeys = AssertNever<Exclude<keyof OpmStoreSlices, keyof OpmStore>>;
