// Source: decompiled/deobfuscated.js
// Original path: ./src/app/modules/Settings/OPCloudPrivacyPolicy/opcloud-privacy-policy.component.ts
// Extracted by opm-extracted/tools/extract.mjs

let OPCloudPrivacyPolicyComponent = /*#__PURE__*/(() => {
  class OPCloudPrivacyPolicyComponent {
    constructor() {}
    ngOnInit() {}
    static #_ = (() => this.ɵfac = function OPCloudPrivacyPolicyComponent_Factory(__ngFactoryType__) {
      return new (__ngFactoryType__ || OPCloudPrivacyPolicyComponent)();
    })();
    static #_2 = (() => this.ɵcmp = /*@__PURE__*/core /* ɵɵdefineComponent */.VBU({
      type: OPCloudPrivacyPolicyComponent,
      selectors: [["opcloud-privacy-policy"]],
      decls: 172,
      vars: 0,
      consts: [[1, "privacy-policy-container"], [1, "privacy-header", 2, "font-size", "24px", "font-weight", "700"], [1, "privacy-text"], [1, "privacy-header"], [1, "privacy-bold"], [1, "privacy-text", 2, "font-style", "italic"], ["href", "https://edpb.europa.eu/about-edpb/about-edpb/members_en", 1, "privacy-link"], ["href", "https://ico.org.uk/make-a-complaint/", 1, "privacy-link"]],
      template: function OPCloudPrivacyPolicyComponent_Template(rf, ctx) {
        if (rf & 1) {
          core /* ɵɵelementStart */.j41(0, "div", 0)(1, "p", 1);
          core /* ɵɵtext */.EFF(2, " PRIVACY POLICY ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(3, "p", 2);
          core /* ɵɵtext */.EFF(4, " This Privacy Policy (\"Privacy Policy\") explains how information is collected and used by OPCloud Ltd. (\"OPCloud\" or \"we\", \"us\", \"our\"). ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(5, "p", 2);
          core /* ɵɵtext */.EFF(6, " This Privacy Policy applies to the data practices relating to the cloud-based modeling platform that OPCloud offers users. As a background, OPCloud has developed and operates a cloud-based platform, based on Object-Process Methodology (OPM) ISO:19450, offering the ability to design and develop conceptual and computational models for products, services, systems, and lifecycle management (the “Service”). ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(7, "p", 2);
          core /* ɵɵtext */.EFF(8, " We are committed to protecting and respecting data privacy. Please read this Privacy Policy carefully. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(9, "p", 3);
          core /* ɵɵtext */.EFF(10, " PERSONAL DATA PROCESSED ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(11, "p", 4);
          core /* ɵɵtext */.EFF(12, " We collect and process your Registration Information when you engage us to use our Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(13, "p", 2);
          core /* ɵɵtext */.EFF(14, " When you wish to register or log-in to our Service, we collect your login name (which can be your email address). You can also upload a URL of your profile photo at your choice. If you registered to the Service with a Microsoft or Google SSO account, we may process your company name as well. We refer to this as “Registration Information”. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(15, "p", 2);
          core /* ɵɵtext */.EFF(16, " You do not have a legal obligation to provide us with your Registration Information. However, if you choose to not share this information with us, we may not be able to respond to your inquiry or provide you the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(17, "p", 4);
          core /* ɵɵtext */.EFF(18, " We also collect Analytics Information and logs about your use of the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(19, "p", 2);
          core /* ɵɵtext */.EFF(20, " When you use our Service, we record and collect certain information about your interaction with the Service, including the date of your last access. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(21, "p", 2);
          core /* ɵɵtext */.EFF(22, " You may choose to join our log error mechanism which helps us in fixing such flaws and improve the Service. You can disable sharing those logs with us through the settings of your account. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(23, "p", 2);
          core /* ɵɵtext */.EFF(24, " We refer to this data as \"Analytics Information\". ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(25, "p", 3);
          core /* ɵɵtext */.EFF(26, " DATA CONTROLLER ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(27, "p", 4);
          core /* ɵɵtext */.EFF(28, " OPCloud is the data controller of all the information explained in this Privacy Policy. We determine the purposes and means of processing that data as part of our Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(29, "p", 2);
          core /* ɵɵtext */.EFF(30, " OPCloud is the data controller of all the information explained in this Privacy Policy. We determine the purposes and means of processing that data as part of our Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(31, "p", 3);
          core /* ɵɵtext */.EFF(32, " HOW WE PROCESS PERSONAL DATA ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(33, "p", 4);
          core /* ɵɵtext */.EFF(34, " To provide you with the Service: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(35, "p", 2);
          core /* ɵɵtext */.EFF(36, " We process Registration Information in order to give you access to use the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(37, "p", 4);
          core /* ɵɵtext */.EFF(38, " To maintain the Service: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(39, "p", 2);
          core /* ɵɵtext */.EFF(40, " We process the Analytics Information to provide, maintain and improve your user experience when accessing our Service. We also will use the Analytics Information for quality assurance and for the development and enhancement of the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(41, "p", 4);
          core /* ɵɵtext */.EFF(42, " To enforce these Terms and comply with applicable law and judicial orders: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(43, "p", 2);
          core /* ɵɵtext */.EFF(44, " We will use the Analytics Information to prevent fraud, resolve disputes, troubleshoot problems, assist with any investigations, enforce these Service’s Terms of Use and take other actions otherwise permitted by law. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(45, "p", 3);
          core /* ɵɵtext */.EFF(46, " WHO PROCESSES YOUR DATA ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(47, "p", 5);
          core /* ɵɵtext */.EFF(48, " We will not share your information with third parties, except in the events listed below or when you provide us your explicit and informed consent. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(49, "p", 4);
          core /* ɵɵtext */.EFF(50, " We will process information with our Service providers helping us to operate our Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(51, "p", 2);
          core /* ɵɵtext */.EFF(52, " We will process personal information with the assistance of our Service providers who assist us with the internal operations of the Service such as Google and Firebase. These companies are authorized to use your personal information in this context only as necessary to provide these Services to us and not for their own promotional purposes. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(53, "p", 4);
          core /* ɵɵtext */.EFF(54, " We will share information with competent authorities, if you abuse your right to use the Service, or violate any applicable law. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(55, "p", 2);
          core /* ɵɵtext */.EFF(56, " If you have abused your rights to use the Service, or violated any applicable law, we will share information with competent authorities and with third parties (such as legal counsels and advisors), for the purpose of handling of the violation or breach. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(57, "p", 4);
          core /* ɵɵtext */.EFF(58, " We will share your information if we are legally required. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(59, "p", 2);
          core /* ɵɵtext */.EFF(60, " We will share information if we are required to do so by a judicial, governmental, or regulatory authority. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(61, "p", 4);
          core /* ɵɵtext */.EFF(62, " We will share your Information with third parties in any event of change in our structure. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(63, "p", 2);
          core /* ɵɵtext */.EFF(64, " If the operation of our Service is organized within a different framework, or through another legal structure or entity (such as due to a merger or acquisition), we will share information only as required to enable the structural change in the operation of the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(65, "p", 3);
          core /* ɵɵtext */.EFF(66, " COOKIES ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(67, "p", 4);
          core /* ɵɵtext */.EFF(68, " What are cookies? ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(69, "p", 2);
          core /* ɵɵtext */.EFF(70, " Cookies are text files, comprised of small amount of data, that are saved on your computer or other device (e.g., smartphone, tablet, etc.) when you use the internet and visit various websites. The information that the cookies maintain is read by the website you visit, during the session of your visit to the website (these are called ‘session’ cookies) We do not use so-called ‘persistent’ cookies. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(71, "p", 4);
          core /* ɵɵtext */.EFF(72, " We use cookies necessary to operate the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(73, "p", 2);
          core /* ɵɵtext */.EFF(74, " We use only cookies that are strictly necessary for the functioning of the Service. These are cookies that help authenticate your access to the Service. The Service cannot operate properly without these cookies. You can set your browser to block or alert you about these cookies, but some parts of the Service may not function properly. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(75, "p", 4);
          core /* ɵɵtext */.EFF(76, " You can always delete or disable cookies. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(77, "p", 2);
          core /* ɵɵtext */.EFF(78, " You can always delete the cookies saved on your device through the settings of your computer browser or device. You can also disable cookies for future use through the settings of your computer browser or device. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(79, "p", 3);
          core /* ɵɵtext */.EFF(80, " SECURITY AND DATA RETENTION ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(81, "p", 4);
          core /* ɵɵtext */.EFF(82, " We generally will retain your Registration Information and Analytics Information for as long you use the Service and/or did not request to delete your account. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(83, "p", 2);
          core /* ɵɵtext */.EFF(84, " We will retain Registration Information and Analytics Information for the duration needed to support our ordinary activities in providing the Service to you and your organization. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(85, "p", 4);
          core /* ɵɵtext */.EFF(86, " We implement measures to secure your Information. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(87, "p", 2);
          core /* ɵɵtext */.EFF(88, " We implement measures to reduce the risks of damage, loss of information and unauthorized access or use of information. These include encryption for data in transit and at rest. However, these measures do not provide absolute information security. Therefore, although efforts are made to secure personal information, it is not guaranteed, and you cannot expect that the Service will be immune from information security risks. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(89, "p", 3);
          core /* ɵɵtext */.EFF(90, " INTERNATIONAL DATA TRANSFERS ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(91, "p", 4);
          core /* ɵɵtext */.EFF(92, " We will internationally transfer information in accordance with applicable data protection laws. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(93, "p", 2);
          core /* ɵɵtext */.EFF(94, " If we transfer your personal data for processing at locations outside your jurisdiction, we will abide by data transfer rules applicable to these situations. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(95, "p", 3);
          core /* ɵɵtext */.EFF(96, " ADDITIONAL INFORMATION FOR INDIVIDUALS IN THE EU or UK ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(97, "p", 4);
          core /* ɵɵtext */.EFF(98, " OPCloud is the data controller ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(99, "p", 2);
          core /* ɵɵtext */.EFF(100, " The following is the contact information of OPCloud, the data controller: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(101, "p", 2);
          core /* ɵɵtext */.EFF(102, " OPCloud Ltd. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(103, "p", 2);
          core /* ɵɵtext */.EFF(104, " 19th Bar-Ilan St. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(105, "p", 2);
          core /* ɵɵtext */.EFF(106, " Haifa, Israel, 2638439 ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(107, "p", 2);
          core /* ɵɵtext */.EFF(108, " Email: opcloud.support@opcloud.tech ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(109, "p", 4);
          core /* ɵɵtext */.EFF(110, " Legal basis under EU law for processing your personal data. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(111, "p", 2);
          core /* ɵɵtext */.EFF(112, " The legal basis for processing Registration Information to give you access to the Service is your and our legitimate interests in providing the Service you’ve signed up for. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(113, "p", 2);
          core /* ɵɵtext */.EFF(114, " The legal basis for processing Analytics Information is our legitimate interest in maintaining, developing, and enhancing the Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(115, "p", 2);
          core /* ɵɵtext */.EFF(116, " The legal basis for processing your Analytics Information for the purpose of handling instances of abusive use of the Service is our legitimate interests in defending and enforcing against violations and breaches that are harmful to our Service. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(117, "p", 2);
          core /* ɵɵtext */.EFF(118, " The legal basis for processing your information with authorities or where we are legally required to share it, is our legitimate interests in complying with mandatory legal requirements imposed on us. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(119, "p", 2);
          core /* ɵɵtext */.EFF(120, " The legal basis for processing your information in the event of a change in our corporate structure is our legitimate interests in our Service continuity. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(121, "p", 4);
          core /* ɵɵtext */.EFF(122, " You have certain rights to access, update or delete information, obtain a copy of your information, and object or restrict certain data processing activities. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(123, "p", 2);
          core /* ɵɵtext */.EFF(124, " If you are in the EU or UK, you have the following rights under the GDPR: ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(125, "p", 2);
          core /* ɵɵtext */.EFF(126, " Right to Access your personal data that we process and receive a copy of it.");
          core /* ɵɵelement */.nrm(127, "br")(128, "br");
          core /* ɵɵtext */.EFF(129, " Right to Rectify inaccurate personal data we have concerning you and to have incomplete personal data completed.");
          core /* ɵɵelement */.nrm(130, "br")(131, "br");
          core /* ɵɵtext */.EFF(132, " Right to Data Portability, that is, to receive the personal data that you provided to us, in a structured, commonly used, and machine-readable format. You have the right to transmit this data to another Service provider. Where technically feasible, you have the right that your personal data be transmitted directly from us to the Service provider you designate.");
          core /* ɵɵelement */.nrm(133, "br")(134, "br");
          core /* ɵɵtext */.EFF(135, " Right to Object, based on your particular situation, to use your personal data on the basis of our legitimate interest. However, we may override the objection if we demonstrate compelling legitimate grounds, or for the establishment, exercise of defense of legal claims. You may also object at any time to the use of your personal data for direct marketing purposes.");
          core /* ɵɵelement */.nrm(136, "br")(137, "br");
          core /* ɵɵtext */.EFF(138, " Right to Restrict the processing of your personal data (except for storing it) if you contest the accuracy of your personal data, for a period enabling us to verify its accuracy; if you believe that the processing is unlawful and you oppose the erasure of the personal data and request instead to restrict its use; if we no longer need the personal data for the purposes outlined in this Privacy Policy, but you require them to establish, exercise or defense relating to legal claims, or if you object to processing, pending the verification whether our legitimate grounds for processing override yours.");
          core /* ɵɵelement */.nrm(139, "br")(140, "br");
          core /* ɵɵtext */.EFF(141, " Right to be Forgotten. Under certain circumstances, such as when you object to us processing your data and we have no compelling legitimate grounds to override your objection, you have the right to ask us to erase your personal data. However, we may still process your personal data if it is necessary to comply with a legal obligation, we are subject to under laws in EU Member States or for the establishment, exercise or defense of legal claims.");
          core /* ɵɵelement */.nrm(142, "br")(143, "br");
          core /* ɵɵtext */.EFF(144, " If you wish to exercise any of these rights, please contact us at:");
          core /* ɵɵelement */.nrm(145, "br");
          core /* ɵɵtext */.EFF(146, " opcloud.support@opcloud.tech");
          core /* ɵɵelement */.nrm(147, "br")(148, "br");
          core /* ɵɵtext */.EFF(149, " We reserve the right to ask for reasonable evidence to verify your identity before we provide you with information. Where we are not able to provide you the information that you have asked for, we will explain the reason for this. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(150, "p", 4);
          core /* ɵɵtext */.EFF(151, " You have a right to submit a complaint to the relevant supervisory data protection authority. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(152, "p", 2);
          core /* ɵɵtext */.EFF(153, " Subject to applicable law, you have the right to lodge a complaint with your local data protection authority. If you are in the EU, then according to Article 77 of the GDPR, you can lodge a complaint to the supervisory authority, in particular in the Member State of your residence, place of work or place of an alleged infringement of the GDPR.");
          core /* ɵɵelement */.nrm(154, "br");
          core /* ɵɵtext */.EFF(155, " For a list of supervisory authorities in the EU, click ");
          core /* ɵɵelementStart */.j41(156, "a", 6);
          core /* ɵɵtext */.EFF(157, "here");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(158, ".");
          core /* ɵɵelement */.nrm(159, "br");
          core /* ɵɵtext */.EFF(160, " If you are in the UK, you can lodge a complaint to Information Commissioner’s Office (ICO) pursuant to the instructions provided ");
          core /* ɵɵelementStart */.j41(161, "a", 7);
          core /* ɵɵtext */.EFF(162, "here");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵtext */.EFF(163, ". ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(164, "p", 3);
          core /* ɵɵtext */.EFF(165, " CHANGES TO THIS PRIVACY NOTICE ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(166, "p", 4);
          core /* ɵɵtext */.EFF(167, " If we change this Privacy Policy, we will make efforts to proactively notify you of such changes. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(168, "p", 2);
          core /* ɵɵtext */.EFF(169, " From time to time, we may change this Privacy Policy. If we do so, we will make efforts to proactively notify you of such changes. In any event, the latest version of the Privacy Policy will always be accessible here. ");
          core /* ɵɵelementEnd */.k0s();
          core /* ɵɵelementStart */.j41(170, "p", 2);
          core /* ɵɵtext */.EFF(171, " Last Update: February 17, 2022 ");
          core /* ɵɵelementEnd */.k0s()();
        }
      },
      styles: [".privacy-policy-container[_ngcontent-%COMP%]{width:720px;padding:20px;border-radius:8px;box-shadow:0 0 10px #0000001a;font-family:Roboto,Helvetica Neue,sans-serif;line-height:1.5;display:block}.privacy-policy-container[_ngcontent-%COMP%]   .privacy-header[_ngcontent-%COMP%]{display:block;position:relative;margin-bottom:20px;font-style:normal;font-weight:500;font-size:20px;color:#1a3763;text-align:center}.privacy-policy-container[_ngcontent-%COMP%]   .privacy-bold[_ngcontent-%COMP%]{display:block;position:relative;font-style:normal;font-size:16px;color:#3b3b3b;font-weight:700}.privacy-policy-container[_ngcontent-%COMP%]   .privacy-text[_ngcontent-%COMP%]{display:block;position:relative;font-style:normal;font-weight:400;font-size:16px;color:#3b3b3b}.privacy-policy-container[_ngcontent-%COMP%]   .privacy-text[_ngcontent-%COMP%]   .privacy-link[_ngcontent-%COMP%]{color:#1a3763;text-decoration:underline}"]
    }))();
  }
  return OPCloudPrivacyPolicyComponent;
})();