import {expect,test} from 'bun:test';
import {COMANDOS} from './comandos';
import {crearEditor} from './estado';
import {dependencias} from './pruebas.test';
test('WP-13 DES§7.4 registro único tiene motivos acciones reales y atajos sin duplicación',async()=>{expect(COMANDOS.length).toBeGreaterThan(40);const claves=COMANDOS.filter(c=>c.atajo).map(c=>c.contexto+':'+c.atajo);expect(new Set(claves).size).toBe(claves.length);const d=dependencias(),ed=crearEditor({...d,reloj:d.reloj.ahora,temporizador:d.reloj});await ed.abrir(d.m.id);const c=COMANDOS.find(c=>c.id==='deshacer')!;expect(typeof c.disponible(ed.obtener())).toBe('string');ed.ejecutar({op:'renombrarModelo',args:{nombre:'Cambio'}});expect(c.disponible(ed.obtener())).toBe(true);c.ejecutar(ed);expect(ed.obtener().modelo!.nombre).toBe(d.m.nombre);ed.cerrar();});
import {despacharAtajo} from './atajos';
import {configuracion,ciclos} from './pruebas.test';
async function abierto(){const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);return {d,ed};}
test('WP-13 DES§7.4 subcontextoobjeto hereda F2 de cosa pero S es acción propia',async()=>{const {ed}=await abierto();ed.seleccionar({cosas:['o-2'],estados:[],enlaces:[],abanicos:[]});expect(despacharAtajo(ed,'objeto',{key:'F2'})).toBe(true);expect(ed.obtener().solicitud?.k).toBe('renombrar');expect(despacharAtajo(ed,'objeto',{key:'s'})).toBe(true);expect(ed.obtener().solicitud?.k).toBe('estado');ed.cerrar();await ciclos();});
for(const key of ['w','t','n','Tab','1','9'])test(`WP-13 DES§7.4 reservado navegadorCtrl+${key} nunca interceptado`,async()=>{const {ed}=await abierto();expect(despacharAtajo(ed,'global',{key,ctrlKey:true})).toBe(false);expect(ed.obtener().solicitud).toBeNull();ed.cerrar();await ciclos();});
test('WP-13 DES§7.4 letras en campos no crean; nombre/OPL conservan atajo propio',async()=>{const {ed}=await abierto();expect(despacharAtajo(ed,'lienzo',{key:'o',editable:true})).toBe(false);expect(despacharAtajo(ed,'nombre',{key:'Enter',editable:true})).toBe(true);expect(ed.obtener().solicitud).toMatchObject({k:'renombrar',opcion:'confirmar'});expect(despacharAtajo(ed,'editor-opl',{key:'Enter',ctrlKey:true,editable:true})).toBe(true);expect(ed.obtener().solicitud).toMatchObject({k:'opl',opcion:'aplicar'});expect(despacharAtajo(ed,'lienzo',{key:'p',isComposing:true})).toBe(false);ed.cerrar();await ciclos();});
test('WP-13 DES§7.4 modo modal no ejecuta mutación; cancelar tiene prioridad y motivo visible',async()=>{const {ed}=await abierto();ed.seleccionar({cosas:['o-2'],estados:[],enlaces:[],abanicos:[]});ed.fijarModo('gestion-modal');const c=COMANDOS.find(c=>c.id==='esencia')!;expect(typeof c.disponible(ed.obtener())).toBe('string');const m=ed.obtener().modelo;c.ejecutar(ed);expect(ed.obtener().modelo).toBe(m);ed.solicitar({k:'ayuda'});expect(despacharAtajo(ed,'global',{key:'Escape'})).toBe(true);expect(ed.obtener().solicitud).toBeNull();expect(ed.obtener().seleccion.cosas).toEqual(['o-2']);despacharAtajo(ed,'global',{key:'Escape'});expect(ed.obtener().seleccion.cosas).toEqual([]);ed.cerrar();await ciclos();});
test('T-015 DEC18 nombre de estadoShiftEnter confirma uno, nunca otro',async()=>{const {ed}=await abierto();ed.seleccionar({cosas:[],estados:['s-3'],enlaces:[],abanicos:[]});expect(despacharAtajo(ed,'nombre',{key:'Enter',shiftKey:true,editable:true})).toBe(true);expect(ed.obtener().solicitud?.opcion).toBe('confirmar');ed.cerrar();await ciclos();});
test('T-015 designaciónI alterna operación existente con estado real',async()=>{const {ed}=await abierto();ed.seleccionar({cosas:[],estados:['s-3'],enlaces:[],abanicos:[]});despacharAtajo(ed,'estado',{key:'i'});expect(inicial(ed)).toBe(true);despacharAtajo(ed,'estado',{key:'i'});expect(inicial(ed)).not.toBe(true);expect(ed.obtener().pasado).toHaveLength(2);ed.cerrar();await ciclos();});
test('WP-13 DES§7.4 tabla7.4 expone petición o efecto verificable en todos sus contextos',()=>{const pares=COMANDOS.map(c=>c.contexto+':'+c.atajo);for(const p of ['global:Ctrl+K','global:Ctrl+E','global:Alt+ArrowUp','global:Ctrl+0','global:Ctrl+\\','global:F9','lienzo:O','lienzo:P','objeto:S','proceso:D','subproceso:[','estado:I','estado:Shift+H','enlace:M','enlace:Shift+M','multiple:X','multiple:Shift+X','abanico:X','simbolo:I','modo-enlace:Tab','nombre:Shift+Enter','encadenando:Escape','menu-tipo:Tab','editor-opl:Ctrl+Enter','biblioteca:/'])expect(pares).toContain(p);});

function inicial(ed:ReturnType<typeof crearEditor>){const o=ed.obtener().modelo!.cosas['o-2']!;if(o.tipo!=='objeto')throw Error('objeto');return o.estados[0]!.inicial;}
test('WP-13 DES§7.4 letras de modo enlace solicitan destino y Espacio solicita pan',async()=>{
 const {ed}=await abierto();expect(despacharAtajo(ed,'modo-enlace',{key:'r'})).toBe(true);expect(ed.obtener().solicitud).toMatchObject({k:'enlace',texto:'r',opcion:'buscar-o-crear'});expect(despacharAtajo(ed,'global',{key:' '})).toBe(true);expect(ed.obtener().solicitud).toMatchObject({k:'camara',opcion:'desplazar'});ed.cerrar();await ciclos();
});
test('T-011 descomponer y completar cadena restauran juntos el padre en un paso',async()=>{
 const {ed}=await abierto();ed.seleccionar({cosas:['p-5'],estados:[],enlaces:[],abanicos:[]});expect(despacharAtajo(ed,'proceso',{key:'d'})).toBe(true);const hijo=ed.obtener().opd,solicitud=ed.obtener().solicitud;expect(solicitud?.gesto).toBeDefined();const r=ed.ejecutar({op:'agregarSubprocesos',args:{opd:hijo,bandas:[['Recibir']],posicion:'final'}},{gesto:solicitud!.gesto!});expect(r.ok).toBe(true);expect(ed.obtener().pasado).toHaveLength(1);ed.deshacer();expect(ed.obtener().modelo!.opds[hijo]).toBeUndefined();ed.cerrar();await ciclos();
});
test('T-011 controlE/C alterna mismo modificador y conserva ID enlace',async()=>{
 const {ed}=await abierto(),r=ed.ejecutar({op:'crearEnlace',args:{opd:ed.obtener().opd,candidato:{tipo:'consumo',objeto:'o-2',proceso:'p-5'}}});if(!r.ok)throw Error('enlace');const id=r.valor.creados[0]!;ed.seleccionar({cosas:[],estados:[],enlaces:[id],abanicos:[]});for(const key of ['e','c']){despacharAtajo(ed,'enlace',{key});expect(ed.obtener().modelo!.enlaces[id]).toMatchObject({control:key});despacharAtajo(ed,'enlace',{key});expect(ed.obtener().modelo!.enlaces[id]).not.toHaveProperty('control');}ed.cerrar();await ciclos();
});
test('T-247 panel minimizable vuelve al estado previo sin historial ni revisión',async()=>{
 const {ed}=await abierto(),m=ed.obtener().modelo,c=ed.obtener().camara,p=ed.obtener().paneles;for(const key of ['\\','.']){despacharAtajo(ed,'global',{key,ctrlKey:true});despacharAtajo(ed,'global',{key,ctrlKey:true});}expect(ed.obtener().paneles).toEqual(p);expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().camara).toBe(c);expect(ed.obtener().pasado).toEqual([]);ed.cerrar();await ciclos();
});
test('T-011 comandos attrs mover y abanicos realizan operaciones y revierten',async()=>{
 const {ed}=await abierto();ed.seleccionar({cosas:['o-2'],estados:[],enlaces:[],abanicos:[]});despacharAtajo(ed,'objeto',{key:'f',shiftKey:true});expect(ed.obtener().modelo!.cosas['o-2']!.esencia).toBe('informacional');despacharAtajo(ed,'objeto',{key:'a',shiftKey:true});expect(ed.obtener().modelo!.cosas['o-2']!.afiliacion).toBe('ambiental');const anterior=ed.obtener().modelo!.opds[ed.obtener().opd]!.apariciones['o-2']!;despacharAtajo(ed,'objeto',{key:'ArrowRight',shiftKey:true});expect(ed.obtener().modelo!.opds[ed.obtener().opd]!.apariciones['o-2']!.x).toBe(anterior.x+10);const ids:string[]=[];for(const proceso of ['p-5','p-6']){const r=ed.ejecutar({op:'crearEnlace',args:{opd:ed.obtener().opd,candidato:{tipo:'consumo',objeto:'o-2',proceso}}});if(!r.ok)throw Error(r.rechazo.mensaje);ids.push(r.valor.creados[0]!);}ed.seleccionar({cosas:[],estados:[],enlaces:ids,abanicos:[]});despacharAtajo(ed,'multiple',{key:'x'});const f=Object.values(ed.obtener().modelo!.abanicos)[0]!;expect(f.operador).toBe('XOR');expect(f.enlaces).toEqual(ids);ed.seleccionar({cosas:[],estados:[],enlaces:[],abanicos:[f.id]});despacharAtajo(ed,'abanico',{key:'x'});expect(ed.obtener().modelo!.abanicos[f.id]!.operador).toBe('OR');despacharAtajo(ed,'abanico',{key:'Delete'});expect(ed.obtener().modelo!.abanicos).toEqual({});expect(ids.every(id=>!!ed.obtener().modelo!.enlaces[id])).toBe(true);ed.cerrar();await ciclos();
});
test('WP-13 DES§7.4 fan no ofrecido está deshabilitado con motivo nuclear',async()=>{
 const {ed}=await abierto(),ids:string[]=[];for(const tipo of ['consumo','invocacion'] as const){const candidato=tipo==='consumo'?{tipo,objeto:'o-2',proceso:'p-5'}:{tipo,origen:'p-5',destino:'p-6'};const r=ed.ejecutar({op:'crearEnlace',args:{opd:ed.obtener().opd,candidato}});if(!r.ok)throw Error(r.rechazo.mensaje);ids.push(r.valor.creados[0]!);}ed.seleccionar({cosas:[],estados:[],enlaces:ids,abanicos:[]});const c=COMANDOS.find(c=>c.id==='abanico-XOR')!,m=ed.obtener().modelo;expect(typeof c.disponible(ed.obtener())).toBe('string');c.ejecutar(ed);expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().modelo!.abanicos).toEqual({});ed.cerrar();await ciclos();
});

test('T-251 Supr múltiple solicita quitar capturando cosas y OPD sin mutación',async()=>{
 const {ed}=await abierto();ed.seleccionar({cosas:['o-2','p-5'],estados:[],enlaces:[],abanicos:[]});const m=ed.obtener().modelo,opd=ed.obtener().opd;COMANDOS.find(c=>c.id==='quitar')!.ejecutar(ed);expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().pasado).toEqual([]);expect(ed.obtener().solicitud).toEqual({k:'tipo',opcion:'confirmar-quitar',refs:[{tipo:'cosa',id:'o-2'},{tipo:'cosa',id:'p-5'},{tipo:'opd',id:opd}]});ed.seleccionar({cosas:['p-6'],estados:[],enlaces:[],abanicos:[]});expect(ed.obtener().solicitud?.refs).toEqual([{tipo:'cosa',id:'o-2'},{tipo:'cosa',id:'p-5'},{tipo:'opd',id:opd}]);COMANDOS.find(c=>c.id==='cancelar')!.ejecutar(ed);expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().solicitud).toBeNull();ed.cerrar();await ciclos();
});
