import {expect,test} from 'bun:test';
import {crearEditor} from './estado';
import {dependencias} from './pruebas.test';
import type {Plan} from '../opl/planificar';
import {exportarV0} from '../codec/exportar';
test('T-011 ejecutar conserva un commit gesto e historial de modelo real',async()=>{const d=dependencias(),ed=crearEditor({...d,reloj:d.reloj.ahora,temporizador:d.reloj});await ed.abrir(d.m.id);const original=ed.obtener().modelo!;ed.seleccionar({cosas:['o-2'],estados:[],enlaces:[],abanicos:[]});const seleccion=ed.obtener().seleccion;expect(ed.ejecutar({op:'renombrarCosa',args:{cosa:'o-2',nombre:'Pedido nuevo'}},{gesto:'drag-uno'}).ok).toBe(true);expect(ed.ejecutar({op:'renombrarCosa',args:{cosa:'o-2',nombre:'Pedido final'}},{gesto:'drag-uno'}).ok).toBe(true);expect(ed.obtener().pasado).toHaveLength(1);ed.deshacer();expect(ed.obtener().modelo).toBe(original);expect(ed.obtener().seleccion).toEqual(seleccion);ed.rehacer();expect(ed.obtener().modelo!.cosas['o-2']!.nombre).toBe('Pedido final');ed.cerrar();});
test('T-011 aplicarOpl usa Plan manual como un paso y rollback nuclear real',async()=>{const d=dependencias(),ed=crearEditor({...d,reloj:d.reloj.ahora,temporizador:d.reloj});await ed.abrir(d.m.id);const base=ed.obtener().modelo!,camara=ed.obtener().camara;const plan:Plan={base,alcance:'modelo',lineas:[],notas:[],resumen:{total:0,aplicables:0,noAplicables:0,ignoradas:0,sinCambio:0},acciones:[{op:'renombrarModelo',args:{nombre:'Desde plan manual'}}]};expect(ed.aplicarOpl(plan).ok).toBe(true);expect(ed.obtener().pasado).toHaveLength(1);expect(ed.obtener().camara).toEqual(camara);ed.deshacer();expect(exportarV0(ed.obtener().modelo!)).toBe(exportarV0(base));const r=ed.ejecutarVarias([{op:'renombrarModelo',args:{nombre:'No debe quedar'}},{op:'crearEnlace',args:{opd:base.raiz,candidato:{tipo:'consumo',objeto:'inexistente',proceso:'p-5'}}}],'todo o nada');expect(r.ok).toBe(false);expect(ed.obtener().modelo).toBe(base);expect(ed.obtener().pasado).toHaveLength(0);ed.cerrar();});
import {configuracion,ciclos} from './pruebas.test';
import {descomponer} from '../nucleo/refinamiento';
import {generarModelo} from '../opl/generar';
import {planificar} from '../opl/planificar';
test('T-011 historial limita200 pasos, gesto distinto separa y nueva edición borra futuro',async()=>{const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);for(let i=0;i<205;i++)expect(ed.ejecutar({op:'renombrarModelo',args:{nombre:'Modelo '+i}},{gesto:'g'+i}).ok).toBe(true);expect(ed.obtener().pasado).toHaveLength(200);ed.deshacer();expect(ed.obtener().futuro).toHaveLength(1);ed.ejecutar({op:'renombrarModelo',args:{nombre:'Otra rama'}});expect(ed.obtener().futuro).toHaveLength(0);ed.cerrar();await ciclos();});
test('T-011 T-231 deshacer restaura OPD/selección previa y navegación no modifica historial',async()=>{const d=dependencias(),p=Object.values(d.m.cosas).find(c=>c.nombre==='Preparar')!;const r=descomponer(d.m,{opd:d.m.raiz,proceso:p.id,bandas:[['Recibir'],['Despachar']]});expect(r.ok).toBe(true);if(!r.ok)throw Error('fixture');d.documento(exportarV0(r.valor.modelo));const ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);const hijo=r.valor.creados[0]!,base=ed.obtener().modelo!;ed.navegar(hijo);ed.seleccionar({cosas:[p.id],estados:[],enlaces:[],abanicos:[]});const seleccion=ed.obtener().seleccion,camara=ed.obtener().camara;ed.ejecutar({op:'renombrarModelo',args:{nombre:'Cambio hijo'}});ed.navegar(base.raiz);ed.deshacer();expect(ed.obtener().opd).toBe(hijo);expect(ed.obtener().seleccion).toEqual(seleccion);expect(ed.obtener().modelo).toBe(base);expect(ed.obtener().camara).not.toBe(camara);expect(ed.obtener().guardado).toBe('pendiente');ed.cerrar();await ciclos();});
test('T-011 lineasNuevas usa IDs y texto real; limpieza2000ms y cámara efímera',async()=>{const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);const viejo=new Map(generarModelo(ed.obtener().modelo!).map(l=>[l.id,l.texto])),camara=ed.obtener().camara;ed.ejecutar({op:'renombrarCosa',args:{cosa:'o-2',nombre:'Pedido distinto'}});expect(ed.obtener().lineasNuevas).toEqual(generarModelo(ed.obtener().modelo!).filter(l=>viejo.get(l.id)!==l.texto).map(l=>l.id));expect(ed.obtener().lineasNuevas.length).toBeGreaterThan(0);expect(ed.obtener().camara).toBe(camara);await d.reloj.avanzar(1999);expect(ed.obtener().lineasNuevas.length).toBeGreaterThan(0);await d.reloj.avanzar(1);expect(ed.obtener().lineasNuevas).toEqual([]);const m=ed.obtener().modelo;ed.realzar([{tipo:'cosa',id:'o-2'}]);ed.fijarCamara({x:10,y:20,zoom:1.2});ed.fijarVista({numeracion:true});ed.fijarPaneles({arbol:false});expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().pasado).toHaveLength(1);ed.cerrar();await ciclos();});
test('T-196 plan real sin cambio conserva identidad y no agrega historial',async()=>{const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);const base=ed.obtener().modelo!,p=planificar(base,'modelo',generarModelo(base).map(l=>l.texto).join('\n'));expect(p.acciones).toEqual([]);expect(ed.aplicarOpl(p).ok).toBe(true);expect(ed.obtener().modelo).toBe(base);expect(ed.obtener().pasado).toEqual([]);ed.fijarModo('navegacion');expect(ed.ejecutar({op:'renombrarModelo',args:{nombre:'No permitido'}}).ok).toBe(false);expect(ed.obtener().modelo).toBe(base);ed.cerrar();await ciclos();});
import {escena} from '../opd/escena';
test('T-231 deshacer a otroOPD encuadra bbox del restaurado y conserva zoomnormal',async()=>{
 const d=dependencias(),r=descomponer(d.m,{opd:d.m.raiz,proceso:'p-5',bandas:[['Recibir'],['Entregar']]});if(!r.ok)throw Error('fixture');d.documento(exportarV0(r.valor.modelo));const ed=crearEditor({...configuracion(d),tamano:()=>({ancho:800,alto:600})});await ed.abrir(d.m.id);const hijo=r.valor.creados[0]!;ed.navegar(hijo);const deseada=ed.obtener().camara;ed.ejecutar({op:'renombrarModelo',args:{nombre:'Cambio'}});ed.navegar(d.m.raiz);ed.fijarCamara({x:9000,y:9000,zoom:3});ed.deshacer();expect(ed.obtener().opd).toBe(hijo);expect(ed.obtener().camara).toEqual(deseada);ed.cerrar();await ciclos();
});
test('WP-13 DES§6.6 crear fuera de vista mueve mínimo cámara sin modificar posición',async()=>{
 const d=dependencias(),ed=crearEditor({...configuracion(d),tamano:()=>({ancho:800,alto:600})});await ed.abrir(d.m.id);ed.fijarCamara({x:0,y:0,zoom:1});const r=ed.ejecutar({op:'crearCosa',args:{opd:d.m.raiz,tipo:'objeto',nombre:'Remoto',x:2000,y:1800}});expect(r.ok).toBe(true);if(!r.ok)throw Error('creación');const id=r.valor.creados[0]!,n=escena(ed.obtener().modelo!,d.m.raiz).nodos.find(n=>n.ref.id===id)!,c=ed.obtener().camara;expect(n.caja.x+c.x).toBeGreaterThanOrEqual(0);expect(n.caja.x+n.caja.ancho+c.x).toBeLessThanOrEqual(800);expect(n.caja.y+n.caja.alto+c.y).toBeLessThanOrEqual(600);expect(c.zoom).toBe(1);expect(ed.obtener().modelo!.opds[d.m.raiz]!.apariciones[id]).toMatchObject({x:2000,y:1800});ed.cerrar();await ciclos();
});
test('T-016 franja conserva traza nuclear al reemplazar designación por defecto',async()=>{
 const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);ed.ejecutar({op:'designar',args:{estado:'s-3',designacion:'porDefecto',activa:true}});const r=ed.ejecutar({op:'designar',args:{estado:'s-4',designacion:'porDefecto',activa:true}});expect(r.ok).toBe(true);if(!r.ok)throw Error('designacion');expect(r.trazas.length).toBeGreaterThan(0);expect(ed.obtener().franja!.trazas).toEqual(r.trazas);expect(ed.obtener().franja!.tipo).toBe('info');const n=ed.obtener().pasado.length,m=ed.obtener().modelo;const rechazado=ed.ejecutar({op:'renombrarCosa',args:{cosa:'o-2',nombre:'inválido!'}});expect(rechazado.ok).toBe(false);if(!rechazado.ok){expect(ed.obtener().franja!.regla).toBe(rechazado.rechazo.regla);expect(ed.obtener().franja!.texto).toBe(rechazado.rechazo.mensaje);}expect(ed.obtener().modelo).toBe(m);expect(ed.obtener().pasado).toHaveLength(n);ed.cerrar();await ciclos();
});
