import {expect,test} from 'bun:test';
import {reducirGesto} from './gestos';
import {modelo} from './pruebas.test';
import {aplicarAcciones} from '../nucleo/operaciones';
test('T-011 crear por gesto produce operación real y cancelación no muta',()=>{const m=modelo(),entrada=JSON.stringify(m),g={k:'creando' as const,tipo:'objeto' as const,en:{x:34,y:56},nombre:'Registro'};const r=reducirGesto(m,m.raiz,g,{k:'tecla',tecla:'Enter',mayus:false,ctrl:false,alt:false});expect(r.acciones).toEqual([{op:'crearCosa',args:{opd:m.raiz,tipo:'objeto',nombre:'Registro',x:34,y:56}}]);const n=aplicarAcciones(m,r.acciones);expect(n.ok).toBe(true);expect(reducirGesto(m,m.raiz,g,{k:'tecla',tecla:'Escape',mayus:false,ctrl:false,alt:false}).acciones).toEqual([]);expect(JSON.stringify(m)).toBe(entrada);});
test('T-011 drag múltiple emite una operación y gesto distinto conserva separación',()=>{const m=modelo(),g={k:'arrastrando' as const,cosas:['o-2'],desde:{x:0,y:0},delta:{x:11,y:9}};const r=reducirGesto(m,m.raiz,g,{k:'arriba',punto:{x:11,y:9},mayus:false});expect(r.acciones).toHaveLength(1);expect(r.acciones[0]!.op).toBe('moverApariciones');expect(r.gestoId).toBeDefined();});
import {descomponer} from '../nucleo/refinamiento';
import {tiposLegales} from '../nucleo/matriz';
import {validarForma} from '../nucleo/forma';
const enter=(mayus=false)=>({k:'tecla' as const,tecla:'Enter',mayus,ctrl:false,alt:false});
test('T-011 DEC18 agregar estado confirma uno inclusoShiftEnter sin encadenar',()=>{const m=modelo(),g={k:'estado',objeto:'o-2',nombre:'pagado',id:'s-uno'} as any;const r=reducirGesto(m,m.raiz,g,enter(true));expect(r.gesto).toEqual({k:'reposo'});expect(r.acciones).toEqual([{op:'agregarEstado',args:{objeto:'o-2',nombre:'pagado'}}]);expect(r.gestoId).toBe('s-uno');const n=aplicarAcciones(m,r.acciones);expect(n.ok).toBe(true);if(n.ok)expect(n.valor.modelo.cosas['o-2']!.tipo==='objeto'&&n.valor.modelo.cosas['o-2']!.estados).toHaveLength(3);});
test('T-011 nombre inválido jamás emite creación ni reserva identidad',()=>{const m=modelo(),g={k:'creando' as const,tipo:'objeto' as const,en:{x:0,y:0},nombre:'nombre inválido!'};const r=reducirGesto(m,m.raiz,g,enter());expect(r.acciones).toEqual([]);expect(r.gesto.k).toBe('creando');});
test('T-011 conectar consulta matriz real conserva opcioneslegales/ilegales y otra orientación',()=>{const m=modelo(),g={k:'conectando' as const,desde:{cosa:'o-2',estado:'s-3'},punto:{x:0,y:0},sobre:{cosa:'p-5'},id:'conexion-1'},r=reducirGesto(m,m.raiz,g,enter());expect(r.gesto.k).toBe('menuTipo');if(r.gesto.k!=='menuTipo')throw Error('menu');expect(r.gesto.opciones).toEqual(tiposLegales(m,{opd:m.raiz,desde:g.desde,hacia:g.sobre}));const posicion=r.gesto.opciones.findIndex(o=>o.legal===true&&o.tipo==='consumo');expect(posicion).toBeGreaterThanOrEqual(0);const elegido=reducirGesto(m,m.raiz,r.gesto,{k:'elegir',indice:posicion});expect(aplicarAcciones(m,elegido.acciones).ok).toBe(true);const negativo=r.gesto.opciones.findIndex(o=>o.legal===false&&!o.alternativa);expect(negativo).toBeGreaterThanOrEqual(0);expect(reducirGesto(m,m.raiz,r.gesto,{k:'elegir',indice:negativo}).acciones).toEqual([]);const invertido=reducirGesto(m,m.raiz,r.gesto,{k:'tecla',tecla:'Tab',mayus:false,ctrl:false,alt:false});expect(invertido.gesto).toMatchObject({desde:g.sobre,hacia:g.desde});});
test('T-011 reanclar conservaID y destinoestado real sin mutar entrada',()=>{const b=modelo(),m={...b,enlaces:{e:{id:'e',tipo:'consumo' as const,objeto:'o-2',proceso:'p-5'}}},g={k:'reanclando' as const,enlace:'e',extremo:'origen' as const,punto:{x:0,y:0},id:'reancla-1'},before=JSON.stringify(m);const r=reducirGesto(m,m.raiz,g,{k:'arriba',punto:{x:0,y:0},sobre:'estado:s-3',mayus:false});expect(r.acciones).toEqual([{op:'reanclarExtremo',args:{opd:m.raiz,enlace:'e',extremo:'origen',hacia:{cosa:'o-2',estado:'s-3'}}}]);const n=aplicarAcciones(m,r.acciones);expect(n.ok).toBe(true);if(n.ok)expect(n.valor.modelo.enlaces.e).toMatchObject({id:'e',estado:'s-3'});expect(JSON.stringify(m)).toBe(before);});
test('WP-13 DES§7.3 banda real y nombres encadenados consumen operaciones atómicas',()=>{const b=modelo(),r=descomponer(b,{opd:b.raiz,proceso:'p-5',bandas:[['Recibir'],['Entregar']]});expect(r.ok).toBe(true);if(!r.ok)throw Error('fixture');const m=r.valor.modelo,opd=r.valor.creados[0]!,o=m.opds[opd]!;if(o.tipo!=='descomposicion')throw Error('tipo');const g={k:'banda' as const,proceso:o.bandas[0]![0]!,destino:{banda:1},id:'banda-1'},p=reducirGesto(m,opd,g,enter());expect(p.acciones[0]?.op).toBe('moverSubproceso');expect(aplicarAcciones(m,p.acciones).ok).toBe(true);let c:any={k:'encadenando',opd,bandas:[],actual:'Archivar',modo:'subprocesos',id:'cadena-1'};c=reducirGesto(m,opd,c,enter()).gesto;c=reducirGesto(m,opd,c,{k:'nombre',nombre:'Validar'}).gesto;c=reducirGesto(m,opd,c,enter(true)).gesto;const final=reducirGesto(m,opd,c,{k:'tecla',tecla:'Escape',ctrl:false,alt:false,mayus:false});expect(final.acciones).toEqual([{op:'agregarSubprocesos',args:{opd,bandas:[['Archivar','Validar']],posicion:'final'}}]);expect(final.gestoId).toBe('cadena-1');const n=aplicarAcciones(m,final.acciones);expect(n.ok).toBe(true);if(n.ok)expect(validarForma(n.valor.modelo)).toEqual([]);});
for(const zoom of [.2,1,3])test(`WP-13 DES§7.3 zoomcursor ${zoom} y pan no alteran Modelo`,()=>{const m=modelo(),antes=JSON.stringify(m),camara={x:20,y:-15,zoom},punto={x:131,y:247};for(const dy of [-1,1]){const r=reducirGesto(m,m.raiz,{k:'reposo'},{k:'rueda',dx:0,dy,ctrl:true,punto,camara});expect(r.camara!.zoom).toBeGreaterThanOrEqual(.2);expect(r.camara!.zoom).toBeLessThanOrEqual(3);expect((punto.x-r.camara!.x)/r.camara!.zoom).toBeCloseTo((punto.x-camara.x)/zoom,9);expect((punto.y-r.camara!.y)/r.camara!.zoom).toBeCloseTo((punto.y-camara.y)/zoom,9);expect(r.acciones).toEqual([]);}const pan=reducirGesto(m,m.raiz,{k:'reposo'},{k:'rueda',dx:10,dy:20,ctrl:false,punto,camara});expect(pan.camara).toEqual({x:10,y:-35,zoom});expect(JSON.stringify(m)).toBe(antes);});
test('WP-13 DES§7.3 Espacioarrastre deriva cámara sin coordenadas persistidas',()=>{const m=modelo(),g={k:'desplazando',desde:{x:50,y:60},camara:{x:20,y:30,zoom:1},id:'pan-1'} as any;const r=reducirGesto(m,m.raiz,g,{k:'mover',punto:{x:80,y:100},mayus:false});expect(r.camara).toEqual({x:50,y:70,zoom:1});expect(r.acciones).toEqual([]);});
test('T-011 IDs explícitos de gesto separan arrastres idénticos',()=>{const m=modelo(),g={k:'arrastrando' as const,cosas:['o-2'],desde:{x:0,y:0},delta:{x:1,y:2}};const a=reducirGesto(m,m.raiz,{...g,id:'drag-a'},{k:'arriba',punto:{x:1,y:2},mayus:false}),b=reducirGesto(m,m.raiz,{...g,id:'drag-b'},{k:'arriba',punto:{x:1,y:2},mayus:false});expect(a.gestoId).not.toBe(b.gestoId);});

test('T-011 OR válido conserva nombre y gates al aplicar creación',()=>{const m=modelo(),g={k:'creando' as const,tipo:'objeto' as const,en:{x:1,y:2},nombre:'OR'},r=reducirGesto(m,m.raiz,g,enter());expect(r.acciones).toEqual([{op:'crearCosa',args:{opd:m.raiz,tipo:'objeto',nombre:'OR',x:1,y:2}}]);const a=aplicarAcciones(m,r.acciones);expect(a.ok).toBe(true);if(a.ok){const id=a.valor.creados[0]!;expect(a.valor.modelo.cosas[id]!.nombre).toBe('OR');expect(a.valor.modelo.opds[m.raiz]!.apariciones[id]).toMatchObject({x:1,y:2});}});
test('WP-13 DES§7.4 menú teclado recorre opciones y confirma/dígito legal',()=>{
 const m=modelo(),opciones=tiposLegales(m,{opd:m.raiz,desde:{cosa:'o-2'},hacia:{cosa:'p-5'}}),g={k:'menuTipo' as const,desde:{cosa:'o-2'},hacia:{cosa:'p-5'},opciones,id:'menu',elegida:0};
 const r=reducirGesto(m,m.raiz,g,{k:'tecla',tecla:'ArrowDown',mayus:false,ctrl:false,alt:false});expect(r.gesto).toMatchObject({elegida:1});const j=opciones.findIndex(o=>o.legal===true);expect(j).toBeGreaterThanOrEqual(0);const elegido=reducirGesto(m,m.raiz,{...g,elegida:j},enter());expect(elegido.acciones).toHaveLength(1);expect(aplicarAcciones(m,elegido.acciones).ok).toBe(true);if(j<9)expect(reducirGesto(m,m.raiz,g,{k:'tecla',tecla:String(j+1),mayus:false,ctrl:false,alt:false}).acciones).toEqual(elegido.acciones);
});
test('WP-13 DES§7.4 Tab en conexión elige sólo destino con opción nuclear legal',()=>{
 const m=modelo(),g={k:'conectando' as const,desde:{cosa:'o-2'},punto:{x:0,y:0}},r=reducirGesto(m,m.raiz,g,{k:'tecla',tecla:'Tab',mayus:false,ctrl:false,alt:false});expect(r.gesto.k).toBe('conectando');if(r.gesto.k!=='conectando')throw Error('contexto');expect(r.gesto.sobre).toBeDefined();expect(tiposLegales(m,{opd:m.raiz,desde:g.desde,hacia:r.gesto.sobre!}).some(o=>o.legal===true)).toBe(true);
});
test('T-011 arrastres sin ID explícito no fusionan movimientos sucesivos',()=>{
 const m=modelo(),g={k:'arrastrando' as const,cosas:['o-2'],desde:{x:0,y:0},delta:{x:1,y:0}},a=reducirGesto(m,m.raiz,g,{k:'arriba',punto:{x:1,y:0},mayus:false}),n=aplicarAcciones(m,a.acciones);expect(n.ok).toBe(true);if(!n.ok)throw Error('drag');const b=reducirGesto(n.valor.modelo,m.raiz,g,{k:'arriba',punto:{x:1,y:0},mayus:false});expect(a.gestoId).not.toBe(b.gestoId);
});
test('T-011 resize aplica núcleo real y todas cancelaciones conservan modelo',()=>{
 const m=modelo(),g={k:'redimensionando' as const,cosa:'o-2',caja:{x:0,y:0,ancho:300,alto:220},id:'resize'},antes=JSON.stringify(m),r=reducirGesto(m,m.raiz,g,{k:'arriba',punto:{x:0,y:0},mayus:false});expect(r.acciones).toEqual([{op:'redimensionar',args:{opd:m.raiz,cosa:'o-2',ancho:300,alto:220}}]);expect(aplicarAcciones(m,r.acciones).ok).toBe(true);for(const estado of [g,{k:'conectando' as const,desde:{cosa:'o-2'},punto:{x:0,y:0}},{k:'encadenando' as const,opd:m.raiz,bandas:[],actual:'',modo:'refinadores' as const},{k:'estado' as const,objeto:'o-2',nombre:'pagado'}])expect(reducirGesto(m,m.raiz,estado,{k:'tecla',tecla:'Escape',mayus:false,ctrl:false,alt:false}).acciones).toEqual([]);expect(JSON.stringify(m)).toBe(antes);
});
test('T-011 alternativaCompletarCambio usa enlace existente y estados exactos',()=>{
 const base=modelo(),m={...base,enlaces:{e:{id:'e',tipo:'efecto' as const,objeto:'o-2',proceso:'p-5',entrada:'s-3'}}},desde={cosa:'p-5'},hacia={cosa:'o-2',estado:'s-4'},opciones=tiposLegales(m,{opd:m.raiz,desde,hacia}),i=opciones.findIndex(o=>o.legal===false&&o.alternativa?.k==='completarCambio');expect(i).toBeGreaterThanOrEqual(0);const r=reducirGesto(m,m.raiz,{k:'menuTipo',desde,hacia,opciones},{k:'elegir',indice:i});expect(r.acciones[0]?.op).toBe('fijarEstados');const a=aplicarAcciones(m,r.acciones);expect(a.ok).toBe(true);if(a.ok)expect(a.valor.modelo.enlaces.e).toMatchObject({id:'e',entrada:'s-3',salida:'s-4'});
});
test('T-011 ShiftEnter de cosa propone el siguiente campo100px debajo',()=>{
 const m=modelo(),r=reducirGesto(m,m.raiz,{k:'creando',tipo:'objeto',en:{x:10,y:20},nombre:'Registro',id:'crear-1'},enter(true));expect(r.gesto).toMatchObject({k:'creando',en:{x:10,y:120},nombre:''});expect(r.acciones).toHaveLength(1);
});
test('WP-13 DES§7.3 Enter vacío termina cadena confirmada como Escape',()=>{
 const b=modelo(),d=descomponer(b,{opd:b.raiz,proceso:'p-5'});if(!d.ok)throw Error('fixture');const m=d.valor.modelo,opd=d.valor.creados[0]!,g={k:'encadenando' as const,opd,bandas:[['Recibir'],['Entregar']],actual:'',modo:'subprocesos' as const,id:'cadena-vacia'};const e=reducirGesto(m,opd,g,enter()),esc=reducirGesto(m,opd,g,{k:'tecla',tecla:'Escape',mayus:false,ctrl:false,alt:false});expect(e.acciones).toEqual(esc.acciones);expect(e.gesto).toEqual({k:'reposo'});expect(aplicarAcciones(m,e.acciones).ok).toBe(true);
});
test('T-011 crear subproceso en banda explícita consume operación nuclear y mantiene paralelo',()=>{
 const base=modelo(),r=descomponer(base,{opd:base.raiz,proceso:'p-5',bandas:[['Recibir'],['Entregar']]});if(!r.ok)throw Error('fixture');const m=r.valor.modelo,opd=r.valor.creados[0]!,o=m.opds[opd]!;if(o.tipo!=='descomposicion')throw Error('tipo');const caja=o.apariciones[o.cosa]!,g={k:'creando' as const,tipo:'proceso' as const,nombre:'Validar',en:{x:caja.x+60,y:caja.y+80},banda:{indice:0,paralelo:true},id:'nuevo-sub'};const p=reducirGesto(m,opd,g,enter()),n=aplicarAcciones(m,p.acciones);expect(n.ok).toBe(true);if(!n.ok)throw Error(n.rechazo.mensaje);const hijo=n.valor.modelo.opds[opd]!;if(hijo.tipo!=='descomposicion')throw Error('tipo');expect(hijo.bandas).toHaveLength(2);expect(hijo.bandas[0]).toEqual([o.bandas[0]![0]!,n.valor.creados[0]!]);expect(validarForma(n.valor.modelo)).toEqual([]);
});
