import {expect,test} from 'bun:test';
import {crearEditor} from './estado';
import {crearCliente} from './cliente';
import {dependencias} from './pruebas.test';
test('WP-13 DES§8.4 cliente transmite CAS cookies CSRF y versión en error',async()=>{const llamadas:any[]=[];const c=crearCliente((async(u,init)=>{llamadas.push([u,init]);return new Response(JSON.stringify({error:'Revisión desactualizada',rev:'b'.repeat(64)}),{status:412,headers:{'X-Opforja-Version':'bundle-B'}});}) as typeof fetch);expect(await c.guardar('m-prueba','texto','a'.repeat(64),{respaldo:true})).toEqual({conflicto:'b'.repeat(64)});expect(llamadas[0][0]).toBe('/api/modelos/m-prueba?respaldo=1');expect(new Headers(llamadas[0][1].headers).get('If-Match')).toBe('"'+ 'a'.repeat(64)+'"');expect(new Headers(llamadas[0][1].headers).get('X-Opforja')).toBe('1');expect(llamadas[0][1].credentials).toBe('same-origin');expect(c.versionServidor()).toBe('bundle-B');});
test('WP-13 DES§8.4 autoguardado respeta1500ms y borrador500ms con scheduler sensible',async()=>{const d=dependencias(),ed=crearEditor({...d,reloj:d.reloj.ahora,temporizador:d.reloj} as any);await ed.abrir(d.m.id);ed.ejecutar({op:'renombrarModelo',args:{nombre:'Editado'}});await d.reloj.avanzar(499);expect(d.peticiones.filter(p=>p.tipo==='PUT')).toHaveLength(0);await d.reloj.avanzar(1);expect(d.borradores.has(d.m.id)).toBe(true);await d.reloj.avanzar(999);expect(d.peticiones.filter(p=>p.tipo==='PUT')).toHaveLength(0);await d.reloj.avanzar(1);expect(d.peticiones.filter(p=>p.tipo==='PUT')).toHaveLength(1);expect(ed.obtener().guardado).toBe('guardado');ed.cerrar();});
import {configuracion,ciclos,diferida} from './pruebas.test';
import {crearAlmacenLocal} from './guardado';
import {exportarV0} from '../codec/exportar';
import {crearModelo} from '../nucleo/modelo';
const cambiar=(ed:ReturnType<typeof crearEditor>,nombre='Cambiado')=>ed.ejecutar({op:'renombrarModelo',args:{nombre}});
async function abierto(){const d=dependencias(),ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);return {d,ed};}
test('WP-13 DES§8.4 edición continua guarda como máximo10000ms sin debounce del borrador',async()=>{const {d,ed}=await abierto();for(let i=0;i<10;i++){cambiar(ed,'Continuo '+i);await d.reloj.avanzar(1000);if(i<9)expect(d.peticiones.filter(p=>p.tipo==='PUT')).toHaveLength(0);}expect(d.peticiones.filter(p=>p.tipo==='PUT')).toHaveLength(1);expect(d.borradores.size).toBe(0);ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 PUT en curso conserva edición nueva,borrador y CAS enviado; sólo un vuelo',async()=>{const {d,ed}=await abierto(),q=diferida<{rev:string}>(),envios:any[]=[];d.cliente.guardar=async(id,texto,rev,o)=>{envios.push({id,texto,rev,o});return envios.length===1?q.promesa:{rev:'c'.repeat(64)};};cambiar(ed,'A');const p=ed.guardarAhora();await ciclos();cambiar(ed,'B');await d.reloj.avanzar(500);expect(envios).toHaveLength(1);expect(envios[0].rev).toBe('a'.repeat(64));expect(JSON.parse(envios[0].texto).modelo.nombre).toBe('A');q.resolver({rev:'b'.repeat(64)});await p;expect(ed.obtener().guardado).toBe('pendiente');expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');await d.reloj.avanzar(1000);expect(envios).toHaveLength(2);expect(envios[1].rev).toBe('b'.repeat(64));expect(JSON.parse(envios[1].texto).modelo.nombre).toBe('B');ed.cerrar();await ciclos();});
for(const opcion of ['conservar-mios','usar-guardada'] as const)test(`WP-13 DES§8.4 CAS412 resolución ${opcion} preserva modelo local`,async()=>{const {d,ed}=await abierto(),calls:any[]=[];d.cliente.guardar=async(id,texto,rev,o)=>{calls.push({k:'PUT',id,texto,rev,o});return calls.length===1?{conflicto:'f'.repeat(64)}:{rev:'g'.repeat(64)};};d.cliente.crear=async texto=>{calls.push({k:'POST',texto});return {id:JSON.parse(texto).modelo.id,rev:'c'.repeat(64)};};const leer=d.cliente.leer;d.cliente.leer=async id=>{calls.push({k:'GET',id});return leer(id);};cambiar(ed,'Mío');await ed.guardarAhora();expect(ed.obtener().guardado).toBe('conflicto');expect(ed.obtener().modo).toBe('navegacion');expect(d.borradores.has(d.m.id)).toBe(true);await ed.resolverConflicto(opcion);if(opcion==='conservar-mios'){expect(calls[1].rev).toBe('f'.repeat(64));expect(calls[1].o).toEqual({respaldo:true});expect(ed.obtener().modelo!.nombre).toBe('Mío');}else{expect(calls.slice(1).map(c=>c.k)).toEqual(['POST','GET']);const copia=JSON.parse(calls[1].texto).modelo;expect(copia.id).not.toBe(d.m.id);expect(copia.nombre).toMatch(/^Mío \(copia \d\d:\d\d\)$/);expect(ed.obtener().modelo!.nombre).toBe(d.m.nombre);}ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 copia CAS fallida conserva local y nunca GET remoto',async()=>{const {d,ed}=await abierto();d.cliente.guardar=async()=>({conflicto:'f'.repeat(64)});d.cliente.crear=async()=>({estado:507,error:'Límite'});cambiar(ed);await ed.guardarAhora();const antes=d.peticiones.length;await ed.resolverConflicto('usar-guardada');expect(d.peticiones.length).toBe(antes);expect(ed.obtener().modelo!.nombre).toBe('Cambiado');expect(d.borradores.has(d.m.id)).toBe(true);ed.salirIgualmente();});
for(const estado of [400,401,404,413,422])test(`WP-13 DES§8.4 HTTP${estado} conserva borrador y detiene auto con estado fiel`,async()=>{const {d,ed}=await abierto();let n=0;d.cliente.guardar=async()=>{n++;return {estado,error:'Fallo explícito'};};cambiar(ed);await ed.guardarAhora();expect(ed.obtener().guardado).toBe(estado===401?'sesion-vencida':estado===404?'eliminado':'error');expect(d.borradores.has(d.m.id)).toBe(true);await d.reloj.avanzar(20000);expect(n).toBe(1);if(estado===401){expect(ed.obtener().modo).toBe('navegacion');d.cliente.guardar=async()=>({rev:'b'.repeat(64)});await ed.guardarAhora();expect(ed.obtener().guardado).toBe('guardado');}ed.salirIgualmente();});
test('WP-13 DES§8.4 red caída y5xx retry2→60s y éxito no pierde borrador',async()=>{const {d,ed}=await abierto();let n=0;d.cliente.guardar=async()=>{n++;if(n<8)throw Error('Red');return {rev:'b'.repeat(64)};};cambiar(ed);await ed.guardarAhora();expect(ed.obtener().guardado).toBe('sin-conexion');for(const ms of [2000,4000,8000,16000,32000,60000,60000]){const antes=n;await d.reloj.avanzar(ms-1);expect(n).toBe(antes);expect(d.borradores.has(d.m.id)).toBe(true);await d.reloj.avanzar(1);expect(n).toBe(antes+1);}expect(n).toBe(8);expect(ed.obtener().guardado).toBe('guardado');ed.salirIgualmente();});
for(const v of ['local','nueva',''])test(`WP-13 DES§8.4 versión bundle independiente primera cabecera ${v||'ausente'}`,async()=>{const d=dependencias();d.version(v);const ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);expect(ed.obtener().guardado).toBe(v&&v!=='local'?'version-nueva':'guardado');cambiar(ed);await ed.guardarAhora();expect(ed.obtener().guardado).toBe(v&&v!=='local'?'version-nueva':'guardado');ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 canonicalizado GET concurrente conserva edición posterior y revisión real',async()=>{const {d,ed}=await abierto(),q=diferida<{texto:string;rev:string}>(),informe={normalizado:[{ruta:'modelo',mensaje:'Normalizado'}],descartado:[],ignorado:{},rechazos:[],visibilidad:[]};d.cliente.guardar=async()=>({rev:'b'.repeat(64),canonicalizado:true,informe});d.cliente.leer=async()=>q.promesa;cambiar(ed,'Enviado');const p=ed.guardarAhora();await ciclos();cambiar(ed,'Posterior');const canon=exportarV0({...d.m,nombre:'Servidor'});q.resolver({texto:canon,rev:'c'.repeat(64)});await p;expect(ed.obtener().modelo!.nombre).toBe('Posterior');expect(ed.obtener().rev).toBe('c'.repeat(64));expect(ed.obtener().guardado).toBe('pendiente');expect(ed.obtener().solicitud?.informe).toEqual(informe);expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('Posterior');ed.salirIgualmente();});
for(const opcion of ['recuperar','descartar','descargar'] as const)for(const misma of [false,true])test(`WP-13 DES§8.4 borrador ${opcion} base igual=${misma}`,async()=>{const d=dependencias(),texto=exportarV0({...d.m,nombre:'Borrador'});d.borradores.set(d.m.id,{base:(misma?'a':'z').repeat(64),texto,fecha:20});const ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);expect(ed.obtener().solicitud).toMatchObject({k:'borrador',servidorCambio:!misma});await ed.resolverBorrador(opcion);if(opcion==='recuperar'){expect(ed.obtener().modelo!.nombre).toBe('Borrador');if(!misma)expect(d.peticiones.find(p=>p.tipo==='PUT')!.o).toEqual({respaldo:true});}if(opcion==='descartar')expect(d.borradores.has(d.m.id)).toBe(false);if(opcion==='descargar'){expect(ed.obtener().solicitud?.texto).toBe(texto);expect(d.borradores.has(d.m.id)).toBe(true);}ed.salirIgualmente();});
test('WP-13 DES§8.4 apertura no canónica sin pérdidas usa importarV0 y respaldo primerPUT',async()=>{const d=dependencias();d.documento(JSON.stringify(JSON.parse(d.texto)));const ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);expect(ed.obtener().modelo!.id).toBe(d.m.id);expect(ed.obtener().guardado).toBe('pendiente');await ed.guardarAhora();expect(d.peticiones.find(p=>p.tipo==='PUT')!.o).toEqual({respaldo:true});ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 apertura con descartes exige decisión visible antes de reemplazar',async()=>{const d=dependencias(),raw=JSON.parse(d.texto);raw.modelo.vistasTipificadas=['nueva'];d.documento(JSON.stringify(raw));const ed=crearEditor(configuracion(d));await ed.abrir(d.m.id);expect(ed.obtener().modelo).toBeNull();expect(ed.obtener().solicitud?.k).toBe('informe');expect(ed.obtener().solicitud?.informe!.descartado.length).toBeGreaterThan(0);await ed.confirmarImportacion();expect(ed.obtener().modelo!.id).toBe(d.m.id);await ed.guardarAhora();expect(d.peticiones.find(p=>p.tipo==='PUT')!.o).toEqual({respaldo:true});ed.cerrar();await ciclos();});
test('WP-13 DES§8.4404 recrea mismoID y409 sólo entonces asigna nuevo',async()=>{const {d,ed}=await abierto(),post:string[]=[];d.cliente.guardar=async()=>({estado:404,error:'Eliminado'});d.cliente.crear=async texto=>{post.push(texto);return post.length===1?{estado:409,error:'Ocupado'}:{id:JSON.parse(texto).modelo.id,rev:'c'.repeat(64)};};cambiar(ed);await ed.guardarAhora();await ed.guardarDeNuevo();expect(JSON.parse(post[0]!).modelo.id).toBe(d.m.id);expect(JSON.parse(post[1]!).modelo.id).not.toBe(d.m.id);expect(ed.obtener().modelo!.nombre).toBe('Cambiado');expect(ed.obtener().guardado).toBe('guardado');ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 cerrar guarda antes de salir y fracaso mantiene borrador/decisión',async()=>{const {d,ed}=await abierto();d.cliente.guardar=async()=>({estado:413,error:'Grande'});cambiar(ed);ed.cerrar();await ciclos();expect(ed.obtener().pantalla).toBe('editor');expect(ed.obtener().solicitud?.k).toBe('salida');expect(d.borradores.has(d.m.id)).toBe(true);ed.salirIgualmente();expect(ed.obtener().pantalla).toBe('biblioteca');expect(d.borradores.has(d.m.id)).toBe(true);});
test('WP-13 DES§8.4 respuesta antigua nunca reemplaza modelo nuevo y su autoguardado continúa',async()=>{const {d,ed}=await abierto(),q=diferida<{rev:string}>();let n=0;d.cliente.guardar=async()=>++n===1?q.promesa:{rev:'d'.repeat(64)};cambiar(ed,'Anterior');const p=ed.guardarAhora();await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-otro',nombre:'Otro'});d.documento(exportarV0(otro),'c'.repeat(64));await ed.abrir(otro.id);cambiar(ed,'Nuevo editado');q.resolver({rev:'b'.repeat(64)});await p;expect(ed.obtener().modelo!.id).toBe(otro.id);expect(ed.obtener().rev).toBe('c'.repeat(64));await d.reloj.avanzar(1500);expect(n).toBe(2);ed.cerrar();await ciclos();});
test('WP-13 DES§8.4 fallback memoria no depende de IndexedDB y entrega copias',async()=>{const local=crearAlmacenLocal({indexedDB:null}),b={base:'rev',texto:'local',fecha:23};await local.escribir('id',b);b.texto='mutado';const leido=await local.leer('id');expect(leido!.texto).toBe('local');leido!.texto='otra-mutación';expect((await local.leer('id'))!.texto).toBe('local');expect(await local.ids()).toEqual(['id']);await local.borrar('id');expect(await local.leer('id')).toBeNull();});

test('WP-13 DES§8.4 borrador posterior al PUT conserva base de revisión nueva',async()=>{
 const {d,ed}=await abierto(),q=diferida<{rev:string}>();d.cliente.guardar=async()=>q.promesa;cambiar(ed,'A');const p=ed.guardarAhora();await ciclos();cambiar(ed,'B');q.resolver({rev:'b'.repeat(64)});await p;expect(d.borradores.get(d.m.id)!.base).toBe('b'.repeat(64));expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');expect(ed.obtener().guardado).toBe('pendiente');ed.salirIgualmente();
});
test('WP-13 DES§8.4 lectura local antigua no borra borrador nuevo ni acredita guardado',async()=>{
 const {d,ed}=await abierto(),q=diferida<{base:string|null;texto:string;fecha:number}|null>();cambiar(ed,'A');await d.reloj.avanzar(500);const anterior={...d.borradores.get(d.m.id)!};d.local.leer=async()=>q.promesa;const p=ed.guardarAhora();await ciclos();cambiar(ed,'B');await d.reloj.avanzar(500);q.resolver(anterior);await p;expect(ed.obtener().guardado).toBe('pendiente');expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');ed.salirIgualmente();
});
for(const respuesta of [{estado:401,error:'Sesión'},{conflicto:'z'.repeat(64)}] as const)test(`WP-13 DES§8.4 respuesta vieja ${'estado' in respuesta?'401':'412'} no altera nueva apertura`,async()=>{
 const {d,ed}=await abierto(),q=diferida<any>();d.cliente.guardar=async()=>q.promesa;cambiar(ed,'Viejo');const p=ed.guardarAhora();await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-nuevo',nombre:'Nuevo'});d.documento(exportarV0(otro),'c'.repeat(64));await ed.abrir(otro.id);q.resolver(respuesta);await p;expect(ed.obtener().modelo!.id).toBe(otro.id);expect(ed.obtener().rev).toBe('c'.repeat(64));expect(ed.obtener().guardado).toBe('guardado');expect(ed.obtener().solicitud).toBeNull();ed.cerrar();await ciclos();
});
test('WP-13 DES§8.4 error401 no salta generación durante escritura local pendiente',async()=>{
 const {d,ed}=await abierto(),q=diferida<void>();cambiar(ed);d.cliente.guardar=async()=>({estado:401,error:'Sesión'});d.local.escribir=async()=>q.promesa;const p=ed.guardarAhora();await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-nuevo',nombre:'Nuevo'});d.documento(exportarV0(otro));await ed.abrir(otro.id);q.resolver();await p;expect(ed.obtener().guardado).toBe('guardado');expect(ed.obtener().modelo!.id).toBe(otro.id);expect(ed.obtener().solicitud).toBeNull();ed.cerrar();await ciclos();
});
test('WP-13 DES§8.4 POST canonicalizado relee documento e Informe sin perder edición',async()=>{
 const {d,ed}=await abierto(),informe={normalizado:[{ruta:'modelo',mensaje:'Canon'}],descartado:[],ignorado:{},rechazos:[],visibilidad:[]};d.cliente.guardar=async()=>({estado:404,error:'Eliminado'});cambiar(ed,'Local');await ed.guardarAhora();let lecturas=0;d.cliente.crear=async()=>({id:d.m.id,rev:'b'.repeat(64),canonicalizado:true,informe});d.cliente.leer=async()=>{lecturas++;return {texto:exportarV0({...d.m,nombre:'Canonizado'}),rev:'c'.repeat(64)};};await ed.guardarDeNuevo();expect(lecturas).toBe(1);expect(ed.obtener().modelo!.nombre).toBe('Canonizado');expect(ed.obtener().rev).toBe('c'.repeat(64));expect(ed.obtener().solicitud?.informe).toEqual(informe);ed.cerrar();await ciclos();
});
test('WP-13 DES§8.4 borrador de otro ID se conserva y no sustituye modelo',async()=>{
 const {d,ed}=await abierto();d.borradores.set(d.m.id,{base:'a'.repeat(64),texto:exportarV0(crearModelo({id:'m-equivocado',nombre:'Otro'})),fecha:1});await ed.resolverBorrador('recuperar');expect(ed.obtener().modelo!.id).toBe(d.m.id);expect(ed.obtener().franja?.tipo).toBe('rechazo');expect(d.borradores.has(d.m.id)).toBe(true);ed.salirIgualmente();
});

test('WP-13 DES§8.1 cliente cubre rutas sesión biblioteca papelera y DTO completos',async()=>{
 const informe={normalizado:[],descartado:[],ignorado:{},rechazos:[],visibilidad:[]},fila={id:'m',nombre:'Modelo',modificado:'t',rev:'r',bytes:2,cosas:0,opds:1},papel={entrada:'archivo',id:'m',nombre:'Modelo',eliminado:'t',motivo:'eliminado' as const},calls:{u:string;i:RequestInit}[]=[];
 const respuestas=[new Response(JSON.stringify({email:'prueba'})),new Response(null,{status:204}),new Response(null,{status:204}),new Response(JSON.stringify({modelos:[fila]})),new Response('genuino',{headers:{ETag:'"r"'}}),new Response(JSON.stringify({id:'m',rev:'r',canonicalizado:true,informe})),new Response(null,{status:204}),new Response(JSON.stringify({entradas:[papel]})),new Response(JSON.stringify({id:'m',rev:'r',canonicalizado:true,informe})),new Response(null,{status:204})];
 const c=crearCliente((async(u,i)=>{calls.push({u:String(u),i:i!});return respuestas.shift()!;}) as typeof fetch,'/base');expect(await c.sesion()).toEqual({email:'prueba'});expect(await c.entrar('prueba','sintética')).toBe('ok');await c.salir();expect(await c.listar()).toEqual([fila]);expect(await c.leer('a/b')).toEqual({texto:'genuino',rev:'r'});expect(await c.crear('texto')).toEqual({id:'m',rev:'r',canonicalizado:true,informe});await c.eliminar('a/b');expect(await c.papelera()).toEqual([papel]);expect(await c.restaurar('a/b')).toEqual({id:'m',rev:'r',canonicalizado:true,informe});await c.purgar('a/b');expect(calls.map(x=>x.u)).toEqual(['/base/api/sesion','/base/api/sesion','/base/api/sesion','/base/api/modelos','/base/api/modelos/a%2Fb','/base/api/modelos','/base/api/modelos/a%2Fb','/base/api/papelera','/base/api/papelera/a%2Fb/restaurar','/base/api/papelera/a%2Fb']);expect(calls.map(x=>x.i.method)).toEqual(['GET','POST','DELETE','GET','GET','POST','DELETE','GET','POST','DELETE']);for(const {i} of calls){expect(i.credentials).toBe('same-origin');expect(new Headers(i.headers).get('X-Opforja')).toBe(i.method==='GET'?null:'1');}expect(JSON.parse(calls[1]!.i.body as string)).toEqual({email:'prueba',clave:'sintética'});
});
for(const estado of [400,401,404,413,422,429,500])test(`WP-13 DES§8.1 cliente mantiene fallo${estado} Informe y versión`,async()=>{
 const informe={normalizado:[],descartado:[{ruta:'x',mensaje:'retirado'}],ignorado:{},rechazos:[],visibilidad:[]},c=crearCliente((async()=>new Response(JSON.stringify({error:'Exacto',informe,reintentarEn:17}),{status:estado,headers:{'X-Opforja-Version':'B'}})) as unknown as typeof fetch);expect(await c.crear('texto')).toMatchObject({estado,error:'Exacto',informe});expect(await c.restaurar('entrada')).toMatchObject({estado,error:'Exacto',informe});expect(c.versionServidor()).toBe('B');if(estado===401){expect(await c.sesion()).toBeNull();expect(await c.entrar('a','b')).toBe('credenciales');}if(estado===429)expect(await c.entrar('a','b')).toEqual({reintentarEn:17});if(estado===404)expect(await c.leer('m')).toBe('no-existe');
});
function idbDoble(){
 const datos=new Map<string,unknown>([['m',{base:'vieja',texto:'anterior',fecha:0}]]);let fallar=false,lecturas=0;
 const db={objectStoreNames:{contains:()=>true},transaction(){const tx:any={objectStore(){return {get(id:string){lecturas++;return request(datos.get(id));},getAllKeys(){lecturas++;return request([...datos.keys()]);},put(b:unknown,id:string){return request(undefined,()=>datos.set(id,b),fallar);},delete(id:string){return request(undefined,()=>datos.delete(id),fallar);}};}};function request(valor:unknown,mutar?:()=>void,error=false){const r:any={result:valor};queueMicrotask(()=>{if(error){tx.onabort?.();return;}mutar?.();r.onsuccess?.();tx.oncomplete?.();});return r;}return tx;}};
 const fabrica={open(){const r:any={result:db};queueMicrotask(()=>r.onsuccess?.());return r;}} as unknown as IDBFactory;return {fabrica,fallar(){fallar=true;},lecturas:()=>lecturas};
}
test('WP-13 DES§8.4 fallo transaccional no vuelve a lecturaDB vieja y conserva copia actual',async()=>{
 const f=idbDoble(),local=crearAlmacenLocal({indexedDB:f.fabrica});expect((await local.leer('m'))!.texto).toBe('anterior');f.fallar();const b={base:'nueva',texto:'actual',fecha:2};await local.escribir('m',b);b.texto='mutado';const leidas=f.lecturas();expect(await local.leer('m')).toEqual({base:'nueva',texto:'actual',fecha:2});expect(await local.ids()).toEqual(['m']);expect(f.lecturas()).toBe(leidas);await local.borrar('m');expect(await local.leer('m')).toBeNull();
});
test('WP-13 DES§8.4 error de aperturaIDB usa memoria sin bloquear promesas',async()=>{
 const fabrica={open(){const r:any={};queueMicrotask(()=>r.onerror?.());return r;}} as unknown as IDBFactory,local=crearAlmacenLocal({indexedDB:fabrica});await local.escribir('m',{base:null,texto:'recuperable',fecha:1});expect((await local.leer('m'))!.texto).toBe('recuperable');
});
test('WP-13 DES§8.4 borrar local tardío no elimina edición nueva durante limpieza',async()=>{
 const {d,ed}=await abierto(),q=diferida<void>();cambiar(ed,'A');await d.reloj.avanzar(500);const borrar=d.local.borrar;d.local.borrar=async id=>{await q.promesa;await borrar(id);};const p=ed.guardarAhora();await ciclos();cambiar(ed,'B');await d.reloj.avanzar(500);q.resolver();await p;expect(ed.obtener().guardado).toBe('pendiente');expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');expect(d.borradores.get(d.m.id)!.base).toBe('b'.repeat(64));ed.salirIgualmente();
});
test('WP-13 DES§8.4 abrir otra vista con guardado fallido mantiene modelo y salida explícita',async()=>{
 const {d,ed}=await abierto();d.cliente.guardar=async()=>({estado:413,error:'Límite'});cambiar(ed,'Local');await ed.abrir('otro');expect(ed.obtener().modelo!.id).toBe(d.m.id);expect(ed.obtener().solicitud?.k).toBe('salida');expect(d.peticiones.filter(p=>p.tipo==='GET')).toHaveLength(1);ed.salirIgualmente();
});
test('WP-13 DES§8.4 GET viejo no reemplaza nueva apertura ni cancela historial',async()=>{
 const d=dependencias(),q=diferida<{texto:string;rev:string}>(),ed=crearEditor(configuracion(d));d.cliente.leer=async id=>id==='m-viejo'?q.promesa:{texto:d.texto,rev:'c'.repeat(64)};const p=ed.abrir('m-viejo');await ciclos();await ed.abrir(d.m.id);cambiar(ed,'Nuevo local');q.resolver({texto:exportarV0(crearModelo({id:'m-viejo',nombre:'Viejo'})),rev:'a'.repeat(64)});await p;expect(ed.obtener().modelo!.id).toBe(d.m.id);expect(ed.obtener().modelo!.nombre).toBe('Nuevo local');expect(ed.obtener().pasado).toHaveLength(1);expect(ed.obtener().rev).toBe('c'.repeat(64));ed.salirIgualmente();
});
test('WP-13 DES§8.4 cierre antiguo no cierra ni bloquea modelo abierto después',async()=>{
 const {d,ed}=await abierto(),q=diferida<{rev:string}>();cambiar(ed,'Viejo');d.cliente.guardar=async()=>q.promesa;ed.cerrar();await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-nuevo',nombre:'Nuevo'});d.documento(exportarV0(otro));await ed.abrir(otro.id);q.resolver({rev:'b'.repeat(64)});await ciclos();expect(ed.obtener().pantalla).toBe('editor');expect(ed.obtener().modelo!.id).toBe(otro.id);expect(ed.obtener().solicitud).toBeNull();ed.salirIgualmente();
});
test('WP-13 DES§8.4 POST canonicalizado con GET concurrente conserva nueva edición',async()=>{
 const {d,ed}=await abierto(),q=diferida<{texto:string;rev:string}>();d.cliente.guardar=async()=>({estado:404,error:'Eliminado'});cambiar(ed,'A');await ed.guardarAhora();d.cliente.crear=async()=>({id:d.m.id,rev:'b'.repeat(64),canonicalizado:true});d.cliente.leer=async()=>q.promesa;const p=ed.guardarDeNuevo();await ciclos();cambiar(ed,'B');q.resolver({texto:exportarV0({...d.m,nombre:'Servidor'}),rev:'c'.repeat(64)});await p;expect(ed.obtener().modelo!.nombre).toBe('B');expect(ed.obtener().rev).toBe('c'.repeat(64));expect(ed.obtener().guardado).toBe('pendiente');expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');ed.salirIgualmente();
});
test('WP-13 DES§8.4 resolver CAS con borrado pendiente no reabre modelo antiguo',async()=>{
 const {d,ed}=await abierto(),q=diferida<void>();d.cliente.guardar=async()=>({conflicto:'f'.repeat(64)});cambiar(ed);await ed.guardarAhora();d.local.borrar=async()=>q.promesa;const p=ed.resolverConflicto('usar-guardada');await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-nuevo',nombre:'Nuevo'});d.documento(exportarV0(otro));await ed.abrir(otro.id);const antes=d.peticiones.filter(p=>p.tipo==='GET').length;q.resolver();await p;expect(d.peticiones.filter(p=>p.tipo==='GET')).toHaveLength(antes);expect(ed.obtener().modelo!.id).toBe(otro.id);ed.salirIgualmente();
});
test('WP-13 DES§8.4 recrear con limpieza tardía conserva cambios nuevos y nueva base',async()=>{
 const {d,ed}=await abierto(),q=diferida<void>();d.cliente.guardar=async()=>({estado:404,error:'Eliminado'});cambiar(ed,'A');await ed.guardarAhora();d.local.borrar=async id=>{await q.promesa;d.borradores.delete(id);};const p=ed.guardarDeNuevo();await ciclos();cambiar(ed,'B');await d.reloj.avanzar(500);q.resolver();await p;expect(ed.obtener().guardado).toBe('pendiente');expect(JSON.parse(d.borradores.get(d.m.id)!.texto).modelo.nombre).toBe('B');expect(d.borradores.get(d.m.id)!.base).toBe('c'.repeat(64));ed.salirIgualmente();
});
test('WP-13 DES§8.4 descartar borrador antiguo no cambia modal del modelo nuevo',async()=>{
 const {d,ed}=await abierto(),q=diferida<void>();d.borradores.set(d.m.id,{base:'a',texto:d.texto,fecha:1});d.local.borrar=async()=>q.promesa;const p=ed.resolverBorrador('descartar');await ciclos();ed.salirIgualmente();const otro=crearModelo({id:'m-nuevo',nombre:'Nuevo'});d.documento(exportarV0(otro));await ed.abrir(otro.id);ed.solicitar({k:'ayuda'});ed.fijarModo('gestion-modal');q.resolver();await p;expect(ed.obtener().solicitud?.k).toBe('ayuda');expect(ed.obtener().modo).toBe('gestion-modal');ed.salirIgualmente();
});

test('T-287 WP-14 apertura con pérdidas entrega bytes originales al Informe antes de confirmar', async () => {
    const d = dependencias(), raw = JSON.parse(d.texto); raw.modelo.vistasTipificadas = ['retirada'];
    const original = '  ' + JSON.stringify(raw) + '\n'; d.documento(original);
    const ed = crearEditor(configuracion(d)); await ed.abrir(d.m.id);
    expect(ed.obtener().modelo).toBeNull(); expect(ed.obtener().solicitud?.k).toBe('informe');
    expect(ed.obtener().solicitud?.informe!.descartado.length).toBeGreaterThan(0);
    expect(d.peticiones.filter(p => p.tipo === 'PUT')).toHaveLength(0);
    expect(ed.obtener().solicitud?.texto).toBe(original);
    await ed.confirmarImportacion(); expect(ed.obtener().modelo!.id).toBe(d.m.id); expect(ed.obtener().rev).toBe('a'.repeat(64));
    await ed.guardarAhora(); expect(d.peticiones.find(p => p.tipo === 'PUT')!.o).toEqual({ respaldo: true }); ed.salirIgualmente();
});
