// [JOYAS §1-3] Chrome UI consume tokens centralizados; canvas semántico invariante.
import { tokens } from "../tokens";
/**
 * Estilos compartidos del wizard AsistenteNuevoModelo (Preact CSS-in-JS).
 * Re-utilizados por todos los componentes en `ui/asistente/`.
 */

export const S = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    background: "rgba(15, 23, 42, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies preact.JSX.CSSProperties,
  modal: {
    width: "620px",
    maxHeight: "85vh",
    background: "${tokens.colors.fondoChrome}",
    borderRadius: tokens.radii.xl,
    boxShadow: tokens.shadows.asistente,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  } satisfies preact.JSX.CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 22px 8px",
    borderBottom: "1px solid ${tokens.colors.bordeChrome}",
  },
  progressBar: {
    flex: 1,
    height: "6px",
    borderRadius: tokens.radii.xs,
    background: "${tokens.colors.bordeChrome}",
    overflow: "hidden",
  },
  progressFill: (pct: number) => ({
    width: `${pct}%`,
    height: "100%",
    borderRadius: tokens.radii.xs,
    background: tokens.colors.canvas.proceso,
    transition: "width 0.3s ease",
  }) satisfies preact.JSX.CSSProperties,
  etapaLabel: {
    fontSize: "13px",
    fontWeight: 700,
    color: tokens.colors.textoSlate,
    whiteSpace: "nowrap",
  },
  body: {
    flex: 1,
    padding: "18px 22px",
    overflowY: "auto" as const,
    fontSize: "14px",
    color: tokens.colors.textoPrimario,
    lineHeight: "1.6",
    minHeight: "180px",
  },
  title: {
    fontSize: "17px",
    fontWeight: 700,
    color: tokens.colors.acentoSecundario,
    marginBottom: "14px",
  },
  desc: {
    marginBottom: "14px",
    color: tokens.colors.textoSlate,
  },
  input: {
    width: "100%",
    maxWidth: "420px",
    padding: "8px 12px",
    border: `1px solid ${tokens.colors.bordeControl}`,
    borderRadius: tokens.radii.control,
    fontSize: "14px",
    fontFamily: tokens.typography.familyChrome,
    color: tokens.colors.textoPrimario,
    background: tokens.colors.fondoInput,
  } satisfies preact.JSX.CSSProperties,
  textarea: {
    width: "100%",
    maxWidth: "420px",
    minHeight: "64px",
    padding: "8px 12px",
    border: `1px solid ${tokens.colors.bordeControl}`,
    borderRadius: tokens.radii.control,
    fontSize: "14px",
    fontFamily: tokens.typography.familyChrome,
    color: tokens.colors.textoPrimario,
    background: tokens.colors.fondoInput,
    resize: "vertical" as const,
  } satisfies preact.JSX.CSSProperties,
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  checkboxLabel: {
    fontSize: "14px",
    color: tokens.colors.textoPrimario,
  },
  select: {
    padding: "6px 10px",
    border: `1px solid ${tokens.colors.bordeControl}`,
    borderRadius: tokens.radii.control,
    fontSize: "14px",
    fontFamily: tokens.typography.familyChrome,
    background: tokens.colors.fondoInput,
  } satisfies preact.JSX.CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 22px 14px",
    borderTop: `1px solid ${tokens.colors.bordeChrome}`,
  },
  btnGroup: {
    display: "flex",
    gap: "8px",
  },
  btn: (primary: boolean): preact.JSX.CSSProperties => ({
    padding: "8px 18px",
    borderRadius: tokens.radii.control,
    border: primary ? `1px solid ${tokens.colors.infoBorde}` : `1px solid ${tokens.colors.bordeControl}`,
    background: primary ? tokens.colors.canvas.proceso : tokens.colors.fondoCard,
    color: primary ? tokens.colors.azulProfundo : tokens.colors.textoPrimario,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  skipBtn: {
    padding: "8px 18px",
    borderRadius: tokens.radii.control,
    border: `1px dashed ${tokens.colors.bordeControl}`,
    background: "transparent",
    color: tokens.colors.textoTerciario,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  mensaje: {
    fontSize: "13px",
    color: tokens.colors.errorOscuro,
    marginTop: "8px",
  },
  resumenLinea: {
    display: "flex",
    gap: "8px",
    marginBottom: "6px",
  },
  resumenLabel: {
    fontWeight: 700,
    color: tokens.colors.textoSlate,
    minWidth: "150px",
  },
  resumenValor: {
    color: tokens.colors.textoPrimario,
  },
  itemTag: {
    display: "inline-block",
    padding: "2px 10px",
    margin: "2px 4px 2px 0",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 700,
    background: tokens.colors.azulPanelSuave,
    color: tokens.colors.infoBorde,
  },
};
