// [JOYAS §1-3] Chrome UI consume tokens centralizados; canvas semántico invariante.
//
// Ronda 28 L5: Asistente Bauhaus. 3 etapas con header minimal
// "ETAPA N DE 3" uppercase tracking +0.08em ink-50, título Inter Tight 700/28
// letter-spacing -0.02em, cuerpo Inter Tight 400/14 ink-70 line-height 1.55,
// input principal 100% width con border ink-15 + caret cinabrio, hint debajo
// del input Inter Tight 12 ink-50, footer minimal Cancelar · Atrás · Siguiente
// con borde superior 1.5px ink-15.
import { transitionPreferida } from "../motion";
import { tokens } from "../tokens";

export const S = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    background: "rgba(10, 10, 10, 0.30)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
  } satisfies preact.JSX.CSSProperties,
  modal: {
    width: "620px",
    maxHeight: "85vh",
    background: tokens.colors.paper,
    border: `${tokens.stroke.base}px solid ${tokens.colors.ink}`,
    borderRadius: 0,
    boxShadow: tokens.shadows.flatXl,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    fontFamily: tokens.typography.familyChrome,
  } satisfies preact.JSX.CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "20px 28px 18px",
    borderBottom: `${tokens.stroke.base}px solid ${tokens.colors.ink}`,
  },
  progressBar: {
    flex: 1,
    height: "2px",
    borderRadius: 0,
    background: tokens.colors.ink15,
    overflow: "hidden",
  },
  progressFill: (pct: number) => ({
    width: `${pct}%`,
    height: "100%",
    borderRadius: 0,
    background: tokens.colors.ink,
    transition: transitionPreferida("width 150ms ease-out"),
  }) satisfies preact.JSX.CSSProperties,
  etapaLabel: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "11px",
    fontWeight: 500,
    color: tokens.colors.ink50,
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  body: {
    flex: 1,
    padding: "24px 28px",
    overflowY: "auto" as const,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "14px",
    color: tokens.colors.ink90,
    lineHeight: "1.55",
    minHeight: "200px",
  },
  title: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "28px",
    fontWeight: 700,
    color: tokens.colors.ink,
    margin: "0 0 16px",
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
  },
  desc: {
    margin: "0 0 20px",
    color: tokens.colors.ink70,
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: 1.55,
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: `1px solid ${tokens.colors.ink15}`,
    borderRadius: 0,
    fontSize: "15px",
    fontFamily: tokens.typography.familyChrome,
    color: tokens.colors.ink,
    background: tokens.colors.paper,
    caretColor: tokens.colors.accent,
  } satisfies preact.JSX.CSSProperties,
  inputHint: {
    margin: "6px 0 0",
    color: tokens.colors.ink50,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "12px",
    fontWeight: 400,
  } satisfies preact.JSX.CSSProperties,
  textarea: {
    width: "100%",
    minHeight: "72px",
    padding: "10px 14px",
    border: `1px solid ${tokens.colors.ink15}`,
    borderRadius: 0,
    fontSize: "15px",
    fontFamily: tokens.typography.familyChrome,
    color: tokens.colors.ink,
    background: tokens.colors.paper,
    resize: "vertical" as const,
    caretColor: tokens.colors.accent,
  } satisfies preact.JSX.CSSProperties,
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "8px",
  },
  checkboxLabel: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "14px",
    color: tokens.colors.ink,
  },
  select: {
    padding: "8px 12px",
    border: `1px solid ${tokens.colors.ink15}`,
    borderRadius: 0,
    fontSize: "14px",
    fontFamily: tokens.typography.familyChrome,
    color: tokens.colors.ink,
    background: tokens.colors.paper,
  } satisfies preact.JSX.CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "space-between",
    padding: "16px 28px",
    borderTop: `${tokens.stroke.base}px solid ${tokens.colors.ink15}`,
  },
  btnGroup: {
    display: "flex",
    gap: "8px",
  },
  btn: (primary: boolean): preact.JSX.CSSProperties => ({
    minHeight: "32px",
    padding: "8px 18px",
    borderRadius: 0,
    border: `${tokens.stroke.base}px solid ${tokens.colors.ink}`,
    background: primary ? tokens.colors.ink : tokens.colors.paper,
    color: primary ? tokens.colors.paper : tokens.colors.ink,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: tokens.transitions.fast,
  }),
  skipBtn: {
    minHeight: "32px",
    padding: "8px 18px",
    borderRadius: 0,
    border: `1px dashed ${tokens.colors.ink15}`,
    background: "transparent",
    color: tokens.colors.ink50,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "13px",
    fontWeight: 400,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  mensaje: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "13px",
    color: tokens.colors.accent,
    marginTop: "8px",
  },
  resumenLinea: {
    display: "flex",
    gap: "12px",
    marginBottom: "8px",
  },
  resumenLabel: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "11px",
    fontWeight: 500,
    color: tokens.colors.ink50,
    minWidth: "150px",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  resumenValor: {
    fontFamily: tokens.typography.familyChrome,
    fontSize: "14px",
    color: tokens.colors.ink,
  },
  itemTag: {
    display: "inline-block",
    padding: "2px 10px",
    margin: "2px 4px 2px 0",
    borderRadius: 0,
    border: `1px solid ${tokens.colors.ink15}`,
    fontFamily: tokens.typography.familyChrome,
    fontSize: "12px",
    fontWeight: 500,
    background: tokens.colors.paper,
    color: tokens.colors.ink70,
  },
};
