/**
 * Estilos compartidos del wizard AsistenteNuevoModelo (Preact CSS-in-JS).
 * Re-utilizados por todos los componentes en `ui/asistente/`.
 */

export const S = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    background: "rgba(15, 23, 42, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies preact.JSX.CSSProperties,
  modal: {
    width: "620px",
    maxHeight: "85vh",
    background: "#ffffff",
    borderRadius: "10px",
    boxShadow: "0 20px 60px rgba(16, 24, 40, 0.22)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  } satisfies preact.JSX.CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 22px 8px",
    borderBottom: "1px solid #e4eaf1",
  },
  progressBar: {
    flex: 1,
    height: "6px",
    borderRadius: "3px",
    background: "#e4eaf1",
    overflow: "hidden",
  },
  progressFill: (pct: number) => ({
    width: `${pct}%`,
    height: "100%",
    borderRadius: "3px",
    background: "#3BC3FF",
    transition: "width 0.3s ease",
  }) satisfies preact.JSX.CSSProperties,
  etapaLabel: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#334155",
    whiteSpace: "nowrap",
  },
  body: {
    flex: 1,
    padding: "18px 22px",
    overflowY: "auto" as const,
    fontSize: "14px",
    color: "#1f2937",
    lineHeight: "1.6",
    minHeight: "180px",
  },
  title: {
    fontSize: "17px",
    fontWeight: 700,
    color: "#1a3763",
    marginBottom: "14px",
  },
  desc: {
    marginBottom: "14px",
    color: "#334155",
  },
  input: {
    width: "100%",
    maxWidth: "420px",
    padding: "8px 12px",
    border: "1px solid #c8d2df",
    borderRadius: "5px",
    fontSize: "14px",
    fontFamily: "Arial, sans-serif",
    color: "#1f2937",
    background: "#fafbfc",
  } satisfies preact.JSX.CSSProperties,
  textarea: {
    width: "100%",
    maxWidth: "420px",
    minHeight: "64px",
    padding: "8px 12px",
    border: "1px solid #c8d2df",
    borderRadius: "5px",
    fontSize: "14px",
    fontFamily: "Arial, sans-serif",
    color: "#1f2937",
    background: "#fafbfc",
    resize: "vertical" as const,
  } satisfies preact.JSX.CSSProperties,
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  checkboxLabel: {
    fontSize: "14px",
    color: "#1f2937",
  },
  select: {
    padding: "6px 10px",
    border: "1px solid #c8d2df",
    borderRadius: "5px",
    fontSize: "14px",
    fontFamily: "Arial, sans-serif",
    background: "#fafbfc",
  } satisfies preact.JSX.CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 22px 14px",
    borderTop: "1px solid #e4eaf1",
  },
  btnGroup: {
    display: "flex",
    gap: "8px",
  },
  btn: (primary: boolean): preact.JSX.CSSProperties => ({
    padding: "8px 18px",
    borderRadius: "5px",
    border: primary ? "1px solid #147aa5" : "1px solid #c8d2df",
    background: primary ? "#3BC3FF" : "#f9fbfd",
    color: primary ? "#0b2f3f" : "#1f2937",
    fontFamily: "Arial, sans-serif",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  skipBtn: {
    padding: "8px 18px",
    borderRadius: "5px",
    border: "1px dashed #c8d2df",
    background: "transparent",
    color: "#667085",
    fontFamily: "Arial, sans-serif",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  mensaje: {
    fontSize: "13px",
    color: "#b91c1c",
    marginTop: "8px",
  },
  resumenLinea: {
    display: "flex",
    gap: "8px",
    marginBottom: "6px",
  },
  resumenLabel: {
    fontWeight: 700,
    color: "#334155",
    minWidth: "150px",
  },
  resumenValor: {
    color: "#1f2937",
  },
  itemTag: {
    display: "inline-block",
    padding: "2px 10px",
    margin: "2px 4px 2px 0",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 700,
    background: "#e4f0fd",
    color: "#147aa5",
  },
};
